# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: Hook - Post-Docker Tests
description: Runs user's hook script after Docker image is built for integration tests, security scans, or validation

inputs:
  script-sub-path:
    description: 'Path to script relative to .github/ (e.g., bin/post-docker.bash)'
    required: true
  version:
    description: 'Version string'
    required: true
  docker-tag:
    description: 'Docker tag'
    required: true
  docker-image-name:
    description: 'Docker image name'
    required: true
  project-name:
    description: 'Project name'
    required: true
  is-release:
    description: 'Whether this is a release build'
    required: true
  target-image-full-uri:
    description: 'Full target image URI (registry/name:tag)'
    required: true

runs:
  using: composite
  steps:
    - name: Run post-docker tests hook
      shell: bash
      env:
        HOOK_SCRIPT_SUB_PATH: .github/${{ inputs.script-sub-path }}
        VERSION: ${{ inputs.version }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
        DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
        PROJECT_NAME: ${{ inputs.project-name }}
        IS_RELEASE: ${{ inputs.is-release }}
        TARGET_IMAGE_FULL_URI: ${{ inputs.target-image-full-uri }}
      run: .github/buildon-github-actions/src/scripts/main/hook-post-docker-tests
