# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
name: GitHub Release
description: Create GitHub release with assets from prepared directory

inputs:
  # Build output
  output-sub-path:
    description: 'Build output directory (relative)'
    required: false
    default: 'target'
  # GitHub release
  github-release-enabled:
    description: 'Create a GitHub release on version tags'
    required: false
    default: 'true'
  github-release-substituted-files:
    description: 'Files with token substitution and version suffix (space-separated)'
    required: false
    default: ''
  github-release-verbatim-files:
    description: 'Files copied as-is with version suffix only (space-separated)'
    required: false
    default: ''
  github-release-notes:
    description: 'Inline release notes string (mutually exclusive with github-release-notes-file)'
    required: false
    default: ''
  github-release-notes-file:
    description: 'Path to release notes file relative to output-sub-path (mutually exclusive with github-release-notes)'
    required: false
    default: ''
  github-release-add-version-to-filenames:
    description: 'Add version suffix to release filenames (e.g., file.yaml -> file-1.2.3.yaml)'
    required: false
    default: 'true'

  # Action-specific inputs
  github-release-tag:
    description: Release tag
    required: false
    default: ${{ github.ref_name }}
  github-release-title:
    description: Release title
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Create release
      if: inputs.github-release-enabled == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        OUTPUT_SUB_PATH: ${{ inputs.output-sub-path }}
        TAG: ${{ inputs.github-release-tag }}
        NOTES: ${{ inputs.github-release-notes }}
        NOTES_FILE: ${{ inputs.github-release-notes-file }}
        TITLE: ${{ inputs.github-release-title }}
      run: |
        RELEASE_DIR="${OUTPUT_SUB_PATH}/github-release"

        # Collect files from prepared directory
        FILES=""
        if [[ -d "${RELEASE_DIR}" ]]; then
          for f in "${RELEASE_DIR}"/*; do
            if [[ -f "$f" ]]; then
              FILES="${FILES} ${f}"
            fi
          done
        fi

        # Fail if both notes and notes-file are set - pick one
        if [[ -n "${NOTES_FILE}" ]] && [[ -n "${NOTES}" ]]; then
          echo "::error::Both github-release-notes and github-release-notes-file are set. Use one or the other, not both."
          exit 1
        fi

        if [[ -n "${NOTES_FILE}" ]]; then
          RESOLVED_NOTES_FILE="${OUTPUT_SUB_PATH}/${NOTES_FILE}"
          if [[ ! -f "${RESOLVED_NOTES_FILE}" ]]; then
            echo "::error::Release notes file not found: ${RESOLVED_NOTES_FILE}"
            exit 1
          fi
          # shellcheck disable=SC2086 # Intentional word splitting for FILES
          gh release create "${TAG}" ${FILES} --title "${TITLE}" --notes-file "${RESOLVED_NOTES_FILE}"
        elif [[ -n "${NOTES}" ]]; then
          # shellcheck disable=SC2086 # Intentional word splitting for FILES
          gh release create "${TAG}" ${FILES} --title "${TITLE}" --notes "${NOTES}"
        else
          # shellcheck disable=SC2086 # Intentional word splitting for FILES
          gh release create "${TAG}" ${FILES} --title "${TITLE}" --generate-notes
        fi
