# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.

apiVersion: kaptain.org/1.23
kind: basic-quality-and-versioning

spec:
  global:
    configSubPath: src/config
    tokens:
      delimiterStyle: shell
      nameStyle: PascalCase
      nameValidation: MATCH
      allowBuiltinOverride: false
      valueTrailingNewline: strip-for-single-line
