#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Tests for generate-kubernetes-serviceaccount

load helpers

setup() {
  export OUTPUT_SUB_PATH=$(create_test_dir "gen-serviceaccount")
  export PROJECT_NAME="my-project"
  export TOKEN_NAME_STYLE="PascalCase"
  export TOKEN_DELIMITER_STYLE="shell"
  export KUBERNETES_SERVICEACCOUNT_GENERATION_ENABLED="true"
}

teardown() {
  :
}

# Helper to read generated manifest
read_manifest() {
  cat "$OUTPUT_SUB_PATH/manifests/combined/serviceaccount.yaml"
}

read_manifest_with_suffix() {
  local suffix="$1"
  cat "$OUTPUT_SUB_PATH/manifests/combined/serviceaccount-${suffix}.yaml"
}

read_manifest_in_subpath() {
  local subpath="$1"
  cat "$OUTPUT_SUB_PATH/manifests/combined/${subpath}/serviceaccount.yaml"
}

# =============================================================================
# Generation enabled/disabled
# =============================================================================

@test "skips generation when not enabled" {
  export KUBERNETES_SERVICEACCOUNT_GENERATION_ENABLED="false"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not enabled"* ]]
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/serviceaccount.yaml" ]
}

@test "skips generation when enabled not set" {
  unset KUBERNETES_SERVICEACCOUNT_GENERATION_ENABLED

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not enabled"* ]]
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/serviceaccount.yaml" ]
}

@test "generates when explicitly enabled" {
  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/serviceaccount.yaml" ]
}

# =============================================================================
# Basic functionality
# =============================================================================

@test "generates valid ServiceAccount structure" {
  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"apiVersion: v1"* ]]
  [[ "$manifest" == *"kind: ServiceAccount"* ]]
  [[ "$manifest" == *"metadata:"* ]]
  [[ "$manifest" == *'name: ${ProjectName}'* ]]
  [[ "$manifest" == *'namespace: ${Environment}'* ]]
}

@test "includes standard labels" {
  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"labels:"* ]]
  [[ "$manifest" == *'app: ${ProjectName}'* ]]
  [[ "$manifest" == *'app.kubernetes.io/name: ${ProjectName}'* ]]
  [[ "$manifest" == *'app.kubernetes.io/version: ${Version}'* ]]
  [[ "$manifest" == *"app.kubernetes.io/managed-by: kaptain"* ]]
}

@test "includes kaptain annotations" {
  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"annotations:"* ]]
  [[ "$manifest" == *'kaptain/project-name: ${ProjectName}'* ]]
  [[ "$manifest" == *'kaptain/version: ${Version}'* ]]
  [[ "$manifest" == *"kaptain/build-timestamp:"* ]]
  [[ "$manifest" == *'kaptain/generated-by: "Generated by Kaptain generate-kubernetes-serviceaccount"'* ]]
}

# =============================================================================
# Token styles
# =============================================================================

@test "respects PascalCase token name style" {
  export TOKEN_NAME_STYLE="PascalCase"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${ProjectName}'* ]]
  [[ "$manifest" == *'${Environment}'* ]]
}

@test "respects lower-kebab token name style" {
  export TOKEN_NAME_STYLE="lower-kebab"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${project-name}'* ]]
  [[ "$manifest" == *'${environment}'* ]]
}

@test "respects mustache substitution style" {
  export TOKEN_DELIMITER_STYLE="mustache"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'{{ ProjectName }}'* ]]
  [[ "$manifest" == *'{{ Environment }}'* ]]
}

@test "fails with unknown token name style" {
  export TOKEN_NAME_STYLE="unknown"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 2 ]
}

@test "fails with unknown substitution token style" {
  export TOKEN_DELIMITER_STYLE="unknown"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 3 ]
}

# =============================================================================
# Output paths
# =============================================================================

@test "creates output directory if missing" {
  # Use a fresh subdirectory that doesn't exist yet
  export OUTPUT_SUB_PATH="${OUTPUT_SUB_PATH}/fresh-subdir"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/serviceaccount.yaml" ]
}

@test "respects custom OUTPUT_SUB_PATH" {
  export OUTPUT_SUB_PATH=$(create_test_dir "serviceaccount-custom")

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/serviceaccount.yaml" ]
}

# =============================================================================
# Additional labels and annotations
# =============================================================================

@test "adds global additional labels" {
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=platform,cost-center=123"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"team: platform"* ]]
  [[ "$manifest" == *"cost-center: 123"* ]]
}

@test "adds serviceaccount-specific additional labels" {
  export KUBERNETES_SERVICEACCOUNT_ADDITIONAL_LABELS="sa-label=value"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"sa-label: value"* ]]
}

@test "serviceaccount labels override global labels" {
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=platform"
  export KUBERNETES_SERVICEACCOUNT_ADDITIONAL_LABELS="team=override"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"team: override"* ]]
  [[ "$manifest" != *"team: platform"* ]]
}

@test "adds global additional annotations" {
  export KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS="example.com/note=test"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"example.com/note: test"* ]]
}

@test "adds serviceaccount-specific additional annotations" {
  export KUBERNETES_SERVICEACCOUNT_ADDITIONAL_ANNOTATIONS="iam.gke.io/gcp-service-account=my-sa@project.iam.gserviceaccount.com"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"iam.gke.io/gcp-service-account: my-sa@project.iam.gserviceaccount.com"* ]]
}

# =============================================================================
# Name suffix
# =============================================================================

@test "suffix affects metadata.name" {
  export KUBERNETES_SERVICEACCOUNT_NAME_SUFFIX="backend"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest_with_suffix "backend")
  [[ "$manifest" == *'name: ${ProjectName}-backend'* ]]
}

@test "suffix affects output filename" {
  export KUBERNETES_SERVICEACCOUNT_NAME_SUFFIX="backend"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/serviceaccount-backend.yaml" ]
}

@test "no suffix uses default filename" {
  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/serviceaccount.yaml" ]
}

# =============================================================================
# Combined sub-path
# =============================================================================

@test "combined sub-path creates subdirectory in combined/" {
  export KUBERNETES_SERVICEACCOUNT_COMBINED_SUB_PATH="apps/backend"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/apps/backend/serviceaccount.yaml" ]
}

@test "combined sub-path affects metadata.name" {
  export KUBERNETES_SERVICEACCOUNT_COMBINED_SUB_PATH="apps-backend"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest_in_subpath "apps-backend")
  [[ "$manifest" == *'name: ${ProjectName}-apps-backend'* ]]
}

@test "combined sub-path with suffix: name is ProjectName-combined-suffix" {
  export KUBERNETES_SERVICEACCOUNT_COMBINED_SUB_PATH="apps"
  export KUBERNETES_SERVICEACCOUNT_NAME_SUFFIX="backend"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/apps/serviceaccount-backend.yaml" ]
  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/apps/serviceaccount-backend.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-apps-backend'* ]]
}

@test "nested combined sub-path replaces slashes with hyphens in name" {
  export KUBERNETES_SERVICEACCOUNT_COMBINED_SUB_PATH="omg/wtf"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/serviceaccount.yaml" ]
  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/serviceaccount.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg-wtf'* ]]
}

@test "combined sub-path validation rejects uppercase" {
  export KUBERNETES_SERVICEACCOUNT_COMBINED_SUB_PATH="Apps"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 5 ]
}

@test "combined sub-path validation rejects leading slash" {
  export KUBERNETES_SERVICEACCOUNT_COMBINED_SUB_PATH="/apps"

  run "$GENERATORS_DIR/generate-kubernetes-serviceaccount"
  [ "$status" -eq 6 ]
}
