#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Tests for generate-kubernetes-service

bats_require_minimum_version 1.5.0

load helpers

setup() {
  export OUTPUT_SUB_PATH=$(create_test_dir "gen-svc")
  export PROJECT_NAME="my-project"
  export TOKEN_NAME_STYLE="PascalCase"
  export TOKEN_DELIMITER_STYLE="shell"
  export KUBERNETES_SERVICE_GENERATION_ENABLED="true"
  export REPOSITORY_OWNER="kube-kaptain"
  export SOURCE_REPO="kube-kaptain/test-project"
  export IMAGE_URI="ghcr.io/kube-kaptain/test-project:1.0.0"
}

teardown() {
  dump_bats_result
  :
}

# Helper to read generated manifest
read_manifest() {
  cat "$OUTPUT_SUB_PATH/manifests/combined/service.yaml"
}

read_manifest_with_suffix() {
  local suffix="$1"
  cat "$OUTPUT_SUB_PATH/manifests/combined/service-${suffix}.yaml"
}

read_manifest_in_subpath() {
  local subpath="$1"
  cat "$OUTPUT_SUB_PATH/manifests/combined/${subpath}/service.yaml"
}

# =============================================================================
# Generation enabled/disabled
# =============================================================================

@test "skips generation when not enabled" {
  export KUBERNETES_SERVICE_GENERATION_ENABLED="false"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not enabled"* ]] || return 1
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/service.yaml" ]
}

@test "skips generation when enabled not set and workload is not deployment" {
  unset KUBERNETES_SERVICE_GENERATION_ENABLED
  export KUBERNETES_WORKLOAD_TYPE="none"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not enabled"* ]] || return 1
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/service.yaml" ]
}

@test "enables generation by default for deployment workload" {
  unset KUBERNETES_SERVICE_GENERATION_ENABLED
  export KUBERNETES_WORKLOAD_TYPE="deployment"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/service.yaml" ]
}

@test "generates when explicitly enabled" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/service.yaml" ]
}

# =============================================================================
# Basic functionality
# =============================================================================

@test "generates valid Service structure" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"apiVersion: v1"* ]] || return 1
  [[ "$manifest" == *"kind: Service"* ]] || return 1
  [[ "$manifest" == *"metadata:"* ]] || return 1
  [[ "$manifest" == *'name: ${ProjectName}'* ]] || return 1
  [[ "$manifest" == *'namespace: ${Environment}'* ]] || return 1
}

@test "includes spec section" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"spec:"* ]] || return 1
  [[ "$manifest" == *"type: ClusterIP"* ]] || return 1
  [[ "$manifest" == *"selector:"* ]] || return 1
  [[ "$manifest" == *'app: ${ProjectName}'* ]] || return 1
  [[ "$manifest" == *"ports:"* ]] || return 1
}

@test "includes standard labels" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"labels:"* ]] || return 1
  [[ "$manifest" == *'app: "${ProjectName}"'* ]] || return 1
  [[ "$manifest" == *'app.kubernetes.io/name: "${ProjectName}"'* ]] || return 1
  [[ "$manifest" == *'app.kubernetes.io/version: "${Version}"'* ]] || return 1
  [[ "$manifest" == *'app.kubernetes.io/managed-by: "Kaptain"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/version: "${Version}"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/project-name: "${ProjectName}"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/owner: "kube-kaptain"'* ]] || return 1
}

@test "includes kaptain annotations" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"annotations:"* ]] || return 1
  [[ "$manifest" == *'kaptain.org/project-name: "${ProjectName}"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/version: "${Version}"'* ]] || return 1
  [[ "$manifest" == *"kaptain.org/build-timestamp:"* ]] || return 1
  [[ "$manifest" == *'kaptain.org/generated-by: "Generated by Kaptain generate-kubernetes-service"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/built-by: "test"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/source-repository: "kube-kaptain/test-project"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/image-uri: "ghcr.io/kube-kaptain/test-project:1.0.0"'* ]] || return 1
}

# =============================================================================
# Service type
# =============================================================================

@test "defaults to ClusterIP type" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"type: ClusterIP"* ]] || return 1
}

@test "respects NodePort type" {
  export KUBERNETES_SERVICE_TYPE="NodePort"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"type: NodePort"* ]] || return 1
}

@test "respects LoadBalancer type" {
  export KUBERNETES_SERVICE_TYPE="LoadBalancer"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"type: LoadBalancer"* ]] || return 1
}

@test "fails with invalid service type" {
  export KUBERNETES_SERVICE_TYPE="invalid"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 4 ]
}

# =============================================================================
# Port configuration
# =============================================================================

@test "defaults to port 80 and targetPort 1024" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"port: 80"* ]] || return 1
  [[ "$manifest" == *"targetPort: 1024"* ]] || return 1
}

@test "respects custom service port" {
  export KUBERNETES_SERVICE_PORT="8080"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"port: 8080"* ]] || return 1
  [[ "$manifest" == *"targetPort: 1024"* ]] || return 1
}

@test "targetPort defaults to container port" {
  export KUBERNETES_WORKLOAD_CONTAINER_PORT="3000"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"port: 80"* ]] || return 1
  [[ "$manifest" == *"targetPort: 3000"* ]] || return 1
}

@test "respects different target port" {
  export KUBERNETES_SERVICE_PORT="80"
  export KUBERNETES_SERVICE_TARGET_PORT="8080"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"port: 80"* ]] || return 1
  [[ "$manifest" == *"targetPort: 8080"* ]] || return 1
}

@test "defaults to TCP protocol" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"protocol: TCP"* ]] || return 1
}

@test "respects UDP protocol" {
  export KUBERNETES_SERVICE_PROTOCOL="UDP"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"protocol: UDP"* ]] || return 1
}

@test "fails with invalid protocol" {
  export KUBERNETES_SERVICE_PROTOCOL="invalid"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 7 ]
}

# =============================================================================
# Token styles
# =============================================================================

@test "respects PascalCase token name style" {
  export TOKEN_NAME_STYLE="PascalCase"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${ProjectName}'* ]] || return 1
  [[ "$manifest" == *'${Environment}'* ]] || return 1
}

@test "respects lower-kebab token name style" {
  export TOKEN_NAME_STYLE="lower-kebab"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${project-name}'* ]] || return 1
  [[ "$manifest" == *'${environment}'* ]] || return 1
}

@test "respects mustache substitution style" {
  export TOKEN_DELIMITER_STYLE="mustache"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'{{ ProjectName }}'* ]] || return 1
  [[ "$manifest" == *'{{ Environment }}'* ]] || return 1
}

@test "fails with unknown token name style" {
  export TOKEN_NAME_STYLE="unknown"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 2 ]
}

@test "fails with unknown substitution token style" {
  export TOKEN_DELIMITER_STYLE="unknown"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 3 ]
}

# =============================================================================
# Output paths
# =============================================================================

@test "creates output directory if missing" {
  # Use a fresh subdirectory that doesn't exist yet
  export OUTPUT_SUB_PATH="${OUTPUT_SUB_PATH}/fresh-subdir"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/service.yaml" ]
}

@test "respects custom OUTPUT_SUB_PATH" {
  export OUTPUT_SUB_PATH=$(create_test_dir "gen-svc-custom")

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/service.yaml" ]
}

# =============================================================================
# Additional labels and annotations
# =============================================================================

@test "adds global additional labels" {
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=platform,cost-center=123"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'team: "platform"'* ]] || return 1
  [[ "$manifest" == *'cost-center: "123"'* ]] || return 1
}

@test "adds service-specific additional labels" {
  export KUBERNETES_SERVICE_ADDITIONAL_LABELS="svc-label=value"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'svc-label: "value"'* ]] || return 1
}

@test "service labels override global labels" {
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=platform"
  export KUBERNETES_SERVICE_ADDITIONAL_LABELS="team=override"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'team: "override"'* ]] || return 1
  [[ "$manifest" != *'team: "platform"'* ]] || return 1
}

@test "adds global additional annotations" {
  export KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS="example.com/note=test"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'example.com/note: "test"'* ]] || return 1
}

@test "adds service-specific additional annotations" {
  export KUBERNETES_SERVICE_ADDITIONAL_ANNOTATIONS="service.beta.kubernetes.io/aws-load-balancer-internal=true"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'service.beta.kubernetes.io/aws-load-balancer-internal: "true"'* ]] || return 1
}

# =============================================================================
# Name suffix
# =============================================================================

@test "suffix affects metadata.name" {
  export KUBERNETES_SERVICE_NAME_SUFFIX="api"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest_with_suffix "api")
  [[ "$manifest" == *'name: ${ProjectName}-api'* ]] || return 1
}

@test "suffix affects output filename" {
  export KUBERNETES_SERVICE_NAME_SUFFIX="api"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/service-api.yaml" ]
}

@test "no suffix uses default filename" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/service.yaml" ]
}

# =============================================================================
# Combined sub-path
# =============================================================================

@test "combined sub-path creates subdirectory in combined/" {
  export KUBERNETES_SERVICE_COMBINED_SUB_PATH="apps/backend"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/apps/backend/service.yaml" ]
}

@test "combined sub-path affects metadata.name" {
  export KUBERNETES_SERVICE_COMBINED_SUB_PATH="apps-backend"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest_in_subpath "apps-backend")
  [[ "$manifest" == *'name: ${ProjectName}-apps-backend'* ]] || return 1
}

@test "combined sub-path with suffix: name is ProjectName-combined-suffix" {
  export KUBERNETES_SERVICE_COMBINED_SUB_PATH="apps"
  export KUBERNETES_SERVICE_NAME_SUFFIX="api"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/apps/service-api.yaml" ]
  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/apps/service-api.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-apps-api'* ]] || return 1
}

@test "nested combined sub-path replaces slashes with hyphens in name" {
  export KUBERNETES_SERVICE_COMBINED_SUB_PATH="omg/wtf"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/service.yaml" ]
  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/service.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg-wtf'* ]] || return 1
}

@test "combined sub-path validation rejects uppercase" {
  export KUBERNETES_SERVICE_COMBINED_SUB_PATH="Apps"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 5 ]
}

@test "combined sub-path validation rejects leading slash" {
  export KUBERNETES_SERVICE_COMBINED_SUB_PATH="/apps"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 6 ]
}

# =============================================================================
# Selector
# =============================================================================

@test "selector uses project name token" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"selector:"* ]] || return 1
  [[ "$manifest" == *'app: ${ProjectName}'* ]] || return 1
}

# =============================================================================
# Headless service type
# =============================================================================

@test "Headless type sets clusterIP: None" {
  export KUBERNETES_SERVICE_TYPE="Headless"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"type: ClusterIP"* ]] || return 1
  [[ "$manifest" == *"clusterIP: None"* ]] || return 1
}

@test "Headless type includes selector" {
  export KUBERNETES_SERVICE_TYPE="Headless"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"selector:"* ]] || return 1
  [[ "$manifest" == *'app: ${ProjectName}'* ]] || return 1
}

@test "Headless type includes ports" {
  export KUBERNETES_SERVICE_TYPE="Headless"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"ports:"* ]] || return 1
  [[ "$manifest" == *"port: 80"* ]] || return 1
}

# =============================================================================
# NoSelector service type
# =============================================================================

@test "NoSelector type omits selector" {
  export KUBERNETES_SERVICE_TYPE="NoSelector"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" != *"selector:"* ]] || return 1
}

@test "NoSelector type includes ports" {
  export KUBERNETES_SERVICE_TYPE="NoSelector"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"ports:"* ]] || return 1
  [[ "$manifest" == *"port: 80"* ]] || return 1
}

# =============================================================================
# ExternalName service type
# =============================================================================

@test "ExternalName type requires external name" {
  export KUBERNETES_SERVICE_TYPE="ExternalName"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 4 ]
  [[ "$output" == *"KUBERNETES_SERVICE_EXTERNAL_NAME is required"* ]] || return 1
}

@test "ExternalName type sets externalName" {
  export KUBERNETES_SERVICE_TYPE="ExternalName"
  export KUBERNETES_SERVICE_EXTERNAL_NAME="my.external.service.com"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"type: ExternalName"* ]] || return 1
  [[ "$manifest" == *"externalName: my.external.service.com"* ]] || return 1
}

@test "ExternalName type omits ports" {
  export KUBERNETES_SERVICE_TYPE="ExternalName"
  export KUBERNETES_SERVICE_EXTERNAL_NAME="my.external.service.com"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" != *"ports:"* ]] || return 1
}

@test "ExternalName type omits selector" {
  export KUBERNETES_SERVICE_TYPE="ExternalName"
  export KUBERNETES_SERVICE_EXTERNAL_NAME="my.external.service.com"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" != *"selector:"* ]] || return 1
}

@test "ExternalName type omits clusterIP" {
  export KUBERNETES_SERVICE_TYPE="ExternalName"
  export KUBERNETES_SERVICE_EXTERNAL_NAME="my.external.service.com"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" != *"clusterIP:"* ]] || return 1
}

# =============================================================================
# NodePort specific features
# =============================================================================

@test "NodePort type allows nodePort specification" {
  export KUBERNETES_SERVICE_TYPE="NodePort"
  export KUBERNETES_SERVICE_NODE_PORT="30080"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"type: NodePort"* ]] || return 1
  [[ "$manifest" == *"nodePort: 30080"* ]] || return 1
}

@test "nodePort rejected for ClusterIP type" {
  export KUBERNETES_SERVICE_TYPE="ClusterIP"
  export KUBERNETES_SERVICE_NODE_PORT="30080"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 4 ]
  [[ "$output" == *"can only be used with NodePort"* ]] || return 1
}

# =============================================================================
# External traffic policy
# =============================================================================

@test "NodePort allows external traffic policy" {
  export KUBERNETES_SERVICE_TYPE="NodePort"
  export KUBERNETES_SERVICE_EXTERNAL_TRAFFIC_POLICY="Local"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"externalTrafficPolicy: Local"* ]] || return 1
}

@test "LoadBalancer allows external traffic policy" {
  export KUBERNETES_SERVICE_TYPE="LoadBalancer"
  export KUBERNETES_SERVICE_EXTERNAL_TRAFFIC_POLICY="Cluster"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"externalTrafficPolicy: Cluster"* ]] || return 1
}

@test "external traffic policy rejected for ClusterIP type" {
  export KUBERNETES_SERVICE_TYPE="ClusterIP"
  export KUBERNETES_SERVICE_EXTERNAL_TRAFFIC_POLICY="Local"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 4 ]
  [[ "$output" == *"can only be used with NodePort or LoadBalancer"* ]] || return 1
}

@test "invalid external traffic policy rejected" {
  export KUBERNETES_SERVICE_TYPE="NodePort"
  export KUBERNETES_SERVICE_EXTERNAL_TRAFFIC_POLICY="invalid"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 4 ]
  [[ "$output" == *"Must be 'Cluster' or 'Local'"* ]] || return 1
}

# =============================================================================
# Port name
# =============================================================================

@test "port name included when specified" {
  export KUBERNETES_SERVICE_PORT_NAME="http"

  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"name: http"* ]] || return 1
}

@test "port name omitted when not specified" {
  run "$GENERATORS_DIR/generate-kubernetes-service"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  # ports section should not have a name field (only port, targetPort, protocol)
  [[ "$manifest" != *"ports:"*"name:"* ]] || return 1
}
