#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Tests for generate-kubernetes-poddisruptionbudget

load helpers

setup() {
  export OUTPUT_SUB_PATH=$(create_test_dir "gen-pdb")
  export PROJECT_NAME="my-project"
  export TOKEN_NAME_STYLE="PascalCase"
  export TOKEN_DELIMITER_STYLE="shell"
  export KUBERNETES_WORKLOAD_TYPE="deployment"
  export KUBERNETES_PODDISRUPTIONBUDGET_GENERATION_ENABLED="true"
}

teardown() {
  :
}

# Helper to read generated manifest
read_manifest() {
  cat "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget.yaml"
}

read_manifest_with_suffix() {
  local suffix="$1"
  cat "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget-${suffix}.yaml"
}

read_manifest_in_subpath() {
  local subpath="$1"
  cat "$OUTPUT_SUB_PATH/manifests/combined/${subpath}/poddisruptionbudget.yaml"
}

# =============================================================================
# Generation enabled/disabled - smart defaults
# =============================================================================

@test "smart default: enabled for deployment workload type" {
  unset KUBERNETES_PODDISRUPTIONBUDGET_GENERATION_ENABLED
  export KUBERNETES_WORKLOAD_TYPE="deployment"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget.yaml" ]
}

@test "smart default: enabled for statefulset workload type" {
  unset KUBERNETES_PODDISRUPTIONBUDGET_GENERATION_ENABLED
  export KUBERNETES_WORKLOAD_TYPE="statefulset"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget.yaml" ]
}

@test "smart default: disabled for other workload types" {
  unset KUBERNETES_PODDISRUPTIONBUDGET_GENERATION_ENABLED
  export KUBERNETES_WORKLOAD_TYPE="cronjob"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not enabled"* ]]
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget.yaml" ]
}

@test "explicit false overrides smart default for deployment" {
  export KUBERNETES_PODDISRUPTIONBUDGET_GENERATION_ENABLED="false"
  export KUBERNETES_WORKLOAD_TYPE="deployment"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not enabled"* ]]
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget.yaml" ]
}

@test "explicit true overrides smart default for other types" {
  export KUBERNETES_PODDISRUPTIONBUDGET_GENERATION_ENABLED="true"
  export KUBERNETES_WORKLOAD_TYPE="cronjob"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget.yaml" ]
}

# =============================================================================
# Basic functionality
# =============================================================================

@test "generates valid PodDisruptionBudget structure" {
  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"apiVersion: policy/v1"* ]]
  [[ "$manifest" == *"kind: PodDisruptionBudget"* ]]
  [[ "$manifest" == *"metadata:"* ]]
  [[ "$manifest" == *'name: ${ProjectName}'* ]]
  [[ "$manifest" == *'namespace: ${Environment}'* ]]
}

@test "includes selector matching workload" {
  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"selector:"* ]]
  [[ "$manifest" == *"matchLabels:"* ]]
  [[ "$manifest" == *'app: ${ProjectName}'* ]]
}

@test "includes standard labels" {
  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"labels:"* ]]
  [[ "$manifest" == *'app: ${ProjectName}'* ]]
  [[ "$manifest" == *'app.kubernetes.io/name: ${ProjectName}'* ]]
  [[ "$manifest" == *'app.kubernetes.io/version: "${Version}"'* ]]
  [[ "$manifest" == *"app.kubernetes.io/managed-by: Kaptain"* ]]
}

@test "includes kaptain annotations" {
  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"annotations:"* ]]
  [[ "$manifest" == *'kaptain/project-name: ${ProjectName}'* ]]
  [[ "$manifest" == *'kaptain/version: "${Version}"'* ]]
  [[ "$manifest" == *"kaptain/build-timestamp:"* ]]
  [[ "$manifest" == *'kaptain/generated-by: "Generated by Kaptain generate-kubernetes-poddisruptionbudget"'* ]]
}

# =============================================================================
# Strategy and value
# =============================================================================

@test "default strategy is max-unavailable with value 1" {
  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"maxUnavailable: 1"* ]]
  [[ "$manifest" != *"minAvailable:"* ]]
}

@test "max-unavailable strategy generates maxUnavailable field" {
  export KUBERNETES_PODDISRUPTIONBUDGET_STRATEGY="max-unavailable"
  export KUBERNETES_PODDISRUPTIONBUDGET_VALUE="2"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"maxUnavailable: 2"* ]]
  [[ "$manifest" != *"minAvailable:"* ]]
}

@test "min-available strategy generates minAvailable field" {
  export KUBERNETES_PODDISRUPTIONBUDGET_STRATEGY="min-available"
  export KUBERNETES_PODDISRUPTIONBUDGET_VALUE="1"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"minAvailable: 1"* ]]
  [[ "$manifest" != *"maxUnavailable:"* ]]
}

@test "supports percentage values" {
  export KUBERNETES_PODDISRUPTIONBUDGET_STRATEGY="max-unavailable"
  export KUBERNETES_PODDISRUPTIONBUDGET_VALUE="25%"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"maxUnavailable: 25%"* ]]
}

@test "fails with invalid strategy" {
  export KUBERNETES_PODDISRUPTIONBUDGET_STRATEGY="invalid"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 4 ]
  [[ "$output" == *"Invalid"* ]]
  [[ "$output" == *"min-available"* ]]
  [[ "$output" == *"max-unavailable"* ]]
}

@test "empty value gets default of 1" {
  export KUBERNETES_PODDISRUPTIONBUDGET_VALUE=""

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"maxUnavailable: 1"* ]]
}

# =============================================================================
# Token styles
# =============================================================================

@test "respects PascalCase token name style" {
  export TOKEN_NAME_STYLE="PascalCase"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${ProjectName}'* ]]
  [[ "$manifest" == *'${Environment}'* ]]
}

@test "respects lower-kebab token name style" {
  export TOKEN_NAME_STYLE="lower-kebab"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${project-name}'* ]]
  [[ "$manifest" == *'${environment}'* ]]
}

@test "respects mustache substitution style" {
  export TOKEN_DELIMITER_STYLE="mustache"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'{{ ProjectName }}'* ]]
  [[ "$manifest" == *'{{ Environment }}'* ]]
}

@test "fails with unknown token name style" {
  export TOKEN_NAME_STYLE="unknown"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 2 ]
}

@test "fails with unknown substitution token style" {
  export TOKEN_DELIMITER_STYLE="unknown"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 3 ]
}

# =============================================================================
# Output paths
# =============================================================================

@test "creates output directory if missing" {
  export OUTPUT_SUB_PATH="${OUTPUT_SUB_PATH}/fresh-subdir"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget.yaml" ]
}

@test "respects custom OUTPUT_SUB_PATH" {
  export OUTPUT_SUB_PATH=$(create_test_dir "pdb-custom")

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget.yaml" ]
}

# =============================================================================
# Additional labels and annotations
# =============================================================================

@test "adds global additional labels" {
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=platform,cost-center=123"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"team: platform"* ]]
  [[ "$manifest" == *"cost-center: 123"* ]]
}

@test "adds pdb-specific additional labels" {
  export KUBERNETES_PODDISRUPTIONBUDGET_ADDITIONAL_LABELS="pdb-label=value"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"pdb-label: value"* ]]
}

@test "pdb labels override global labels" {
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=platform"
  export KUBERNETES_PODDISRUPTIONBUDGET_ADDITIONAL_LABELS="team=override"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"team: override"* ]]
  [[ "$manifest" != *"team: platform"* ]]
}

@test "adds global additional annotations" {
  export KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS="example.com/note=test"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"example.com/note: test"* ]]
}

@test "adds pdb-specific additional annotations" {
  export KUBERNETES_PODDISRUPTIONBUDGET_ADDITIONAL_ANNOTATIONS="example.com/pdb-note=pdb-test"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"example.com/pdb-note: pdb-test"* ]]
}

# =============================================================================
# Name suffix
# =============================================================================

@test "suffix affects metadata.name" {
  export KUBERNETES_PODDISRUPTIONBUDGET_NAME_SUFFIX="backend"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest_with_suffix "backend")
  [[ "$manifest" == *'name: ${ProjectName}-backend'* ]]
}

@test "suffix affects output filename" {
  export KUBERNETES_PODDISRUPTIONBUDGET_NAME_SUFFIX="backend"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget-backend.yaml" ]
}

@test "no suffix uses default filename" {
  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/poddisruptionbudget.yaml" ]
}

# =============================================================================
# Combined sub-path
# =============================================================================

@test "combined sub-path creates subdirectory in combined/" {
  export KUBERNETES_PODDISRUPTIONBUDGET_COMBINED_SUB_PATH="apps/backend"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/apps/backend/poddisruptionbudget.yaml" ]
}

@test "combined sub-path affects metadata.name" {
  export KUBERNETES_PODDISRUPTIONBUDGET_COMBINED_SUB_PATH="apps-backend"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest_in_subpath "apps-backend")
  [[ "$manifest" == *'name: ${ProjectName}-apps-backend'* ]]
}

@test "combined sub-path with suffix: name is ProjectName-combined-suffix" {
  export KUBERNETES_PODDISRUPTIONBUDGET_COMBINED_SUB_PATH="apps"
  export KUBERNETES_PODDISRUPTIONBUDGET_NAME_SUFFIX="backend"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/apps/poddisruptionbudget-backend.yaml" ]
  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/apps/poddisruptionbudget-backend.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-apps-backend'* ]]
}

@test "nested combined sub-path replaces slashes with hyphens in name" {
  export KUBERNETES_PODDISRUPTIONBUDGET_COMBINED_SUB_PATH="omg/wtf"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/poddisruptionbudget.yaml" ]
  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/poddisruptionbudget.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg-wtf'* ]]
}

@test "combined sub-path validation rejects uppercase" {
  export KUBERNETES_PODDISRUPTIONBUDGET_COMBINED_SUB_PATH="Apps"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 5 ]
}

@test "combined sub-path validation rejects leading slash" {
  export KUBERNETES_PODDISRUPTIONBUDGET_COMBINED_SUB_PATH="/apps"

  run "$GENERATORS_DIR/generate-kubernetes-poddisruptionbudget"
  [ "$status" -eq 6 ]
}
