#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Tests for generate-kubernetes-configmap

load helpers

setup() {
  export KUBERNETES_CONFIGMAP_SUB_PATH=$(mktemp -d)
  export OUTPUT_SUB_PATH=$(mktemp -d)
  export PROJECT_NAME="my-project"
  export TOKEN_NAME_STYLE="PascalCase"
  export TOKEN_DELIMITER_STYLE="shell"
  export KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION="true"
}

teardown() {
  rm -rf "$KUBERNETES_CONFIGMAP_SUB_PATH"
  rm -rf "$OUTPUT_SUB_PATH"
}

# Helper to create a config file
create_config_file() {
  local filename="$1"
  local content="$2"
  mkdir -p "$(dirname "$KUBERNETES_CONFIGMAP_SUB_PATH/$filename")"
  printf '%s' "$content" > "$KUBERNETES_CONFIGMAP_SUB_PATH/$filename"
}

# Helper to create a config file in a suffixed directory
create_config_file_with_suffix() {
  local suffix="$1"
  local filename="$2"
  local content="$3"
  local suffixed_path="${KUBERNETES_CONFIGMAP_SUB_PATH}-${suffix}"
  mkdir -p "$(dirname "$suffixed_path/$filename")"
  printf '%s' "$content" > "$suffixed_path/$filename"
}

# Helper to read generated manifest
read_manifest() {
  cat "$OUTPUT_SUB_PATH/manifests/combined/configmap.yaml"
}

# =============================================================================
# Basic functionality
# =============================================================================

@test "generates ConfigMap with single file" {
  create_config_file "app.properties" "key=value"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"apiVersion: v1"* ]]
  [[ "$manifest" == *"kind: ConfigMap"* ]]
  [[ "$manifest" == *"app.properties:"* ]]
  [[ "$manifest" == *"key=value"* ]]
}

@test "generates ConfigMap with multiple files" {
  create_config_file "app.properties" "key1=value1"
  create_config_file "settings.json" '{"debug": false}'

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"app.properties:"* ]]
  [[ "$manifest" == *"settings.json:"* ]]
}

@test "includes standard labels" {
  create_config_file "app.properties" "key=value"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"labels:"* ]]
  [[ "$manifest" == *'app: ${ProjectName}'* ]]
  [[ "$manifest" == *'app.kubernetes.io/name: ${ProjectName}'* ]]
  [[ "$manifest" == *'app.kubernetes.io/version: ${Version}'* ]]
  [[ "$manifest" == *"app.kubernetes.io/managed-by: kaptain"* ]]
}

@test "includes kaptain annotations" {
  create_config_file "app.properties" "key=value"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"annotations:"* ]]
  [[ "$manifest" == *'kaptain/project-name: ${ProjectName}'* ]]
  [[ "$manifest" == *'kaptain/version: ${Version}'* ]]
  [[ "$manifest" == *"kaptain/build-timestamp:"* ]]
  [[ "$manifest" == *'kaptain/generated-by: "Generated by Kaptain generate-kubernetes-configmap"'* ]]
}

@test "uses checksum injection by default" {
  create_config_file "app.properties" "key=value"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'name: ${ProjectName}-configmap-checksum'* ]]
}

@test "uses plain name when checksum injection disabled" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION="false"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'name: ${ProjectName}'* ]]
  [[ "$manifest" != *"configmap-checksum"* ]]
}

@test "uses Environment token for namespace" {
  create_config_file "app.properties" "key=value"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'namespace: ${Environment}'* ]]
}

# =============================================================================
# Token style integration
# =============================================================================

@test "respects PascalCase token name style" {
  create_config_file "app.properties" "key=value"
  export TOKEN_NAME_STYLE="PascalCase"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${ProjectName}'* ]]
  [[ "$manifest" == *'${Environment}'* ]]
}

@test "respects lower-kebab token name style" {
  create_config_file "app.properties" "key=value"
  export TOKEN_NAME_STYLE="lower-kebab"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${project-name}'* ]]
  [[ "$manifest" == *'${environment}'* ]]
}

@test "respects UPPER_SNAKE token name style" {
  create_config_file "app.properties" "key=value"
  export TOKEN_NAME_STYLE="UPPER_SNAKE"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${PROJECT_NAME}'* ]]
  [[ "$manifest" == *'${ENVIRONMENT}'* ]]
}

@test "respects mustache substitution style" {
  create_config_file "app.properties" "key=value"
  export TOKEN_DELIMITER_STYLE="mustache"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'{{ ProjectName }}'* ]]
  [[ "$manifest" == *'{{ Environment }}'* ]]
}

@test "respects helm substitution style" {
  create_config_file "app.properties" "key=value"
  export TOKEN_DELIMITER_STYLE="helm"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'{{ .Values.ProjectName }}'* ]]
  [[ "$manifest" == *'{{ .Values.Environment }}'* ]]
}

# =============================================================================
# Skip behavior
# =============================================================================

@test "exits 0 when configmap directory does not exist" {
  rm -rf "$KUBERNETES_CONFIGMAP_SUB_PATH"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]
  assert_output_contains "not found, skipping"

  # No manifest generated
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/configmap.yaml" ]
}

@test "fails when configmap directory has only dotfiles" {
  # Directory exists but has only dotfiles (like .gitkeep)
  touch "$KUBERNETES_CONFIGMAP_SUB_PATH/.gitkeep"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 7 ]
  assert_output_contains "No files found (excluding dotfiles)"
}

# =============================================================================
# Content handling
# =============================================================================

@test "preserves multiline content" {
  create_config_file "app.properties" "line1=value1
line2=value2
line3=value3"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"line1=value1"* ]]
  [[ "$manifest" == *"line2=value2"* ]]
  [[ "$manifest" == *"line3=value3"* ]]
}

@test "handles content with special characters" {
  create_config_file "app.properties" 'url=http://example.com?foo=bar&baz=qux'

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'url=http://example.com?foo=bar&baz=qux'* ]]
}

@test "handles content with token-like strings" {
  create_config_file "app.properties" 'template=${SomeVar}'

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  # Token-like strings in content should be preserved as-is
  [[ "$manifest" == *'template=${SomeVar}'* ]]
}

# =============================================================================
# Error cases
# =============================================================================

@test "fails with unknown token name style" {
  create_config_file "app.properties" "key=value"
  export TOKEN_NAME_STYLE="UnknownStyle"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 2 ]
  assert_output_contains "Unknown token name style"
}

@test "fails with unknown substitution token style" {
  create_config_file "app.properties" "key=value"
  export TOKEN_DELIMITER_STYLE="unknown"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 3 ]
  assert_output_contains "Unknown substitution"
}

@test "fails with invalid configmap-name-checksum-injection value" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION="maybe"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 4 ]
  assert_output_contains "KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION must be 'true' or 'false'"
}

# =============================================================================
# Output location
# =============================================================================

@test "creates output directory if missing" {
  rm -rf "$OUTPUT_SUB_PATH"
  create_config_file "app.properties" "key=value"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/configmap.yaml" ]
}

@test "respects custom OUTPUT_SUB_PATH" {
  local custom_output=$(mktemp -d)
  export OUTPUT_SUB_PATH="$custom_output"
  create_config_file "app.properties" "key=value"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  [ -f "$custom_output/manifests/combined/configmap.yaml" ]
  rm -rf "$custom_output"
}

# =============================================================================
# Additional labels and annotations
# =============================================================================

@test "adds global additional labels" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=platform,cost-center=123"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"team: platform"* ]]
  [[ "$manifest" == *"cost-center: 123"* ]]
}

@test "adds global additional annotations" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS="custom/note=hello"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"custom/note: hello"* ]]
}

@test "adds configmap-specific additional labels" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_ADDITIONAL_LABELS="config-type=app"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"config-type: app"* ]]
}

@test "adds configmap-specific additional annotations" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_ADDITIONAL_ANNOTATIONS="configmap/source=generated"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"configmap/source: generated"* ]]
}

@test "configmap labels override global labels" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=global-team"
  export KUBERNETES_CONFIGMAP_ADDITIONAL_LABELS="team=configmap-team"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"team: configmap-team"* ]]
  [[ "$manifest" != *"team: global-team"* ]]
}

@test "configmap annotations override global annotations" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS="custom/note=global"
  export KUBERNETES_CONFIGMAP_ADDITIONAL_ANNOTATIONS="custom/note=configmap"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"custom/note: configmap"* ]]
  [[ "$manifest" != *"custom/note: global"* ]]
}

@test "additional labels can override builtin labels" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_ADDITIONAL_LABELS="app.kubernetes.io/managed-by=helm"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"app.kubernetes.io/managed-by: helm"* ]]
  [[ "$manifest" != *"app.kubernetes.io/managed-by: kaptain"* ]]
}

@test "additional annotations can override builtin annotations" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_ADDITIONAL_ANNOTATIONS='kaptain/generated-by="custom generator"'

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'kaptain/generated-by: "custom generator"'* ]]
}

# =============================================================================
# Name suffix
# =============================================================================

@test "suffix affects default sub-path" {
  # Create directory with suffix
  local suffix_dir="$KUBERNETES_CONFIGMAP_SUB_PATH-nginx"
  mkdir -p "$suffix_dir"
  printf 'key=value' > "$suffix_dir/app.properties"

  # Unset sub-path so default is used, set suffix
  unset KUBERNETES_CONFIGMAP_SUB_PATH
  export KUBERNETES_CONFIGMAP_NAME_SUFFIX="nginx"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  rm -rf "$suffix_dir"
}

@test "suffix affects metadata.name with checksum" {
  create_config_file_with_suffix "nginx" "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_NAME_SUFFIX="nginx"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/configmap-nginx.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-nginx-configmap-checksum'* ]]
}

@test "suffix affects metadata.name without checksum" {
  create_config_file_with_suffix "nginx" "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_NAME_SUFFIX="nginx"
  export KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION="false"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/configmap-nginx.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-nginx'* ]]
  [[ "$manifest" != *"configmap-checksum"* ]]
}

@test "suffix affects output filename" {
  create_config_file_with_suffix "nginx" "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_NAME_SUFFIX="nginx"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/configmap-nginx.yaml" ]
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/configmap.yaml" ]
}

@test "no suffix uses default filename" {
  create_config_file "app.properties" "key=value"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/configmap.yaml" ]
}

@test "suffix with custom sub-path still affects name and filename" {
  # User overrides sub-path but provides suffix - suffix appends to path
  create_config_file_with_suffix "custom" "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_NAME_SUFFIX="custom"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  # Filename should include suffix
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/configmap-custom.yaml" ]

  # Name should include suffix
  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/configmap-custom.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-custom-configmap-checksum'* ]]
}

@test "suffix appends to custom sub-path for source directory" {
  # Create a custom base path and the suffixed version
  local custom_base=$(mktemp -d)
  local custom_suffixed="${custom_base}-nginx"
  mkdir -p "$custom_suffixed"
  printf 'nginx=config' > "$custom_suffixed/nginx.conf"

  # Set custom base path and suffix - should look in custom_base-nginx
  export KUBERNETES_CONFIGMAP_SUB_PATH="$custom_base"
  export KUBERNETES_CONFIGMAP_NAME_SUFFIX="nginx"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  # Should have read from the suffixed directory
  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/configmap-nginx.yaml")
  [[ "$manifest" == *"nginx.conf:"* ]]
  [[ "$manifest" == *"nginx=config"* ]]

  rm -rf "$custom_base" "$custom_suffixed"
}

@test "custom sub-path without suffix uses path as-is" {
  # Create a custom path
  local custom_path=$(mktemp -d)
  printf 'custom=value' > "$custom_path/custom.properties"

  # Set custom path, no suffix
  export KUBERNETES_CONFIGMAP_SUB_PATH="$custom_path"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/configmap.yaml")
  [[ "$manifest" == *"custom.properties:"* ]]
  [[ "$manifest" == *"custom=value"* ]]

  rm -rf "$custom_path"
}

# =============================================================================
# Combined sub-path
# =============================================================================

@test "combined sub-path creates subdirectory in combined/" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/omg/configmap.yaml" ]
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/configmap.yaml" ]
}

@test "combined sub-path affects metadata.name with checksum" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg/configmap.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg-configmap-checksum'* ]]
}

@test "combined sub-path affects metadata.name without checksum" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg"
  export KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION="false"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg/configmap.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg'* ]]
  [[ "$manifest" != *"configmap-checksum"* ]]
}

@test "combined sub-path with suffix: name is ProjectName-combined-suffix-checksum" {
  create_config_file_with_suffix "wtf" "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg"
  export KUBERNETES_CONFIGMAP_NAME_SUFFIX="wtf"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  # File goes in combined sub-path directory with suffix in filename
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/omg/configmap-wtf.yaml" ]

  # Name includes both combined and suffix
  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg/configmap-wtf.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg-wtf-configmap-checksum'* ]]
}

@test "combined sub-path with suffix, no checksum: name is ProjectName-combined-suffix" {
  create_config_file_with_suffix "wtf" "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg"
  export KUBERNETES_CONFIGMAP_NAME_SUFFIX="wtf"
  export KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION="false"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg/configmap-wtf.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg-wtf'* ]]
  [[ "$manifest" != *"configmap-checksum"* ]]
}

@test "no combined sub-path uses root combined directory" {
  create_config_file "app.properties" "key=value"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/configmap.yaml" ]
}

@test "nested combined sub-path creates nested directory" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg/wtf"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/configmap.yaml" ]
}

@test "nested combined sub-path replaces slashes with hyphens in name" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg/wtf"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/configmap.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg-wtf-configmap-checksum'* ]]
}

@test "nested combined sub-path with suffix: name is ProjectName-omg-wtf-suffix-checksum" {
  create_config_file_with_suffix "lol" "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg/wtf"
  export KUBERNETES_CONFIGMAP_NAME_SUFFIX="lol"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/configmap-lol.yaml" ]

  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/configmap-lol.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg-wtf-lol-configmap-checksum'* ]]
}

@test "combined sub-path validation rejects uppercase" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="OMG"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 5 ]
  assert_output_contains "must contain only lowercase"
}

@test "combined sub-path validation rejects underscores" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg_wtf"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 5 ]
  assert_output_contains "must contain only lowercase"
}

@test "combined sub-path validation rejects special characters" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg@wtf"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 5 ]
  assert_output_contains "must contain only lowercase"
}

@test "combined sub-path validation rejects leading slash" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="/omg"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 6 ]
  assert_output_contains "must not start or end with a slash"
}

@test "combined sub-path validation rejects trailing slash" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg/"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 6 ]
  assert_output_contains "must not start or end with a slash"
}

@test "combined sub-path validation allows lowercase letters digits hyphens slashes" {
  create_config_file "app.properties" "key=value"
  export KUBERNETES_CONFIGMAP_COMBINED_SUB_PATH="omg-1/wtf-2"

  run "$GENERATORS_DIR/generate-kubernetes-configmap"
  [ "$status" -eq 0 ]

  [ -f "$OUTPUT_SUB_PATH/manifests/combined/omg-1/wtf-2/configmap.yaml" ]

  manifest=$(cat "$OUTPUT_SUB_PATH/manifests/combined/omg-1/wtf-2/configmap.yaml")
  [[ "$manifest" == *'name: ${ProjectName}-omg-1-wtf-2-configmap-checksum'* ]]
}
