#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Tests for generate-kubernetes-namespace

bats_require_minimum_version 1.5.0

load helpers

setup() {
  export OUTPUT_SUB_PATH=$(create_test_dir "gen-namespace")
  export PROJECT_NAME="my-project"
  export TOKEN_NAME_STYLE="PascalCase"
  export TOKEN_DELIMITER_STYLE="shell"
  export KUBERNETES_NAMESPACE_GENERATION_ENABLED="true"
  export KUBERNETES_NAMESPACE_NAME='${ProjectName}'
  export REPOSITORY_OWNER="kube-kaptain"
  export SOURCE_REPO="kube-kaptain/test-project"
  export IMAGE_URI="ghcr.io/kube-kaptain/test-project:1.0.0"
}

teardown() {
  dump_bats_result
  :
}

# Helper to read generated manifest
read_manifest() {
  cat "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml"
}

read_manifest_in_subpath() {
  local subpath="$1"
  cat "$OUTPUT_SUB_PATH/manifests/combined/${subpath}/namespace.yaml"
}

# =============================================================================
# Generation enabled/disabled
# =============================================================================

@test "skips generation when not enabled" {
  export KUBERNETES_NAMESPACE_GENERATION_ENABLED="false"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not enabled"* ]] || return 1
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml" ]
}

@test "skips generation when enabled not set" {
  unset KUBERNETES_NAMESPACE_GENERATION_ENABLED

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not enabled"* ]] || return 1
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml" ]
}

@test "generates when explicitly enabled" {
  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml" ]
}

# =============================================================================
# Basic functionality
# =============================================================================

@test "generates valid Namespace structure" {
  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"apiVersion: v1"* ]] || return 1
  [[ "$manifest" == *"kind: Namespace"* ]] || return 1
  [[ "$manifest" == *"metadata:"* ]] || return 1
  [[ "$manifest" == *'  name: ${ProjectName}'* ]] || return 1
}

@test "is cluster-scoped and carries no spec" {
  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  [ "$(yq '.metadata.name' "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml")" = '${ProjectName}' ]
  [ "$(yq '.metadata | has("namespace")' "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml")" = "false" ]
  [ "$(yq 'has("spec")' "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml")" = "false" ]
}

@test "includes standard labels" {
  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"labels:"* ]] || return 1
  [[ "$manifest" == *'app: "${ProjectName}"'* ]] || return 1
  [[ "$manifest" == *'app.kubernetes.io/name: "${ProjectName}"'* ]] || return 1
  [[ "$manifest" == *'app.kubernetes.io/version: "${Version}"'* ]] || return 1
  [[ "$manifest" == *'app.kubernetes.io/managed-by: "Kaptain"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/version: "${Version}"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/project-name: "${ProjectName}"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/owner: "kube-kaptain"'* ]] || return 1
}

@test "includes kaptain annotations" {
  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *"annotations:"* ]] || return 1
  [[ "$manifest" == *'kaptain.org/project-name: "${ProjectName}"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/version: "${Version}"'* ]] || return 1
  [[ "$manifest" == *"kaptain.org/build-timestamp:"* ]] || return 1
  [[ "$manifest" == *'kaptain.org/generated-by: "Generated by Kaptain generate-kubernetes-namespace"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/built-by: "test"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/source-repository: "kube-kaptain/test-project"'* ]] || return 1
  [[ "$manifest" == *'kaptain.org/image-uri: "ghcr.io/kube-kaptain/test-project:1.0.0"'* ]] || return 1
}

# =============================================================================
# Token styles
# =============================================================================

@test "respects PascalCase token name style" {
  export TOKEN_NAME_STYLE="PascalCase"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${ProjectName}'* ]] || return 1
  [[ "$manifest" == *'${Environment}'* ]] || return 1
}

@test "respects lower-kebab token name style" {
  export TOKEN_NAME_STYLE="lower-kebab"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'${project-name}'* ]] || return 1
  [[ "$manifest" == *'${environment}'* ]] || return 1
}

@test "respects mustache substitution style" {
  export TOKEN_DELIMITER_STYLE="mustache"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'{{ ProjectName }}'* ]] || return 1
  [[ "$manifest" == *'{{ Environment }}'* ]] || return 1
}

@test "fails with unknown token name style" {
  export TOKEN_NAME_STYLE="unknown"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 2 ]
}

@test "fails with unknown substitution token style" {
  export TOKEN_DELIMITER_STYLE="unknown"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 3 ]
}

# =============================================================================
# Output paths
# =============================================================================

@test "creates output directory if missing" {
  # Use a fresh subdirectory that doesn't exist yet
  export OUTPUT_SUB_PATH="${OUTPUT_SUB_PATH}/fresh-subdir"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml" ]
}

@test "respects custom OUTPUT_SUB_PATH" {
  export OUTPUT_SUB_PATH=$(create_test_dir "namespace-custom")

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml" ]
}

# =============================================================================
# Additional labels and annotations
# =============================================================================

@test "adds global additional labels" {
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=platform,cost-center=123"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'team: "platform"'* ]] || return 1
  [[ "$manifest" == *'cost-center: "123"'* ]] || return 1
}

@test "adds namespace-specific additional labels" {
  export KUBERNETES_NAMESPACE_ADDITIONAL_LABELS="ns-label=value"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'ns-label: "value"'* ]] || return 1
}

@test "namespace labels override global labels" {
  export KUBERNETES_GLOBAL_ADDITIONAL_LABELS="team=platform"
  export KUBERNETES_NAMESPACE_ADDITIONAL_LABELS="team=override"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'team: "override"'* ]] || return 1
  [[ "$manifest" != *'team: "platform"'* ]] || return 1
}

@test "adds global additional annotations" {
  export KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS="example.com/note=test"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'example.com/note: "test"'* ]] || return 1
}

@test "adds namespace-specific additional annotations" {
  export KUBERNETES_NAMESPACE_ADDITIONAL_ANNOTATIONS="iam.gke.io/gcp-service-account=my-sa@project.iam.gnamespace.com"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]

  manifest=$(read_manifest)
  [[ "$manifest" == *'iam.gke.io/gcp-service-account: "my-sa@project.iam.gnamespace.com"'* ]] || return 1
}

# =============================================================================
# Name
# =============================================================================

@test "fails without a name, as there is no default" {
  unset KUBERNETES_NAMESPACE_NAME

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 1 ]
  [[ "$output" == *"KUBERNETES_NAMESPACE_NAME is required"* ]] || return 1
  [ ! -f "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml" ]
}

@test "name can be any token the consumer supplies" {
  export KUBERNETES_NAMESPACE_NAME='${Environment}'

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [ "$(yq '.metadata.name' "$OUTPUT_SUB_PATH/manifests/combined/namespace.yaml")" = '${Environment}' ]
}

@test "name is a literal used exactly as given, even with a combined sub-path" {
  export KUBERNETES_NAMESPACE_NAME="shared-tools"
  export KUBERNETES_NAMESPACE_COMBINED_SUB_PATH="extra"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [ "$(yq '.metadata.name' "$OUTPUT_SUB_PATH/manifests/combined/extra/namespace.yaml")" = "shared-tools" ]
}

# =============================================================================
# Combined sub-path
# =============================================================================

@test "combined sub-path creates subdirectory in combined/" {
  export KUBERNETES_NAMESPACE_COMBINED_SUB_PATH="apps/backend"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [ -f "$OUTPUT_SUB_PATH/manifests/combined/apps/backend/namespace.yaml" ]
}

@test "combined sub-path does not affect metadata.name" {
  export KUBERNETES_NAMESPACE_COMBINED_SUB_PATH="apps-backend"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [ "$(yq '.metadata.name' "$OUTPUT_SUB_PATH/manifests/combined/apps-backend/namespace.yaml")" = '${ProjectName}' ]
}

@test "nested combined sub-path nests the file and leaves the name alone" {
  export KUBERNETES_NAMESPACE_COMBINED_SUB_PATH="omg/wtf"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 0 ]
  [ "$(yq '.metadata.name' "$OUTPUT_SUB_PATH/manifests/combined/omg/wtf/namespace.yaml")" = '${ProjectName}' ]
}

@test "combined sub-path validation rejects uppercase" {
  export KUBERNETES_NAMESPACE_COMBINED_SUB_PATH="Apps"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 5 ]
}

@test "combined sub-path validation rejects leading slash" {
  export KUBERNETES_NAMESPACE_COMBINED_SUB_PATH="/apps"

  run "$GENERATORS_DIR/generate-kubernetes-namespace"
  [ "$status" -eq 6 ]
}
