#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Tests for kubernetes-manifests-repo-provider-docker-package
# This script builds a Docker image containing the manifests zip.

load helpers

setup() {
  setup_mock_docker
  export IMAGE_BUILD_COMMAND="docker"
  local base_dir=$(create_test_dir "k8s-repo-docker-pkg")
  export GITHUB_OUTPUT="$base_dir/output"
  # Create a test zip in a directory
  export TEST_ZIP_DIR="$base_dir/zip"
  mkdir -p "$TEST_ZIP_DIR"
  export TEST_ZIP_NAME="test-manifests.zip"
  echo "test content" > "$TEST_ZIP_DIR/$TEST_ZIP_NAME"
  # Create output directory
  export OUTPUT_SUB_PATH="$base_dir/target"
  export DOCKER_PUSH_IMAGE_LIST_FILE="${OUTPUT_SUB_PATH}/docker-push-all/image-uris"
  mkdir -p "$OUTPUT_SUB_PATH"
  mkdir -p "$(dirname "$DOCKER_PUSH_IMAGE_LIST_FILE")"
}

teardown() {
  :
}

# Required env vars for most tests (using REPO_PROVIDER_* API)
set_required_env() {
  export MANIFESTS_ZIP_SUB_PATH="$TEST_ZIP_DIR"
  export MANIFESTS_ZIP_FILE_NAME="$TEST_ZIP_NAME"
  export REPO_PROVIDER_URL="ghcr.io"
  export REPO_PROVIDER_NAME="test/my-repo"
  export REPO_PROVIDER_VERSION="1.0.0-manifests"
  export VERSION="1.0.0"
  export PROJECT_NAME="my-repo"
}

@test "assembles target URI without namespace" {
  set_required_env

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]
  assert_var_equals "MANIFESTS_URI" "ghcr.io/test/my-repo:1.0.0-manifests"
}

@test "assembles target URI with namespace" {
  set_required_env
  export REPO_PROVIDER_NAMESPACE="kube-kaptain"

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]
  assert_var_equals "MANIFESTS_URI" "ghcr.io/kube-kaptain/test/my-repo:1.0.0-manifests"
}

@test "builds both architectures via docker-package-multi-arch" {
  set_required_env

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]
  assert_docker_called "build --platform linux/amd64 -t ghcr.io/test/my-repo:1.0.0-manifests-linux-amd64"
  assert_docker_called "build --platform linux/arm64 -t ghcr.io/test/my-repo:1.0.0-manifests-linux-arm64"
}

@test "creates publish directory with zip" {
  set_required_env

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]
  # Verify publish directory was created with zip
  [ -d "$OUTPUT_SUB_PATH/publish/docker" ]
  [ -f "$OUTPUT_SUB_PATH/publish/docker/$TEST_ZIP_NAME" ]
  # Dockerfile generated by docker-package-multi-arch in its build dir
  [ -f "$OUTPUT_SUB_PATH/docker-package-multi-arch/docker/Dockerfile" ]
}

@test "registers arch-specific URIs for docker-push-all" {
  set_required_env

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]

  local push_file="$DOCKER_PUSH_IMAGE_LIST_FILE"
  [ -f "$push_file" ]
  run cat "$push_file"
  [[ "$output" == *"ghcr.io/test/my-repo:1.0.0-manifests-linux-amd64"* ]]
  [[ "$output" == *"ghcr.io/test/my-repo:1.0.0-manifests-linux-arm64"* ]]
}

@test "registers base URI in manifest-uris" {
  set_required_env

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]

  local manifest_file="$OUTPUT_SUB_PATH/docker-push-all/manifest-uris"
  [ -f "$manifest_file" ]
  run cat "$manifest_file"
  [[ "$output" == *"ghcr.io/test/my-repo:1.0.0-manifests"* ]]
}

@test "does not push (package only)" {
  set_required_env

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]
  assert_docker_not_called "push"
}

@test "fails when MANIFESTS_ZIP_SUB_PATH missing" {
  export REPO_PROVIDER_URL="ghcr.io"
  export REPO_PROVIDER_NAME="test/my-repo"
  export REPO_PROVIDER_VERSION="1.0.0-manifests"
  unset MANIFESTS_ZIP_SUB_PATH

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -ne 0 ]
  assert_output_contains "MANIFESTS_ZIP_SUB_PATH"
}

@test "fails when zip file not found" {
  set_required_env
  export MANIFESTS_ZIP_SUB_PATH="/nonexistent"
  export MANIFESTS_ZIP_FILE_NAME="file.zip"

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -ne 0 ]
  assert_output_contains "Manifests zip not found"
}

@test "fails when REPO_PROVIDER_NAME missing" {
  export MANIFESTS_ZIP_SUB_PATH="$TEST_ZIP_DIR"
  export MANIFESTS_ZIP_FILE_NAME="$TEST_ZIP_NAME"
  export REPO_PROVIDER_URL="ghcr.io"
  export REPO_PROVIDER_VERSION="1.0.0-manifests"

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -ne 0 ]
  assert_output_contains "REPO_PROVIDER_NAME"
}

@test "fails when REPO_PROVIDER_VERSION missing" {
  export MANIFESTS_ZIP_SUB_PATH="$TEST_ZIP_DIR"
  export MANIFESTS_ZIP_FILE_NAME="$TEST_ZIP_NAME"
  export REPO_PROVIDER_URL="ghcr.io"
  export REPO_PROVIDER_NAME="test/my-repo"

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -ne 0 ]
  assert_output_contains "REPO_PROVIDER_VERSION"
}

@test "fails when REPO_PROVIDER_URL missing" {
  export MANIFESTS_ZIP_SUB_PATH="$TEST_ZIP_DIR"
  export MANIFESTS_ZIP_FILE_NAME="$TEST_ZIP_NAME"
  export REPO_PROVIDER_NAME="test/my-repo"
  export REPO_PROVIDER_VERSION="1.0.0-manifests"

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -ne 0 ]
  assert_output_contains "REPO_PROVIDER_URL"
}

@test "always checks for existing image" {
  set_required_env

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]
  assert_docker_called "manifest inspect"
}

@test "fails when image already exists" {
  set_required_env
  # Make docker manifest inspect succeed (image exists)
  echo '#!/bin/bash
if [[ "$1" == "manifest" && "$2" == "inspect" ]]; then
  exit 0
fi
echo "$*" >> "$MOCK_DOCKER_CALLS"
exit 0' > "$MOCK_BIN_DIR/docker"
  chmod +x "$MOCK_BIN_DIR/docker"

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -ne 0 ]
  assert_output_contains "already exists"
}

@test "uses scratch as default base image" {
  set_required_env

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]
  # The script should output info about using scratch as base
  assert_output_contains "scratch"
}

@test "allows overriding base image" {
  set_required_env
  export MANIFESTS_PACKAGING_BASE_IMAGE="custom.registry.io/my-org/custom-pause:1.0.0"

  run "$REPO_PROVIDERS_DIR/kubernetes-manifests-repo-provider-docker-package"
  [ "$status" -eq 0 ]
  assert_output_contains "custom.registry.io/my-org/custom-pause:1.0.0"
}
