#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Tests for lib/sensitive-resource-signoff.bash.

load helpers

setup() {
  TEST_DIR=$(create_test_dir "sensitive-resource-signoff")
  # shellcheck source=src/scripts/lib/sensitive-resource-signoff.bash
  source "${LIB_DIR}/sensitive-resource-signoff.bash"

  KINDS_FILE="${LIB_DIR}/../../data/signoff-kinds/default-1.1.txt"

  MANIFESTS_DIR="${TEST_DIR}/manifests"
  SIGNOFFS_DIR="${TEST_DIR}/signoffs"
  mkdir -p "${MANIFESTS_DIR}/run-foo/some-app/src/kubernetes" \
           "${SIGNOFFS_DIR}/some-app/src/kubernetes"
}

# 'run-foo' is the env root, stripped from the signoff path.
write_ingress() {
  cat > "${MANIFESTS_DIR}/run-foo/some-app/src/kubernetes/ingress.yaml" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules:
  - host: example.com
EOF
}

write_signoff() {
  local checksum="$1"
  cat > "${SIGNOFFS_DIR}/some-app/src/kubernetes/ingress.yaml" << EOF
sourcePath: some-app/src/kubernetes/ingress.yaml
checksum:   sha256:${checksum}
EOF
}

# =============================================================================
# signoff_canonical_hash - strip expression
# =============================================================================

@test "hash: our provenance annotations do not affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    kaptain.org/build-timestamp: "2026-09-25T20:00:00Z"
    kaptain.org/built-by: github-actions
    kaptain.org/generated-by: Generated by Kaptain generate-kubernetes-ingress
    kaptain.org/git-sha: abc123
    kaptain.org/helm-upstream-chart: ingress-nginx-4.11.0
    kaptain.org/image-uri: ghcr.io/org/app:1.2.3
    kaptain.org/source-repository: https://github.com/org/app
spec:
  rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: keel.sh/ and keelson.io/ annotations do not affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    keel.sh/policy: force
    keelson.io/track: latest
spec:
  rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: kaptain.org/version and app.kubernetes.io/version labels do not affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  labels:
    kaptain.org/version: "1.0.0"
    app.kubernetes.io/version: "1.0.0"
spec:
  rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: spec content changes do affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules:
  - host: a.example.com
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules:
  - host: b.example.com
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" != "${h2}" ]
}

@test "hash: pod-template rollout annotations on workloads do not affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d
spec:
  template:
    metadata:
      annotations: {}
    spec:
      containers: [{ name: d, image: i }]
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d
spec:
  template:
    metadata:
      annotations:
        kaptain.org/build-timestamp: "2026-09-25T20:00:00Z"
        keel.sh/policy: force
    spec:
      containers: [{ name: d, image: i }]
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: an unlisted kaptain.org/ annotation does affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    kaptain.org/some-future-behaviour: "on"
spec:
  rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" != "${h2}" ]
}

@test "hash: absent annotations and annotations holding only stripped keys hash the same" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r
rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r
  annotations:
    kaptain.org/git-sha: abc123
rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: projection adds no pod template to kinds that have none" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r
rules: []
EOF
  [ "$(yq eval-all "${SIGNOFF_STRIP_EXPR}" -o=json "${f}" | jq -c 'has("spec")')" = "false" ]
}

@test "hash: missing file fails loudly" {
  run signoff_canonical_hash "${TEST_DIR}/does-not-exist.yaml"
  [ "${status}" -ne 0 ]
  assert_output_contains "Manifest file not found"
}

@test "hash: missing argument fails loudly" {
  run signoff_canonical_hash
  [ "${status}" -ne 0 ]
  assert_output_contains "requires exactly 1 argument"
}

# =============================================================================
# signoff_check_tree - end-to-end coverage / integrity
# =============================================================================

@test "tree: matching signoff passes" {
  write_ingress
  local h
  h=$(signoff_canonical_hash "${MANIFESTS_DIR}/run-foo/some-app/src/kubernetes/ingress.yaml")
  write_signoff "${h}"

  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  assert_output_contains "Signoff check passed"
}

@test "tree: missing signoff fails with expected-path hint" {
  write_ingress
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "Sensitive resource has no signoff"
  assert_output_contains "some-app/src/kubernetes/ingress.yaml"
  assert_output_contains "expected at:"
}

@test "tree: mismatched checksum fails with both expected and actual" {
  write_ingress
  write_signoff "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "Signoff checksum mismatch"
  assert_output_contains "expected: sha256:deadbeef"
  assert_output_contains "Re-review and update"
}

@test "tree: stale signoff (no matching resource) fails" {
  cat > "${SIGNOFFS_DIR}/some-app/src/kubernetes/ingress.yaml" << 'EOF'
sourcePath: some-app/src/kubernetes/ingress.yaml
checksum:   sha256:deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "Stale signoff"
  assert_output_contains "some-app/src/kubernetes/ingress.yaml"
}

@test "tree: malformed signoff (missing checksum field) fails" {
  write_ingress
  cat > "${SIGNOFFS_DIR}/some-app/src/kubernetes/ingress.yaml" << 'EOF'
sourcePath: some-app/src/kubernetes/ingress.yaml
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "missing 'checksum' field"
}

@test "tree: non-sensitive resources do not require a signoff" {
  cat > "${MANIFESTS_DIR}/run-foo/some-app/src/kubernetes/service.yaml" << 'EOF'
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  ports: []
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
}

@test "tree: custom kinds file replaces the default list entirely" {
  # Only Service is flagged: the custom list replaces the default.
  write_ingress
  cat > "${MANIFESTS_DIR}/run-foo/some-app/src/kubernetes/service.yaml" << 'EOF'
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  ports: []
EOF
  local custom="${TEST_DIR}/custom-kinds.txt"
  cat > "${custom}" << 'EOF'
# custom sensitive kinds - replaces the default list
Service
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${custom}"
  [ "${status}" -ne 0 ]
  assert_output_contains "Sensitive resource has no signoff"
  assert_output_contains "service.yaml"
  ! grep -q "ingress.yaml" <<< "${output}"
}

@test "tree: missing kinds file fails loudly" {
  write_ingress
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${TEST_DIR}/no-such-kinds.txt"
  [ "${status}" -ne 0 ]
  assert_output_contains "kinds file not found"
}

@test "tree: multi-doc YAML hashed as a single unit" {
  mkdir -p "${MANIFESTS_DIR}/run-foo/some-app/src/kubernetes"
  cat > "${MANIFESTS_DIR}/run-foo/some-app/src/kubernetes/rbac.yaml" << 'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: r
subjects: []
EOF
  local h
  h=$(signoff_canonical_hash "${MANIFESTS_DIR}/run-foo/some-app/src/kubernetes/rbac.yaml")
  [ -n "${h}" ]
  mkdir -p "${SIGNOFFS_DIR}/some-app/src/kubernetes"
  cat > "${SIGNOFFS_DIR}/some-app/src/kubernetes/rbac.yaml" << EOF
sourcePath: some-app/src/kubernetes/rbac.yaml
checksum:   sha256:${h}
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
}

@test "tree: missing manifests dir fails loudly" {
  run signoff_check_tree "${TEST_DIR}/does-not-exist" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "Manifests directory not found"
}

@test "tree: missing required arguments fails loudly" {
  run signoff_check_tree "${MANIFESTS_DIR}"
  [ "${status}" -ne 0 ]
  assert_output_contains "Usage: signoff_check_tree"
}

teardown() {
  dump_bats_result
}

# =============================================================================
# Skeletons
# =============================================================================

SKELETON="some-app/src/kubernetes/ingress.yaml"

# Git repo for the committed/uncommitted distinction; cd into it as the
# build runs from the repo.
init_signoff_repo() {
  git -C "${TEST_DIR}" init -q
  git -C "${TEST_DIR}" config user.name "Test Reviewer"
  git -C "${TEST_DIR}" config user.email "test@example.com"
  cd "${TEST_DIR}"
}

commit_signoffs() {
  git -C "${TEST_DIR}" add signoffs
  git -C "${TEST_DIR}" commit -q -m "signoffs"
}

@test "skeleton: a missing signoff gets a prefilled skeleton with the current checksum" {
  init_signoff_repo
  write_ingress
  local h
  h=$(signoff_canonical_hash "${MANIFESTS_DIR}/run-foo/${SKELETON}")
  SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  local s="${TEST_DIR}/skeletons/${SKELETON}"
  [ -f "${s}" ]
  [ "$(sed -n 1p "${s}")" = "${SIGNOFF_SKELETON_HEADER_1}" ]
  [ "$(sed -n 2p "${s}")" = "${SIGNOFF_SKELETON_HEADER_2_PREFIX}${SIGNOFFS_DIR}/${SKELETON}" ]
  [ "$(sed -n 3p "${s}")" = "${SIGNOFF_SKELETON_HEADER_3}" ]
  [ "$(yq '.sourcePath' "${s}")" = "${SKELETON}" ]
  [ "$(yq '.checksum' "${s}")" = "sha256:${h}" ]
  [ "$(yq '.reviewer' "${s}")" = "Test Reviewer" ]
  [[ "$(yq '.signoffTimestamp' "${s}")" =~ ${SIGNOFF_TIMESTAMP_PATTERN} ]] || return 1
  grep -qxF "${SIGNOFF_SKELETON_REFERENCE_PLACEHOLDER}" "${s}"
}

@test "skeleton: reviewer falls back to a placeholder when git has no name" {
  write_ingress
  GIT_DIR=/nonexistent GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1 \
    SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  grep -qxF "# reviewer: <who reviewed it>" "${TEST_DIR}/skeletons/${SKELETON}"
}

@test "skeleton: a mismatched signoff gets a skeleton with the current checksum" {
  write_ingress
  write_signoff "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  local h
  h=$(signoff_canonical_hash "${MANIFESTS_DIR}/run-foo/${SKELETON}")
  SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  [ "$(yq '.checksum' "${TEST_DIR}/skeletons/${SKELETON}")" = "sha256:${h}" ]
  assert_output_contains "skeleton written:"
}

@test "skeleton: a matching signoff gets no skeleton" {
  write_ingress
  write_signoff "$(signoff_canonical_hash "${MANIFESTS_DIR}/run-foo/${SKELETON}")"
  SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  [ ! -e "${TEST_DIR}/skeletons/${SKELETON}" ]
}

@test "skeleton: none written when SIGNOFF_SKELETON_DIR is unset" {
  write_ingress
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  [ ! -e "${TEST_DIR}/skeletons" ]
  [ "$(echo "${output}" | grep -c "skeleton written")" -eq 0 ]
}

# =============================================================================
# Signoff content
# =============================================================================

write_matching_signoff() {
  write_signoff "$(signoff_canonical_hash "${MANIFESTS_DIR}/run-foo/${SKELETON}")"
  local line
  for line in "$@"; do
    printf '%s\n' "${line}" >> "${SIGNOFFS_DIR}/${SKELETON}"
  done
}

@test "content: local build warns on leftover skeleton lines while uncommitted" {
  init_signoff_repo
  write_ingress
  write_matching_signoff "${SIGNOFF_SKELETON_HEADER_1}" "${SIGNOFF_SKELETON_REFERENCE_PLACEHOLDER}"
  BUILD_MODE=local run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  assert_output_contains "needs attention before it is committed"
  assert_output_contains "leftover skeleton line: ${SIGNOFF_SKELETON_HEADER_1}"
}

@test "content: local build warns on leftover skeleton lines while staged" {
  init_signoff_repo
  write_ingress
  write_matching_signoff "${SIGNOFF_SKELETON_HEADER_3}"
  git -C "${TEST_DIR}" add signoffs
  BUILD_MODE=local run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  assert_output_contains "needs attention before it is committed"
}

@test "content: local build fails on leftover skeleton lines once committed" {
  init_signoff_repo
  write_ingress
  write_matching_signoff "${SIGNOFF_SKELETON_HEADER_2_PREFIX}${SIGNOFFS_DIR}/${SKELETON}"
  commit_signoffs
  BUILD_MODE=local run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "leftover skeleton line: ${SIGNOFF_SKELETON_HEADER_2_PREFIX}"
}

@test "content: server build fails on leftover skeleton lines even uncommitted" {
  init_signoff_repo
  write_ingress
  write_matching_signoff 'reviewer: someone' 'signoffTimestamp: 2026-09-26T01:00:00Z' "${SIGNOFF_SKELETON_REFERENCE_PLACEHOLDER}"
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "leftover skeleton line: ${SIGNOFF_SKELETON_REFERENCE_PLACEHOLDER}"
}

@test "content: server build requires reviewer and signoffTimestamp" {
  write_ingress
  write_matching_signoff
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "reviewer is required on server builds"
  assert_output_contains "signoffTimestamp is required on server builds"
}

@test "content: local build does not require reviewer or signoffTimestamp" {
  write_ingress
  write_matching_signoff
  BUILD_MODE=local run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  [ "$(echo "${output}" | grep -c "needs attention")" -eq 0 ]
}

@test "content: server build accepts a complete signoff with an offset timestamp" {
  write_ingress
  write_matching_signoff 'reviewer: someone' 'signoffTimestamp: 2026-09-26T14:00:00+13:00' 'reference: KAP-1'
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
}

@test "content: server build rejects a timestamp without a zone" {
  write_ingress
  write_matching_signoff 'reviewer: someone' 'signoffTimestamp: 2026-09-26T14:00:00'
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "is not an ISO 8601 date and time with a zone"
}

@test "content: server build rejects a free-text timestamp" {
  write_ingress
  write_matching_signoff 'reviewer: someone' 'signoffTimestamp: last tuesday'
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
}
