#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Tests for lib/sensitive-resource-signoff.bash.

load helpers

setup() {
  TEST_DIR=$(create_test_dir "sensitive-resource-signoff")
  # shellcheck source=src/scripts/lib/sensitive-resource-signoff.bash
  source "${LIB_DIR}/sensitive-resource-signoff.bash"

  KINDS_FILE="${LIB_DIR}/../../data/signoff-kinds/default-1.1.txt"

  MANIFESTS_DIR="${TEST_DIR}/manifests"
  SIGNOFFS_DIR="${TEST_DIR}/signoffs"
  mkdir -p "${MANIFESTS_DIR}/some-app/src/kubernetes" \
           "${SIGNOFFS_DIR}/some-app/src/kubernetes"
}

write_ingress() {
  cat > "${MANIFESTS_DIR}/some-app/src/kubernetes/ingress.yaml" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules:
  - host: example.com
EOF
}

write_signoff() {
  local checksum="$1"
  cat > "${SIGNOFFS_DIR}/some-app/src/kubernetes/ingress.yaml" << EOF
sourcePath: some-app/src/kubernetes/ingress.yaml
checksum:   sha256:${checksum}
EOF
}

# =============================================================================
# signoff_canonical_hash - strip expression
# =============================================================================

@test "hash: our provenance annotations do not affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    kaptain.org/build-timestamp: "2026-09-25T20:00:00Z"
    kaptain.org/built-by: github-actions
    kaptain.org/generated-by: Generated by Kaptain generate-kubernetes-ingress
    kaptain.org/git-sha: abc123
    kaptain.org/helm-upstream-chart: ingress-nginx-4.11.0
    kaptain.org/image-uri: ghcr.io/org/app:1.2.3
    kaptain.org/source-repository: https://github.com/org/app
spec:
  rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: keel.sh/ and keelson.io/ annotations do not affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    keel.sh/policy: force
    keelson.io/track: latest
spec:
  rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: kaptain.org/version and app.kubernetes.io/version labels do not affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  labels:
    kaptain.org/version: "1.0.0"
    app.kubernetes.io/version: "1.0.0"
spec:
  rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: spec content changes do affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules:
  - host: a.example.com
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules:
  - host: b.example.com
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" != "${h2}" ]
}

@test "hash: pod-template rollout annotations on workloads do not affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d
spec:
  template:
    metadata:
      annotations: {}
    spec:
      containers: [{ name: d, image: i }]
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d
spec:
  template:
    metadata:
      annotations:
        kaptain.org/build-timestamp: "2026-09-25T20:00:00Z"
        keel.sh/policy: force
    spec:
      containers: [{ name: d, image: i }]
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: an unlisted kaptain.org/ annotation does affect the hash" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    kaptain.org/some-future-behaviour: "on"
spec:
  rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" != "${h2}" ]
}

@test "hash: absent annotations and annotations holding only stripped keys hash the same" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r
rules: []
EOF
  local h1
  h1=$(signoff_canonical_hash "${f}")

  cat > "${f}" << 'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r
  annotations:
    kaptain.org/git-sha: abc123
rules: []
EOF
  local h2
  h2=$(signoff_canonical_hash "${f}")
  [ "${h1}" = "${h2}" ]
}

@test "hash: projection adds no pod template to kinds that have none" {
  local f="${TEST_DIR}/manifest.yaml"
  cat > "${f}" << 'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r
rules: []
EOF
  [ "$(yq eval-all "${SIGNOFF_STRIP_EXPR}" -o=json "${f}" | jq -c 'has("spec")')" = "false" ]
}

@test "hash: missing file fails loudly" {
  run signoff_canonical_hash "${TEST_DIR}/does-not-exist.yaml"
  [ "${status}" -ne 0 ]
  assert_output_contains "Manifest file not found"
}

@test "hash: missing argument fails loudly" {
  run signoff_canonical_hash
  [ "${status}" -ne 0 ]
  assert_output_contains "requires exactly 1 argument"
}

# =============================================================================
# signoff_check_tree - end-to-end coverage / integrity
# =============================================================================

# =============================================================================
# Layout: the signoffs dir mirrors the manifest tree exactly
# =============================================================================

# An Ingress at <rel> in the manifest tree.
write_ingress_at() {
  local rel="$1"
  mkdir -p "$(dirname "${MANIFESTS_DIR}/${rel}")"
  cat > "${MANIFESTS_DIR}/${rel}" << 'EOF'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  rules:
  - host: example.com
EOF
}

# A signoff for the manifest at <rel>, at the same relative path.
write_signoff_for() {
  local rel="$1"
  mkdir -p "$(dirname "${SIGNOFFS_DIR}/${rel}")"
  cat > "${SIGNOFFS_DIR}/${rel}" << EOF
sourcePath: ${rel}
checksum:   sha256:$(signoff_canonical_hash "${MANIFESTS_DIR}/${rel}")
EOF
}

@test "layout: the signoff path is the manifest's tree-relative path, first segment kept" {
  write_ingress_at shop/billing/ingress.yaml
  [ "$(signoff_source_path "${MANIFESTS_DIR}" "${MANIFESTS_DIR}/shop/billing/ingress.yaml")" = "shop/billing/ingress.yaml" ]
  write_signoff_for shop/billing/ingress.yaml
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
}

@test "layout: a signoff with the child's folder stripped does not count" {
  write_ingress_at shop/billing/ingress.yaml
  mkdir -p "${SIGNOFFS_DIR}/billing"
  cat > "${SIGNOFFS_DIR}/billing/ingress.yaml" << EOF
sourcePath: billing/ingress.yaml
checksum:   sha256:$(signoff_canonical_hash "${MANIFESTS_DIR}/shop/billing/ingress.yaml")
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "MISSING  shop/billing/ingress.yaml"
  assert_output_contains "STALE    billing/ingress.yaml"
}

@test "layout: two children with the same relative path need a signoff each" {
  write_ingress_at alpha/ingress.yaml
  write_ingress_at beta/ingress.yaml
  write_signoff_for alpha/ingress.yaml
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "beta/ingress.yaml"
  write_signoff_for beta/ingress.yaml
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
}

@test "layout: a manifest at the tree root has its signoff at the signoffs root" {
  write_ingress_at ingress.yaml
  write_signoff_for ingress.yaml
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
}

@test "tree: matching signoff passes" {
  write_ingress
  local h
  h=$(signoff_canonical_hash "${MANIFESTS_DIR}/some-app/src/kubernetes/ingress.yaml")
  write_signoff "${h}"

  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  assert_output_contains "Signoff check passed"
}

@test "tree: missing signoff is listed as MISSING under the dirs named once at the top" {
  write_ingress
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "Signoff check: 1 sensitive resource(s) in ${MANIFESTS_DIR}/"
  assert_output_contains "Signoffs read from ${SIGNOFFS_DIR}/"
  assert_output_contains "MISSING  some-app/src/kubernetes/ingress.yaml"
  assert_output_contains "1 of 1 sensitive resource(s) failed the signoff check (1 missing)"
}

@test "tree: mismatched checksum is listed as CHANGED" {
  write_ingress
  write_signoff "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "CHANGED  some-app/src/kubernetes/ingress.yaml"
  assert_output_contains "1 of 1 sensitive resource(s) failed the signoff check (1 changed)"
}

@test "tree: stale signoff (no matching resource) fails" {
  cat > "${SIGNOFFS_DIR}/some-app/src/kubernetes/ingress.yaml" << 'EOF'
sourcePath: some-app/src/kubernetes/ingress.yaml
checksum:   sha256:deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "STALE    some-app/src/kubernetes/ingress.yaml"
  assert_output_contains "Delete each STALE signoff from ${SIGNOFFS_DIR}/ if its resource was removed on purpose."
  assert_output_contains "1 signoff(s) in ${SIGNOFFS_DIR}/ match no sensitive resource (1 stale)"
}

@test "tree: malformed signoff (missing checksum field) fails" {
  write_ingress
  cat > "${SIGNOFFS_DIR}/some-app/src/kubernetes/ingress.yaml" << 'EOF'
sourcePath: some-app/src/kubernetes/ingress.yaml
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "INVALID  some-app/src/kubernetes/ingress.yaml (no checksum field)"
}

@test "tree: non-sensitive resources do not require a signoff" {
  cat > "${MANIFESTS_DIR}/some-app/src/kubernetes/service.yaml" << 'EOF'
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  ports: []
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
}

@test "tree: a pass names the count and logs no error" {
  write_ingress_at alpha/ingress.yaml
  write_signoff_for alpha/ingress.yaml
  write_ingress_at beta/ingress.yaml
  write_signoff_for beta/ingress.yaml
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  assert_output_contains "OK       alpha/ingress.yaml"
  assert_output_contains "OK       beta/ingress.yaml"
  assert_output_contains "Signoff check passed: 2 of 2 sensitive resource(s) signed off."
  [ "$(grep -c '^ERROR' <<< "${output}")" -eq 0 ]
}

@test "tree: every problem gets one status line and the whole check one error line" {
  write_ingress_at alpha/ingress.yaml
  write_signoff_for alpha/ingress.yaml
  write_ingress_at missing/ingress.yaml
  write_ingress_at changed/ingress.yaml
  mkdir -p "${SIGNOFFS_DIR}/changed" "${SIGNOFFS_DIR}/invalid" "${SIGNOFFS_DIR}/gone"
  printf 'sourcePath: changed/ingress.yaml\nchecksum: sha256:00\n' > "${SIGNOFFS_DIR}/changed/ingress.yaml"
  write_ingress_at invalid/ingress.yaml
  printf 'sourcePath: invalid/ingress.yaml\n' > "${SIGNOFFS_DIR}/invalid/ingress.yaml"
  printf 'sourcePath: gone/ingress.yaml\nchecksum: sha256:00\n' > "${SIGNOFFS_DIR}/gone/ingress.yaml"
  run_merged_check
  [ "${status}" -ne 0 ]
  assert_output_contains "OK       alpha/ingress.yaml"
  assert_output_contains "MISSING  missing/ingress.yaml"
  assert_output_contains "CHANGED  changed/ingress.yaml"
  assert_output_contains "INVALID  invalid/ingress.yaml (no checksum field)"
  assert_output_contains "STALE    gone/ingress.yaml"
  assert_output_contains "Review each MISSING, CHANGED and INVALID entry in ${TEST_DIR}/skeletons/ and add if appropriate."
  assert_output_contains "To accept them all once reviewed (stale ones are already left out):"
  assert_output_contains "Then remove the three generated comment lines from each new signoff"
  assert_output_contains "4 signoff problem(s): 3 of 4 sensitive resource(s) failed (1 missing, 1 changed and 1 invalid), 1 stale signoff(s)."
  [ "$(grep -c '^ERROR' <<< "${output}")" -eq 1 ]
  # The full manifest path is named once, in the header, never per resource.
  [ "$(grep -cF "${MANIFESTS_DIR}" <<< "${output}")" -eq 1 ]
  # Every failing resource has a skeleton to review, the invalid one included.
  [ -f "${TEST_DIR}/skeletons/missing/ingress.yaml" ]
  [ -f "${TEST_DIR}/skeletons/changed/ingress.yaml" ]
  [ -f "${TEST_DIR}/skeletons/invalid/ingress.yaml" ]
}

@test "tree: custom kinds file replaces the default list entirely" {
  # Only Service is flagged: the custom list replaces the default.
  write_ingress
  cat > "${MANIFESTS_DIR}/some-app/src/kubernetes/service.yaml" << 'EOF'
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  ports: []
EOF
  local custom="${TEST_DIR}/custom-kinds.txt"
  cat > "${custom}" << 'EOF'
# custom sensitive kinds - replaces the default list
Service
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${custom}"
  [ "${status}" -ne 0 ]
  assert_output_contains "MISSING  some-app/src/kubernetes/service.yaml"
  ! grep -q "ingress.yaml" <<< "${output}"
}

@test "tree: missing kinds file fails loudly" {
  write_ingress
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${TEST_DIR}/no-such-kinds.txt"
  [ "${status}" -ne 0 ]
  assert_output_contains "kinds file not found"
}

@test "tree: multi-doc YAML hashed as a single unit" {
  mkdir -p "${MANIFESTS_DIR}/some-app/src/kubernetes"
  cat > "${MANIFESTS_DIR}/some-app/src/kubernetes/rbac.yaml" << 'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: r
subjects: []
EOF
  local h
  h=$(signoff_canonical_hash "${MANIFESTS_DIR}/some-app/src/kubernetes/rbac.yaml")
  [ -n "${h}" ]
  mkdir -p "${SIGNOFFS_DIR}/some-app/src/kubernetes"
  cat > "${SIGNOFFS_DIR}/some-app/src/kubernetes/rbac.yaml" << EOF
sourcePath: some-app/src/kubernetes/rbac.yaml
checksum:   sha256:${h}
EOF
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
}

@test "tree: missing manifests dir fails loudly" {
  run signoff_check_tree "${TEST_DIR}/does-not-exist" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "Manifests directory not found"
}

@test "tree: missing required arguments fails loudly" {
  run signoff_check_tree "${MANIFESTS_DIR}"
  [ "${status}" -ne 0 ]
  assert_output_contains "Usage: signoff_check_tree"
}

teardown() {
  dump_bats_result
}

# =============================================================================
# Skeletons
# =============================================================================

SKELETON="some-app/src/kubernetes/ingress.yaml"

# Git repo for the committed/uncommitted distinction; cd into it as the
# build runs from the repo.
init_signoff_repo() {
  git -C "${TEST_DIR}" init -q
  git -C "${TEST_DIR}" config user.name "Test Reviewer"
  git -C "${TEST_DIR}" config user.email "test@example.com"
  cd "${TEST_DIR}"
}

commit_signoffs() {
  git -C "${TEST_DIR}" add signoffs
  git -C "${TEST_DIR}" commit -q -m "signoffs"
}

@test "skeleton: a missing signoff gets a prefilled skeleton with the current checksum" {
  init_signoff_repo
  write_ingress
  local h
  h=$(signoff_canonical_hash "${MANIFESTS_DIR}/${SKELETON}")
  SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  local s="${TEST_DIR}/skeletons/${SKELETON}"
  [ -f "${s}" ]
  [ "$(sed -n 1p "${s}")" = "${SIGNOFF_SKELETON_HEADER_1}" ]
  [ "$(sed -n 2p "${s}")" = "${SIGNOFF_SKELETON_HEADER_2_PREFIX}${SIGNOFFS_DIR}/${SKELETON}" ]
  [ "$(sed -n 3p "${s}")" = "${SIGNOFF_SKELETON_HEADER_3}" ]
  [ "$(yq '.sourcePath' "${s}")" = "${SKELETON}" ]
  [ "$(yq '.checksum' "${s}")" = "sha256:${h}" ]
  [ "$(yq '.reviewer' "${s}")" = "Test Reviewer" ]
  [[ "$(yq '.signoffTimestamp' "${s}")" =~ ${SIGNOFF_TIMESTAMP_PATTERN} ]] || return 1
  grep -qxF "${SIGNOFF_SKELETON_REFERENCE_PLACEHOLDER}" "${s}"
}

@test "skeleton: reviewer falls back to a placeholder when git has no name" {
  write_ingress
  GIT_DIR=/nonexistent GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1 \
    SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  grep -qxF "# reviewer: <who reviewed it>" "${TEST_DIR}/skeletons/${SKELETON}"
}

@test "skeleton: a mismatched signoff gets a skeleton with the current checksum" {
  write_ingress
  write_signoff "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  local h
  h=$(signoff_canonical_hash "${MANIFESTS_DIR}/${SKELETON}")
  SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  [ "$(yq '.checksum' "${TEST_DIR}/skeletons/${SKELETON}")" = "sha256:${h}" ]
  assert_output_contains "Review each CHANGED entry in ${TEST_DIR}/skeletons/ and add if appropriate."
}

@test "skeleton: a matching signoff gets no skeleton" {
  write_ingress
  write_signoff "$(signoff_canonical_hash "${MANIFESTS_DIR}/${SKELETON}")"
  SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  [ ! -e "${TEST_DIR}/skeletons/${SKELETON}" ]
}

@test "skeleton: none written when SIGNOFF_SKELETON_DIR is unset" {
  write_ingress
  run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  [ ! -e "${TEST_DIR}/skeletons" ]
  [ "$(echo "${output}" | grep -c "skeleton written")" -eq 0 ]
}

# =============================================================================
# Merged signoffs dir: ready to replace the source dir after review
# =============================================================================

run_merged_check() {
  SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" SIGNOFF_MERGED_DIR="${TEST_DIR}/merged" \
    run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
}

@test "merged: existing signoffs are kept and a missing one is added as its skeleton" {
  write_ingress_at alpha/ingress.yaml
  write_signoff_for alpha/ingress.yaml
  write_ingress_at beta/ingress.yaml
  run_merged_check
  [ "${status}" -ne 0 ]
  cmp "${SIGNOFFS_DIR}/alpha/ingress.yaml" "${TEST_DIR}/merged/alpha/ingress.yaml"
  cmp "${TEST_DIR}/skeletons/beta/ingress.yaml" "${TEST_DIR}/merged/beta/ingress.yaml"
  assert_output_contains "rm -r ${SIGNOFFS_DIR} && mv ${TEST_DIR}/merged ${SIGNOFFS_DIR}"
}

@test "merged: a changed resource's signoff is replaced by its skeleton" {
  write_ingress
  write_signoff "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  run_merged_check
  [ "${status}" -ne 0 ]
  [ "$(yq '.checksum' "${TEST_DIR}/merged/${SKELETON}")" = "sha256:$(signoff_canonical_hash "${MANIFESTS_DIR}/${SKELETON}")" ]
}

@test "merged: stale signoffs are dropped, and so are directories left empty" {
  write_ingress_at alpha/ingress.yaml
  write_signoff_for alpha/ingress.yaml
  mkdir -p "${SIGNOFFS_DIR}/gone/deep"
  printf 'sourcePath: gone/deep/ingress.yaml\nchecksum: sha256:00\n' > "${SIGNOFFS_DIR}/gone/deep/ingress.yaml"
  run_merged_check
  [ "${status}" -ne 0 ]
  assert_output_contains "STALE    gone/deep/ingress.yaml"
  [ -f "${TEST_DIR}/merged/alpha/ingress.yaml" ]
  [ ! -e "${TEST_DIR}/merged/gone" ]
}

@test "merged: other files in the signoffs dir are kept" {
  write_ingress
  printf 'notes\n' > "${SIGNOFFS_DIR}/README.md"
  run_merged_check
  [ "${status}" -ne 0 ]
  cmp "${SIGNOFFS_DIR}/README.md" "${TEST_DIR}/merged/README.md"
}

@test "merged: built when there is no signoffs dir yet" {
  rm -rf "${SIGNOFFS_DIR}"
  write_ingress
  run_merged_check
  [ "${status}" -ne 0 ]
  [ -f "${TEST_DIR}/merged/${SKELETON}" ]
}

@test "merged: nothing written when every signoff matches" {
  write_ingress
  write_signoff "$(signoff_canonical_hash "${MANIFESTS_DIR}/${SKELETON}")"
  run_merged_check
  [ "${status}" -eq 0 ]
  [ ! -e "${TEST_DIR}/merged" ]
}

@test "merged: output from an earlier run does not leak in" {
  write_ingress
  mkdir -p "${TEST_DIR}/skeletons/old" "${TEST_DIR}/merged/old"
  printf 'x\n' > "${TEST_DIR}/skeletons/old/ingress.yaml"
  printf 'x\n' > "${TEST_DIR}/merged/old/ingress.yaml"
  run_merged_check
  [ "${status}" -ne 0 ]
  [ ! -e "${TEST_DIR}/skeletons/old" ]
  [ ! -e "${TEST_DIR}/merged/old" ]
  [ -f "${TEST_DIR}/merged/${SKELETON}" ]
}

@test "merged: none written when SIGNOFF_MERGED_DIR is unset" {
  write_ingress
  SIGNOFF_SKELETON_DIR="${TEST_DIR}/skeletons" run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  [ ! -e "${TEST_DIR}/merged" ]
  [ "$(echo "${output}" | grep -c "mv ")" -eq 0 ]
}

# =============================================================================
# Signoff content
# =============================================================================

write_matching_signoff() {
  write_signoff "$(signoff_canonical_hash "${MANIFESTS_DIR}/${SKELETON}")"
  local line
  for line in "$@"; do
    printf '%s\n' "${line}" >> "${SIGNOFFS_DIR}/${SKELETON}"
  done
}

@test "content: local build warns on leftover skeleton lines while uncommitted" {
  init_signoff_repo
  write_ingress
  write_matching_signoff "${SIGNOFF_SKELETON_HEADER_1}" "${SIGNOFF_SKELETON_REFERENCE_PLACEHOLDER}"
  BUILD_MODE=local run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  assert_output_contains "PENDING  some-app/src/kubernetes/ingress.yaml (leftover skeleton lines; fails once committed)"
  assert_output_contains "Signoff check passed, 1 signoff(s) pending cleanup before commit."
}

@test "content: local build warns on leftover skeleton lines while staged" {
  init_signoff_repo
  write_ingress
  write_matching_signoff "${SIGNOFF_SKELETON_HEADER_3}"
  git -C "${TEST_DIR}" add signoffs
  BUILD_MODE=local run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  assert_output_contains "PENDING  some-app/src/kubernetes/ingress.yaml"
}

@test "content: local build fails on leftover skeleton lines once committed" {
  init_signoff_repo
  write_ingress
  write_matching_signoff "${SIGNOFF_SKELETON_HEADER_2_PREFIX}${SIGNOFFS_DIR}/${SKELETON}"
  commit_signoffs
  BUILD_MODE=local run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "INVALID  some-app/src/kubernetes/ingress.yaml (leftover skeleton lines)"
}

@test "content: server build fails on leftover skeleton lines even uncommitted" {
  init_signoff_repo
  write_ingress
  write_matching_signoff 'reviewer: someone' 'signoffTimestamp: 2026-09-26T01:00:00Z' "${SIGNOFF_SKELETON_REFERENCE_PLACEHOLDER}"
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "INVALID  some-app/src/kubernetes/ingress.yaml (leftover skeleton lines)"
}

@test "content: server build requires reviewer and signoffTimestamp" {
  write_ingress
  write_matching_signoff
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "reviewer is required on server builds"
  assert_output_contains "signoffTimestamp is required on server builds"
}

@test "content: local build does not require reviewer or signoffTimestamp" {
  write_ingress
  write_matching_signoff
  BUILD_MODE=local run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
  [ "$(echo "${output}" | grep -c "needs attention")" -eq 0 ]
}

@test "content: server build accepts a complete signoff with an offset timestamp" {
  write_ingress
  write_matching_signoff 'reviewer: someone' 'signoffTimestamp: 2026-09-26T14:00:00+13:00' 'reference: KAP-1'
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -eq 0 ]
}

@test "content: server build rejects a timestamp without a zone" {
  write_ingress
  write_matching_signoff 'reviewer: someone' 'signoffTimestamp: 2026-09-26T14:00:00'
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
  assert_output_contains "is not an ISO 8601 date and time with a zone"
}

@test "content: server build rejects a free-text timestamp" {
  write_ingress
  write_matching_signoff 'reviewer: someone' 'signoffTimestamp: last tuesday'
  BUILD_MODE=build_server run signoff_check_tree "${MANIFESTS_DIR}" "${SIGNOFFS_DIR}" "${KINDS_FILE}"
  [ "${status}" -ne 0 ]
}
