# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

- name: Generate ConfigMap manifest
  id: generate-configmap
  if: steps.kpm.outputs.KUBERNETES_CONFIGMAP_SUB_PATH != ''
  uses: ./.github/buildon-github-actions/src/actions/generate-kubernetes-configmap
  with:
    # Required context
    project-name: ${{ steps.versions.outputs.project-name }}
    # ConfigMap settings
    kubernetes-configmap-sub-path: ${{ steps.kpm.outputs.KUBERNETES_CONFIGMAP_SUB_PATH }}
    # Global settings
    output-sub-path: ${{ steps.kpm.outputs.OUTPUT_SUB_PATH }}
    token-name-style: ${{ steps.kpm.outputs.TOKEN_NAME_STYLE }}
    token-delimiter-style: ${{ steps.kpm.outputs.TOKEN_DELIMITER_STYLE }}
    kubernetes-configmap-name-checksum-injection: ${{ steps.kpm.outputs.KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION }}
    kubernetes-global-additional-labels: ${{ steps.kpm.outputs.KUBERNETES_GLOBAL_ADDITIONAL_LABELS }}
    kubernetes-global-additional-annotations: ${{ steps.kpm.outputs.KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS }}
    kubernetes-configmap-additional-labels: ${{ steps.kpm.outputs.KUBERNETES_CONFIGMAP_ADDITIONAL_LABELS }}
    kubernetes-configmap-additional-annotations: ${{ steps.kpm.outputs.KUBERNETES_CONFIGMAP_ADDITIONAL_ANNOTATIONS }}
