# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Docker Push All'
description: 'Pushes all Docker images registered during build/tag steps'

inputs:
  # Build output
  output-sub-path:
    description: 'Build output directory (relative)'
    required: false
    default: 'target'

  # Action-specific inputs
  is-release:
    description: 'Whether to push (true) or skip (false)'
    required: true

outputs:
  images-pushed:
    description: 'Number of images pushed'
    value: ${{ steps.push.outputs.IMAGES_PUSHED }}

runs:
  using: 'composite'
  steps:
    - name: Push all images
      id: push
      shell: bash
      env:
        LOG_ERROR_PREFIX: '::error::'
        OUTPUT_SUB_PATH: ${{ inputs.output-sub-path }}
        IS_RELEASE: ${{ inputs.is-release }}
      run: "${{ github.action_path }}/../../scripts/main/docker-push-all"
