# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'EKS Cluster Management Post-Build Validate'
description: 'Validate substituted cluster yaml and image integrity after docker build'

inputs:
  # Build output
  output-sub-path:
    description: 'Build output directory (relative)'
    required: false
    default: 'target'
  # Docker build options
  dockerfile-substitution-files:
    description: 'Comma-separated list of files to perform token substitution on (relative to dockerfile-sub-path and docker-context-sub-path)'
    required: false
    default: 'Dockerfile'
  dockerfile-sub-path:
    description: 'Directory containing Dockerfile, relative to repo root.'
    required: false
    default: 'src/docker'
  dockerfile-squash:
    description: 'Squash mode: squash, squash-all, or no'
    required: false
    default: 'squash'
  dockerfile-no-cache:
    description: 'Disable layer caching for reproducible builds'
    required: false
    default: 'true'
  dockerfile-sub-path-linux-amd64:
    description: 'Per-platform Dockerfile directory for linux/amd64 multi-platform builds'
    required: false
    default: 'src/docker-linux-amd64'
  dockerfile-sub-path-linux-arm64:
    description: 'Per-platform Dockerfile directory for linux/arm64 multi-platform builds'
    required: false
    default: 'src/docker-linux-arm64'
  # Target platform for docker/podman operations
  docker-platform:
    description: 'Target platform (linux/amd64, linux/arm64, or both comma-separated)'
    required: false
    default: 'linux/amd64'
  # Token substitution
  token-delimiter-style:
    description: 'Token delimiter syntax for variables (shell, mustache, helm, erb, github-actions, blade, stringtemplate, ognl, t4, swift)'
    required: false
    default: 'shell'
  token-name-style:
    description: 'Case style for token names (UPPER_SNAKE, lower_snake, lower-kebab, UPPER-KEBAB, camelCase, PascalCase, lower.dot, UPPER.DOT)'
    required: false
    default: 'PascalCase'
  token-name-validation:
    description: 'How to validate user token names (MATCH = must match token-name-style, ALL = accept any valid name)'
    required: false
    default: 'MATCH'
  allow-builtin-token-override:
    description: 'Allow user tokens to override built-in tokens (for template/reusable projects)'
    required: false
    default: 'false'
  config-sub-path:
    description: 'Directory containing user-defined token files (relative)'
    required: false
    default: 'src/config'
  config-value-trailing-newline:
    description: 'How to handle trailing newlines in config values (strip-for-single-line, preserve-all, always-strip-one-newline)'
    required: false
    default: 'strip-for-single-line'
  # Container runtime
  image-build-command:
    description: 'Container runtime command (podman or docker)'
    required: true

  # Action-specific inputs (passed from workflow/version generator)
  project-name:
    description: 'Project name (from version generator)'
    required: true
  docker-tag:
    description: 'Tag for target image (from version generator)'
    required: true
  docker-image-name:
    description: 'Image name (from version generator)'
    required: true
  docker-target-registry:
    description: 'Target container registry (pre-resolved by workflow)'
    required: true
  docker-target-namespace:
    description: 'Namespace between registry and image name (pre-resolved by workflow)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate substituted cluster yaml and image integrity
      id: post-build-validate
      shell: bash
      env:
        BUILD_PLATFORM: github-actions
        BUILD_PLATFORM_LOG_PROVIDER: github-actions
        OUTPUT_SUB_PATH: ${{ inputs.output-sub-path }}
        DOCKERFILE_SUB_PATH: ${{ inputs.dockerfile-sub-path }}
        DOCKERFILE_SUB_PATH_LINUX_AMD64: ${{ inputs.dockerfile-sub-path-linux-amd64 }}
        DOCKERFILE_SUB_PATH_LINUX_ARM64: ${{ inputs.dockerfile-sub-path-linux-arm64 }}
        DOCKER_PLATFORM: ${{ inputs.docker-platform }}
        TOKEN_DELIMITER_STYLE: ${{ inputs.token-delimiter-style }}
        TOKEN_NAME_STYLE: ${{ inputs.token-name-style }}
        IMAGE_BUILD_COMMAND: ${{ inputs.image-build-command }}
        PROJECT_NAME: ${{ inputs.project-name }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
        DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
        DOCKER_TARGET_REGISTRY: ${{ inputs.docker-target-registry }}
        DOCKER_TARGET_NAMESPACE: ${{ inputs.docker-target-namespace }}
      run: "${{ github.action_path }}/../../scripts/main/aws-eks-cluster-management-post-build-validate"
