# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Docker Multi-Tag'
description: 'Discovers and tags all matching images for additional registries'

inputs:
  # Build output
  output-sub-path:
    description: 'Build output directory (relative)'
    required: false
    default: 'target'
  # Docker registry logins
  docker-registry-logins:
    description: 'YAML config for Docker registry logins (registry URL as key)'
    required: false
    default: ''
  # Docker target config
  docker-target-registry:
    description: 'Target container registry domain (defaults to ghcr.io on gh actions)'
    required: false
    default: ''
  docker-target-base-path:
    description: 'Path between registry and image name (defaults to lower cased org name on gh actions)'
    required: false
    default: ''
  # Docker push targets
  docker-push-targets:
    description: 'JSON array of additional push targets [{registry, base-path?}]'
    required: false
    default: ''

  # Action-specific inputs
  docker-image-name:
    description: 'Image name portion'
    required: true
  docker-tag:
    description: 'Base tag for images'
    required: true
  docker-target-registry:
    description: 'Primary registry to filter source images'
    required: true
  docker-target-base-path:
    description: 'Primary base path within registry'
    required: false
    default: ''
  # Container runtime
  image-build-command:
    description: 'Container runtime command (podman or docker)'
    required: true

outputs:
  images-tagged:
    description: 'Number of images tagged'
    value: ${{ steps.tag.outputs.IMAGES_TAGGED }}

runs:
  using: 'composite'
  steps:
    - name: Tag images
      id: tag
      shell: bash
      env:
        OUTPUT_SUB_PATH: ${{ inputs.output-sub-path }}
        DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
        DOCKER_PUSH_TARGETS: ${{ inputs.docker-push-targets }}
        DOCKER_TARGET_REGISTRY: ${{ inputs.docker-target-registry }}
        DOCKER_TARGET_BASE_PATH: ${{ inputs.docker-target-base-path }}
        IMAGE_BUILD_COMMAND: ${{ inputs.image-build-command }}
      run: "${{ github.action_path }}/../../scripts/main/docker-multi-tag"
