# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Docker Multi-Tag'
description: 'Discovers and tags all matching images for additional registries'

inputs:
  # Docker push image list file path
  docker-push-image-list-file:
    description: 'Path to file listing image URIs for docker-push-all (set by docker-registry-logins)'
    required: true
  # Docker registry logins
  docker-registry-logins:
    description: 'YAML config for Docker registry logins (registry URL as key)'
    required: false
    default: ''
  # Docker target config
  docker-target-registry:
    description: 'Target container registry domain (defaults to ghcr.io on GH Actions)'
    required: false
    default: ''
  docker-target-namespace:
    description: 'Path segment between registry and image name (defaults to lower cased org name or user ID on GH Actions)'
    required: false
    default: ''
  # Docker push targets
  docker-push-targets:
    description: 'JSON array of additional push targets [{registry, namespace?}]'
    required: false
    default: ''

  # Action-specific inputs
  docker-image-name:
    description: 'Image name portion'
    required: true
  docker-tag:
    description: 'Base tag for images'
    required: true
  docker-target-registry:
    description: 'Primary registry to filter source images'
    required: true
  docker-target-namespace:
    description: 'Primary namespace within registry'
    required: false
    default: ''
  # Container runtime
  image-build-command:
    description: 'Container runtime command (podman or docker)'
    required: true
  # Target platform for docker/podman operations
  docker-platform:
    description: 'Target platform (linux/amd64, linux/arm64, or both comma-separated)'
    required: false
    default: 'linux/amd64'

outputs:
  images-tagged:
    description: 'Number of images tagged'
    value: ${{ steps.tag.outputs.IMAGES_TAGGED }}

runs:
  using: 'composite'
  steps:
    - name: Tag images
      id: tag
      shell: bash
      env:
        DOCKER_PUSH_IMAGE_LIST_FILE: ${{ inputs.docker-push-image-list-file }}
        DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
        DOCKER_PUSH_TARGETS: ${{ inputs.docker-push-targets }}
        DOCKER_TARGET_REGISTRY: ${{ inputs.docker-target-registry }}
        DOCKER_TARGET_NAMESPACE: ${{ inputs.docker-target-namespace }}
        IMAGE_BUILD_COMMAND: ${{ inputs.image-build-command }}
        DOCKER_PLATFORM: ${{ inputs.docker-platform }}
      run: "${{ github.action_path }}/../../scripts/main/docker-multi-tag"
