# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.

name: Custom Target Registry

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@1.1.13
    permissions:
      contents: write
      packages: write
      checks: write
    secrets:
      docker-registry-logins-secrets: |
        {
          "HARBOR_USER": "${{ secrets.HARBOR_USER }}",
          "HARBOR_PASS": "${{ secrets.HARBOR_PASS }}"
        }
