# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Basic Quality Checks'
description: 'Basic quality checks for commits and branches'
author: 'kube-kaptain'

inputs:
  release-branch:
    description: 'The release branch name'
    required: false
  additional-release-branches:
    description: 'Comma-separated list of additional release branches'
    required: false
    default: ''
  block-slashes:
    description: 'DEPRECATED: Use block-slash-containing-branches instead'
    required: false
    default: ''
  block-slash-containing-branches:
    description: 'Block branch names containing slashes'
    required: false
    default: 'false'
  block-double-hyphen-containing-branches:
    description: 'Block branch names containing double hyphens (typo detection)'
    required: false
    default: 'true'
  require-conventional-branches:
    description: 'Require branch names start with feature/, fix/, etc.'
    required: false
    default: 'false'
  require-conventional-commits:
    description: 'Require commits use conventional commit format (feat:, fix:, etc.)'
    required: false
    default: 'false'
  block-conventional-commits:
    description: 'Block commits that use conventional commit format'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Enforce quality standards
      id: check
      shell: bash
      env:
        LOG_ERROR_PREFIX: '::error::'
        LOG_WARNING_PREFIX: '::warning::'
        CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}
        RELEASE_BRANCH: ${{ inputs.release-branch }}
        ADDITIONAL_RELEASE_BRANCHES: ${{ inputs.additional-release-branches }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        TARGET_BRANCH: ${{ github.base_ref }}
        MERGE_CANDIDATE_CREATOR: ${{ github.event.pull_request.user.login }}
        BLOCK_SLASHES: ${{ inputs.block-slashes }}
        BLOCK_SLASH_CONTAINING_BRANCHES: ${{ inputs.block-slash-containing-branches }}
        BLOCK_DOUBLE_HYPHEN_CONTAINING_BRANCHES: ${{ inputs.block-double-hyphen-containing-branches }}
        REQUIRE_CONVENTIONAL_BRANCHES: ${{ inputs.require-conventional-branches }}
        BLOCK_CONVENTIONAL_COMMITS: ${{ inputs.block-conventional-commits }}
        REQUIRE_CONVENTIONAL_COMMITS: ${{ inputs.require-conventional-commits }}
      run: "${{ github.action_path }}/../../scripts/main/basic-quality-checks"
