# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: Hook - Pre-Package Prepare
description: Runs user's hook script before manifest packaging to generate ConfigMaps, modify manifests, or add files

inputs:
  script-sub-path:
    description: 'Path to script relative to .github/ (e.g., bin/pre-package.bash)'
    required: true
  manifests-sub-path:
    description: 'Manifests source directory (relative)'
    required: true
  manifests-substituted-sub-path:
    description: 'Manifests substituted directory (relative, where substituted manifests go)'
    required: true
  output-sub-path:
    description: 'Build output directory (relative)'
    required: true
  version:
    description: 'Version string'
    required: true
  docker-tag:
    description: 'Docker tag'
    required: true
  docker-image-name:
    description: 'Docker image name'
    required: true
  project-name:
    description: 'Project name'
    required: true
  is-release:
    description: 'Whether this is a release build'
    required: true

runs:
  using: composite
  steps:
    - name: Run pre-package prepare hook
      shell: bash
      env:
        HOOK_SCRIPT_SUB_PATH: .github/${{ inputs.script-sub-path }}
        MANIFESTS_SUB_PATH: ${{ inputs.manifests-sub-path }}
        MANIFESTS_SUBSTITUTED_SUB_PATH: ${{ inputs.manifests-substituted-sub-path }}
        OUTPUT_SUB_PATH: ${{ inputs.output-sub-path }}
        VERSION: ${{ inputs.version }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
        DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
        PROJECT_NAME: ${{ inputs.project-name }}
        IS_RELEASE: ${{ inputs.is-release }}
      run: .github/buildon-github-actions/src/scripts/main/hook-pre-package-prepare
