# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.

apiVersion: kaptain.org/1.23
kind: docker-build-dockerfile

spec:
  global:
    release:
      versioning:
        strategy: compound-file-pattern-match
        patternType: dockerfile-env-kubectl
        source:
          subPath: src/docker
          fileName: Dockerfile
          prefixParts: 2
        sourceTwo:
          subPath: .
          fileName: PATCH_VERSION
          pattern: '^([0-9]+)$'
