# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Generate Kubernetes ServiceAccount'
description: 'Generates a Kubernetes ServiceAccount manifest for pod identity and RBAC binding'

inputs:
  kubernetes-serviceaccount-generation-enabled:
    description: 'Enable ServiceAccount generation (true/false)'
    required: false
    default: 'false'
  kubernetes-serviceaccount-name-suffix:
    description: 'Optional suffix for ServiceAccount name and filename'
    required: false
    default: ''
  kubernetes-serviceaccount-combined-sub-path:
    description: 'Sub-path within combined/ for output (default: empty)'
    required: false
    default: ''
  output-sub-path:
    description: 'Build output directory (relative)'
    required: false
    default: 'target'
  token-name-style:
    description: 'Case style for token names (UPPER_SNAKE, lower_snake, lower-kebab, UPPER-KEBAB, camelCase, PascalCase, lower.dot, UPPER.DOT)'
    required: false
    default: 'PascalCase'
  token-delimiter-style:
    description: 'Token delimiter syntax for variables (shell, mustache, helm, erb, github-actions, blade, stringtemplate, ognl, t4, swift)'
    required: false
    default: 'shell'
  kubernetes-global-additional-labels:
    description: 'Additional labels for all Kubernetes manifests (comma-separated key=value)'
    required: false
    default: ''
  kubernetes-global-additional-annotations:
    description: 'Additional annotations for all Kubernetes manifests (comma-separated key=value)'
    required: false
    default: ''
  kubernetes-serviceaccount-additional-labels:
    description: 'Additional labels specific to ServiceAccount (comma-separated key=value)'
    required: false
    default: ''
  kubernetes-serviceaccount-additional-annotations:
    description: 'Additional annotations specific to ServiceAccount (comma-separated key=value)'
    required: false
    default: ''

  # Required context
  project-name:
    description: 'Project name (required)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate ServiceAccount manifest
      id: generate
      shell: bash
      env:
        LOG_ERROR_PREFIX: '::error::'
        # Required context
        PROJECT_NAME: ${{ inputs.project-name }}
        # ServiceAccount settings
        KUBERNETES_SERVICEACCOUNT_GENERATION_ENABLED: ${{ inputs.kubernetes-serviceaccount-generation-enabled }}
        KUBERNETES_SERVICEACCOUNT_NAME_SUFFIX: ${{ inputs.kubernetes-serviceaccount-name-suffix }}
        KUBERNETES_SERVICEACCOUNT_COMBINED_SUB_PATH: ${{ inputs.kubernetes-serviceaccount-combined-sub-path }}
        OUTPUT_SUB_PATH: ${{ inputs.output-sub-path }}
        TOKEN_NAME_STYLE: ${{ inputs.token-name-style }}
        TOKEN_DELIMITER_STYLE: ${{ inputs.token-delimiter-style }}
        KUBERNETES_GLOBAL_ADDITIONAL_LABELS: ${{ inputs.kubernetes-global-additional-labels }}
        KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS: ${{ inputs.kubernetes-global-additional-annotations }}
        KUBERNETES_SERVICEACCOUNT_ADDITIONAL_LABELS: ${{ inputs.kubernetes-serviceaccount-additional-labels }}
        KUBERNETES_SERVICEACCOUNT_ADDITIONAL_ANNOTATIONS: ${{ inputs.kubernetes-serviceaccount-additional-annotations }}
      run: "${{ github.action_path }}/../../scripts/generators/generate-kubernetes-serviceaccount"
