# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Resolve Target Registry and Namespace'
description: 'Resolves target registry (defaults to ghcr.io) and computes namespace (auto-detects org/user for GHCR)'

inputs:
  # Docker registry logins
  docker-registry-logins:
    description: 'YAML config for Docker registry logins (registry URL as key)'
    required: false
    default: ''
  # Docker target config
  docker-target-registry:
    description: 'Target container registry domain (defaults to ghcr.io on GH Actions)'
    required: false
    default: ''
  docker-target-namespace:
    description: 'Path segment between registry and image name (defaults to lower cased org name or user ID on GH Actions)'
    required: false
    default: ''
  # Docker push targets
  docker-push-targets:
    description: 'JSON array of additional push targets [{registry, namespace?}]'
    required: false
    default: ''

outputs:
  docker-target-registry:
    description: 'Resolved target registry'
    value: ${{ steps.resolve.outputs.docker-target-registry }}
  docker-target-namespace:
    description: 'Computed target namespace'
    value: ${{ steps.resolve.outputs.docker-target-namespace }}

runs:
  using: 'composite'
  steps:
    - name: Resolve target registry and namespace
      id: resolve
      shell: bash
      run: |
        # Use provided registry or default to ghcr.io
        if [[ -n "${{ inputs.docker-target-registry }}" ]]; then
          RESOLVED_REGISTRY="${{ inputs.docker-target-registry }}"
        else
          RESOLVED_REGISTRY="ghcr.io"
        fi
        echo "docker-target-registry=$RESOLVED_REGISTRY" >> "$GITHUB_OUTPUT"

        # Auto-set namespace for GHCR if not explicitly provided
        # Note: GHCR requires lowercase paths, so we lowercase the org name
        if [[ "$RESOLVED_REGISTRY" == "ghcr.io" && -z "${{ inputs.docker-target-namespace }}" ]]; then
          OWNER="${{ github.repository_owner }}"
          echo "docker-target-namespace=${OWNER,,}" >> "$GITHUB_OUTPUT"
        else
          echo "docker-target-namespace=${{ inputs.docker-target-namespace }}" >> "$GITHUB_OUTPUT"
        fi
