# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: Run Hook Script
description: Runs a user-provided hook script from the .github/ directory

inputs:
  script-sub-path:
    description: 'Path to script relative to .github/ (e.g., bin/pre-tagging.bash)'
    required: true
  # Paths for file preparation
  dockerfile-sub-path:
    description: 'Docker source directory (relative)'
    required: false
    default: ''
  docker-context-sub-path:
    description: 'Docker build context directory (relative, where docker build runs from)'
    required: false
    default: ''
  manifests-sub-path:
    description: 'Manifests source directory (relative)'
    required: false
    default: ''
  manifests-substituted-sub-path:
    description: 'Manifests substituted directory (relative, where substituted manifests go)'
    required: false
    default: ''
  manifests-zip-sub-path:
    description: 'Manifests zip directory (relative, where the zip file is created)'
    required: false
    default: ''
  manifests-zip-file-name:
    description: 'Manifests zip file name'
    required: false
    default: ''
  output-sub-path:
    description: 'Build output directory (relative)'
    required: false
    default: ''
  # Version information
  version:
    description: 'Version string'
    required: false
    default: ''
  version-major:
    description: 'Major version number'
    required: false
    default: ''
  version-minor:
    description: 'Minor version number'
    required: false
    default: ''
  version-patch:
    description: 'Patch version number'
    required: false
    default: ''
  version-2-part:
    description: 'Version padded/truncated to 2 parts'
    required: false
    default: ''
  version-3-part:
    description: 'Version padded/truncated to 3 parts'
    required: false
    default: ''
  version-4-part:
    description: 'Version padded/truncated to 4 parts'
    required: false
    default: ''
  docker-tag:
    description: 'Docker tag'
    required: false
    default: ''
  docker-image-name:
    description: 'Docker image name'
    required: false
    default: ''
  is-release:
    description: 'Whether this is a release build'
    required: false
    default: ''
  project-name:
    description: 'Project name'
    required: false
    default: ''
  target-image-full-uri:
    description: 'Full target image URI'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Validate script exists
      shell: bash
      run: |
        SCRIPT_SUB_PATH=".github/${{ inputs.script-sub-path }}"
        if [[ ! -f "$SCRIPT_SUB_PATH" ]]; then
          echo "::error::Hook script not found: $SCRIPT_SUB_PATH"
          echo "Configured script-sub-path '${{ inputs.script-sub-path }}' does not exist under .github/"
          exit 1
        fi
        if [[ ! -x "$SCRIPT_SUB_PATH" ]]; then
          echo "::error::Hook script is not executable: $SCRIPT_SUB_PATH"
          echo "Run: chmod +x $SCRIPT_SUB_PATH"
          exit 1
        fi
        echo "Found executable script: $SCRIPT_SUB_PATH"

    - name: Run hook script
      shell: bash
      env:
        # Paths
        DOCKERFILE_SUB_PATH: ${{ inputs.dockerfile-sub-path }}
        DOCKER_CONTEXT_SUB_PATH: ${{ inputs.docker-context-sub-path }}
        MANIFESTS_SUB_PATH: ${{ inputs.manifests-sub-path }}
        MANIFESTS_SUBSTITUTED_SUB_PATH: ${{ inputs.manifests-substituted-sub-path }}
        MANIFESTS_ZIP_SUB_PATH: ${{ inputs.manifests-zip-sub-path }}
        MANIFESTS_ZIP_FILE_NAME: ${{ inputs.manifests-zip-file-name }}
        OUTPUT_SUB_PATH: ${{ inputs.output-sub-path }}
        # Version info
        VERSION: ${{ inputs.version }}
        VERSION_MAJOR: ${{ inputs.version-major }}
        VERSION_MINOR: ${{ inputs.version-minor }}
        VERSION_PATCH: ${{ inputs.version-patch }}
        VERSION_2_PART: ${{ inputs.version-2-part }}
        VERSION_3_PART: ${{ inputs.version-3-part }}
        VERSION_4_PART: ${{ inputs.version-4-part }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
        DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
        IS_RELEASE: ${{ inputs.is-release }}
        PROJECT_NAME: ${{ inputs.project-name }}
        TARGET_IMAGE_FULL_URI: ${{ inputs.target-image-full-uri }}
      run: |
        SCRIPT_SUB_PATH=".github/${{ inputs.script-sub-path }}"
        echo "Running: $SCRIPT_SUB_PATH"
        "$SCRIPT_SUB_PATH"
