#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Hook-specific defaults that don't belong in shared defaults files
# These are pass-through vars only needed by hooks, not by the scripts they call
#
# shellcheck disable=SC2034  # Variables used by sourcing scripts

# Docker config (defaults come from workflow/action layer)
DOCKER_TARGET_REGISTRY="${DOCKER_TARGET_REGISTRY:-}"
DOCKER_TARGET_BASE_PATH="${DOCKER_TARGET_BASE_PATH:-}"
DOCKER_REGISTRY_LOGINS="${DOCKER_REGISTRY_LOGINS:-}"
DOCKER_PUSH_TARGETS="${DOCKER_PUSH_TARGETS:-}"

# Manifests packaging
MANIFESTS_REPO_PROVIDER_TYPE="${MANIFESTS_REPO_PROVIDER_TYPE:-}"
MANIFESTS_PACKAGING_BASE_IMAGE="${MANIFESTS_PACKAGING_BASE_IMAGE:-}"

# Release branches
RELEASE_BRANCH="${RELEASE_BRANCH:-}"
ADDITIONAL_RELEASE_BRANCHES="${ADDITIONAL_RELEASE_BRANCHES:-}"

# Kubernetes generation (defaults in generators, hooks just pass through)
# Kubernetes Generation Globals
KUBERNETES_GLOBAL_ADDITIONAL_LABELS="${KUBERNETES_GLOBAL_ADDITIONAL_LABELS:-}"
KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS="${KUBERNETES_GLOBAL_ADDITIONAL_ANNOTATIONS:-}"
# Kubernetes ConfigMap Generation
KUBERNETES_CONFIGMAP_SUB_PATH="${KUBERNETES_CONFIGMAP_SUB_PATH:-}"
KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION="${KUBERNETES_CONFIGMAP_NAME_CHECKSUM_INJECTION:-}"
KUBERNETES_CONFIGMAP_ADDITIONAL_LABELS="${KUBERNETES_CONFIGMAP_ADDITIONAL_LABELS:-}"
KUBERNETES_CONFIGMAP_ADDITIONAL_ANNOTATIONS="${KUBERNETES_CONFIGMAP_ADDITIONAL_ANNOTATIONS:-}"
# Kubernetes secret template generation
KUBERNETES_SECRET_TEMPLATE_SUB_PATH="${KUBERNETES_SECRET_TEMPLATE_SUB_PATH:-}"
KUBERNETES_SECRET_TEMPLATE_NAME_CHECKSUM_INJECTION="${KUBERNETES_SECRET_TEMPLATE_NAME_CHECKSUM_INJECTION:-}"
KUBERNETES_SECRET_TEMPLATE_ADDITIONAL_LABELS="${KUBERNETES_SECRET_TEMPLATE_ADDITIONAL_LABELS:-}"
KUBERNETES_SECRET_TEMPLATE_ADDITIONAL_ANNOTATIONS="${KUBERNETES_SECRET_TEMPLATE_ADDITIONAL_ANNOTATIONS:-}"
