#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# kubernetes-workload.bash - Default values for Kubernetes workload generation
#
# Source this file to get consistent defaults for workload-related variables.
# These are shared across all workload types (Deployment, StatefulSet, etc.)
#
# Variables are set with defaults only if not already set, so callers can
# override by setting values before sourcing this file.
#

# shellcheck disable=SC2034  # Variables used by sourcing scripts

# =============================================================================
# Apply defaults to long-form variables (collision-safe)
# =============================================================================

# Workload type (deployment, statefulset, daemonset, job, cronjob)
KUBERNETES_WORKLOAD_TYPE="${KUBERNETES_WORKLOAD_TYPE:-deployment}"

# Naming and paths
KUBERNETES_WORKLOAD_NAME_SUFFIX="${KUBERNETES_WORKLOAD_NAME_SUFFIX:-}"
KUBERNETES_WORKLOAD_COMBINED_SUB_PATH="${KUBERNETES_WORKLOAD_COMBINED_SUB_PATH:-}"

# Replicas: empty → token, "NO" → omit for HPA, other → pass through (numeric or custom token)
KUBERNETES_WORKLOAD_REPLICAS="${KUBERNETES_WORKLOAD_REPLICAS:-}"
KUBERNETES_WORKLOAD_REVISION_HISTORY_LIMIT="${KUBERNETES_WORKLOAD_REVISION_HISTORY_LIMIT:-10}"
KUBERNETES_WORKLOAD_MIN_READY_SECONDS="${KUBERNETES_WORKLOAD_MIN_READY_SECONDS:-0}"

# Container command and args (space-separated, respects quotes like shell)
# Example: '/bin/sh -c' and '"echo hello && sleep 10"'
KUBERNETES_WORKLOAD_CONTAINER_COMMAND="${KUBERNETES_WORKLOAD_CONTAINER_COMMAND:-}"
KUBERNETES_WORKLOAD_CONTAINER_ARGS="${KUBERNETES_WORKLOAD_CONTAINER_ARGS:-}"

# Node selector (comma-separated key=value pairs)
KUBERNETES_WORKLOAD_NODE_SELECTOR="${KUBERNETES_WORKLOAD_NODE_SELECTOR:-}"

# DNS policy (ClusterFirst, ClusterFirstWithHostNet, Default, None)
KUBERNETES_WORKLOAD_DNS_POLICY="${KUBERNETES_WORKLOAD_DNS_POLICY:-}"

# =============================================================================
# Convenience short names (for single-purpose generator scripts only)
# =============================================================================

# Workload type
WORKLOAD_TYPE="${KUBERNETES_WORKLOAD_TYPE}"

# Naming and paths
NAME_SUFFIX="${KUBERNETES_WORKLOAD_NAME_SUFFIX}"
COMBINED_SUB_PATH="${KUBERNETES_WORKLOAD_COMBINED_SUB_PATH}"

# Replicas
REPLICAS="${KUBERNETES_WORKLOAD_REPLICAS}"
REVISION_HISTORY_LIMIT="${KUBERNETES_WORKLOAD_REVISION_HISTORY_LIMIT}"
MIN_READY_SECONDS="${KUBERNETES_WORKLOAD_MIN_READY_SECONDS}"

# Image reference style
IMAGE_REFERENCE_STYLE="${KUBERNETES_WORKLOAD_IMAGE_REFERENCE_STYLE:-combined}"

# Container configuration
CONTAINER_PORT="${KUBERNETES_WORKLOAD_CONTAINER_PORT:-1024}"

# Container command and args (space-separated, respects quotes like shell)
# Example: '/bin/sh -c' and '"echo hello && sleep 10"'
CONTAINER_COMMAND="${KUBERNETES_WORKLOAD_CONTAINER_COMMAND}"
CONTAINER_ARGS="${KUBERNETES_WORKLOAD_CONTAINER_ARGS}"

# Security
READONLY_ROOT_FILESYSTEM="${KUBERNETES_WORKLOAD_READONLY_ROOT_FILESYSTEM:-true}"
SECCOMP_PROFILE="${KUBERNETES_WORKLOAD_SECCOMP_PROFILE:-DISABLED}"
AUTOMOUNT_SERVICE_ACCOUNT_TOKEN="${KUBERNETES_WORKLOAD_AUTOMOUNT_SERVICE_ACCOUNT_TOKEN:-false}"
IMAGE_PULL_SECRETS="${KUBERNETES_WORKLOAD_IMAGE_PULL_SECRETS:-ENABLED}"

# Resources
MEMORY="${KUBERNETES_WORKLOAD_RESOURCES_MEMORY:-10Mi}"
CPU_REQUEST="${KUBERNETES_WORKLOAD_RESOURCES_CPU_REQUEST:-100m}"
CPU_LIMIT="${KUBERNETES_WORKLOAD_RESOURCES_CPU_LIMIT:-}"
EPHEMERAL_STORAGE="${KUBERNETES_WORKLOAD_RESOURCES_EPHEMERAL_STORAGE:-10Mi}"

# Mounts
CONFIGMAP_MOUNT_PATH="${KUBERNETES_WORKLOAD_CONFIGMAP_MOUNT_PATH:-/configmap}"
SECRET_MOUNT_PATH="${KUBERNETES_WORKLOAD_SECRET_MOUNT_PATH:-/secret}"

# Environment variable refs from ConfigMap/Secret keys
CONFIGMAP_KEYS_FOR_ENV="${KUBERNETES_WORKLOAD_CONFIGMAP_KEYS_FOR_ENV:-}"
SECRET_KEYS_FOR_ENV="${KUBERNETES_WORKLOAD_SECRET_KEYS_FOR_ENV:-}"

# Termination and lifecycle
TERMINATION_GRACE_PERIOD_SECONDS="${KUBERNETES_WORKLOAD_TERMINATION_GRACE_PERIOD_SECONDS:-10}"
PRESTOP_COMMAND="${KUBERNETES_WORKLOAD_PRESTOP_COMMAND:-}"

# Affinity
AFFINITY_STRATEGY="${KUBERNETES_WORKLOAD_AFFINITY_STRATEGY:-spread-nodes-and-zones-ha}"

# Tolerations (JSON array)
TOLERATIONS="${KUBERNETES_WORKLOAD_TOLERATIONS:-}"

# Node selector (comma-separated key=value pairs)
NODE_SELECTOR="${KUBERNETES_WORKLOAD_NODE_SELECTOR}"

# DNS policy (ClusterFirst, ClusterFirstWithHostNet, Default, None)
DNS_POLICY="${KUBERNETES_WORKLOAD_DNS_POLICY}"

# Liveness probe
LIVENESS_CHECK_TYPE="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_CHECK_TYPE:-http-get}"
LIVENESS_INITIAL_DELAY_SECONDS="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_INITIAL_DELAY_SECONDS:-10}"
LIVENESS_PERIOD_SECONDS="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_PERIOD_SECONDS:-10}"
LIVENESS_TIMEOUT_SECONDS="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_TIMEOUT_SECONDS:-5}"
LIVENESS_FAILURE_THRESHOLD="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_FAILURE_THRESHOLD:-3}"
LIVENESS_HTTP_PATH="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_HTTP_PATH:-/liveness}"
LIVENESS_HTTP_SCHEME="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_HTTP_SCHEME:-HTTP}"
LIVENESS_TCP_PORT="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_TCP_PORT:-${CONTAINER_PORT}}"
LIVENESS_EXEC_COMMAND="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_EXEC_COMMAND:-}"
LIVENESS_GRPC_PORT="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_GRPC_PORT:-${CONTAINER_PORT}}"
LIVENESS_GRPC_SERVICE="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_GRPC_SERVICE:-}"
LIVENESS_TERMINATION_GRACE_PERIOD_SECONDS="${KUBERNETES_WORKLOAD_PROBE_LIVENESS_TERMINATION_GRACE_PERIOD_SECONDS:-}"

# Readiness probe
READINESS_CHECK_TYPE="${KUBERNETES_WORKLOAD_PROBE_READINESS_CHECK_TYPE:-http-get}"
READINESS_INITIAL_DELAY_SECONDS="${KUBERNETES_WORKLOAD_PROBE_READINESS_INITIAL_DELAY_SECONDS:-5}"
READINESS_PERIOD_SECONDS="${KUBERNETES_WORKLOAD_PROBE_READINESS_PERIOD_SECONDS:-5}"
READINESS_TIMEOUT_SECONDS="${KUBERNETES_WORKLOAD_PROBE_READINESS_TIMEOUT_SECONDS:-3}"
READINESS_FAILURE_THRESHOLD="${KUBERNETES_WORKLOAD_PROBE_READINESS_FAILURE_THRESHOLD:-3}"
READINESS_SUCCESS_THRESHOLD="${KUBERNETES_WORKLOAD_PROBE_READINESS_SUCCESS_THRESHOLD:-1}"
READINESS_HTTP_PATH="${KUBERNETES_WORKLOAD_PROBE_READINESS_HTTP_PATH:-/readiness}"
READINESS_HTTP_SCHEME="${KUBERNETES_WORKLOAD_PROBE_READINESS_HTTP_SCHEME:-HTTP}"
READINESS_TCP_PORT="${KUBERNETES_WORKLOAD_PROBE_READINESS_TCP_PORT:-${CONTAINER_PORT}}"
READINESS_EXEC_COMMAND="${KUBERNETES_WORKLOAD_PROBE_READINESS_EXEC_COMMAND:-}"
READINESS_GRPC_PORT="${KUBERNETES_WORKLOAD_PROBE_READINESS_GRPC_PORT:-${CONTAINER_PORT}}"
READINESS_GRPC_SERVICE="${KUBERNETES_WORKLOAD_PROBE_READINESS_GRPC_SERVICE:-}"

# Startup probe
STARTUP_CHECK_TYPE="${KUBERNETES_WORKLOAD_PROBE_STARTUP_CHECK_TYPE:-http-get}"
STARTUP_INITIAL_DELAY_SECONDS="${KUBERNETES_WORKLOAD_PROBE_STARTUP_INITIAL_DELAY_SECONDS:-0}"
STARTUP_PERIOD_SECONDS="${KUBERNETES_WORKLOAD_PROBE_STARTUP_PERIOD_SECONDS:-5}"
STARTUP_TIMEOUT_SECONDS="${KUBERNETES_WORKLOAD_PROBE_STARTUP_TIMEOUT_SECONDS:-3}"
STARTUP_FAILURE_THRESHOLD="${KUBERNETES_WORKLOAD_PROBE_STARTUP_FAILURE_THRESHOLD:-30}"
STARTUP_HTTP_PATH="${KUBERNETES_WORKLOAD_PROBE_STARTUP_HTTP_PATH:-/startup}"
STARTUP_HTTP_SCHEME="${KUBERNETES_WORKLOAD_PROBE_STARTUP_HTTP_SCHEME:-HTTP}"
STARTUP_TCP_PORT="${KUBERNETES_WORKLOAD_PROBE_STARTUP_TCP_PORT:-${CONTAINER_PORT}}"
STARTUP_EXEC_COMMAND="${KUBERNETES_WORKLOAD_PROBE_STARTUP_EXEC_COMMAND:-}"
STARTUP_GRPC_PORT="${KUBERNETES_WORKLOAD_PROBE_STARTUP_GRPC_PORT:-${CONTAINER_PORT}}"
STARTUP_GRPC_SERVICE="${KUBERNETES_WORKLOAD_PROBE_STARTUP_GRPC_SERVICE:-}"
STARTUP_TERMINATION_GRACE_PERIOD_SECONDS="${KUBERNETES_WORKLOAD_PROBE_STARTUP_TERMINATION_GRACE_PERIOD_SECONDS:-}"
