#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Quality check defaults
#
# shellcheck disable=SC2034  # Variables used by sourcing scripts

BLOCK_SLASHES="${BLOCK_SLASHES:-false}"
# Falls back to BLOCK_SLASHES for backwards compatibility
QC_BLOCK_SLASH_CONTAINING_BRANCHES="${QC_BLOCK_SLASH_CONTAINING_BRANCHES:-${BLOCK_SLASHES}}"
QC_BLOCK_DOUBLE_HYPHEN_CONTAINING_BRANCHES="${QC_BLOCK_DOUBLE_HYPHEN_CONTAINING_BRANCHES:-true}"
QC_REQUIRE_CONVENTIONAL_BRANCHES="${QC_REQUIRE_CONVENTIONAL_BRANCHES:-false}"
QC_REQUIRE_CONVENTIONAL_COMMITS="${QC_REQUIRE_CONVENTIONAL_COMMITS:-false}"
QC_BLOCK_CONVENTIONAL_COMMITS="${QC_BLOCK_CONVENTIONAL_COMMITS:-false}"
QC_BLOCK_DUPLICATE_COMMIT_MESSAGES="${QC_BLOCK_DUPLICATE_COMMIT_MESSAGES:-true}"
