#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# GitHub release defaults
#
# shellcheck disable=SC2034  # Variables used by sourcing scripts

GITHUB_RELEASE_ENABLED="${GITHUB_RELEASE_ENABLED:-true}"
GITHUB_RELEASE_SUBSTITUTED_FILES="${GITHUB_RELEASE_SUBSTITUTED_FILES:-}"
GITHUB_RELEASE_VERBATIM_FILES="${GITHUB_RELEASE_VERBATIM_FILES:-}"
GITHUB_RELEASE_NOTES="${GITHUB_RELEASE_NOTES:-}"
GITHUB_RELEASE_ADD_VERSION_TO_FILENAMES="${GITHUB_RELEASE_ADD_VERSION_TO_FILENAMES:-true}"
