# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Docker Build Dockerfile'
description: 'Builds a Docker image from a Dockerfile with token substitution (build only, push handled by docker-push-all)'

inputs:
  # Build output
  output-sub-path:
    description: 'Build output directory (relative)'
    required: false
    default: 'target'
  # Docker build options
  dockerfile-substitution-files:
    description: 'Comma-separated list of files to perform token substitution on (relative to dockerfile-sub-path and docker-context-sub-path)'
    required: false
    default: 'Dockerfile'
  dockerfile-sub-path:
    description: 'Directory containing Dockerfile, relative to repo root.'
    required: false
    default: 'src/docker'
  dockerfile-squash:
    description: 'Enable --squash (requires experimental mode)'
    required: false
    default: 'true'
  dockerfile-squash-allow-unavailable:
    description: 'Allow build without squash if unavailable (default: false - fail if squash unavailable)'
    required: false
    default: 'false'
  dockerfile-no-cache:
    description: 'Disable layer caching for reproducible builds'
    required: false
    default: 'true'
  # Token substitution
  token-delimiter-style:
    description: 'Token delimiter syntax for variables (shell, mustache, helm, erb, github-actions, blade, stringtemplate, ognl, t4, swift)'
    required: false
    default: 'shell'
  token-name-style:
    description: 'Case style for token names (UPPER_SNAKE, lower_snake, lower-kebab, UPPER-KEBAB, camelCase, PascalCase, lower.dot, UPPER.DOT)'
    required: false
    default: 'PascalCase'
  token-name-validation:
    description: 'How to validate user token names (MATCH = must match token-name-style, ALL = accept any valid name)'
    required: false
    default: 'MATCH'
  allow-builtin-token-override:
    description: 'Allow user tokens to override built-in tokens (for template/reusable projects)'
    required: false
    default: 'false'
  config-sub-path:
    description: 'Directory containing user-defined token files (relative)'
    required: false
    default: 'src/config'
  config-value-trailing-newline:
    description: 'How to handle trailing newlines in config values (strip-for-single-line, preserve-all, always-strip-one-newline)'
    required: false
    default: 'strip-for-single-line'

  # Action-specific inputs (passed from workflow/version generator)
  docker-target-registry:
    description: 'Target container registry (pre-resolved by workflow)'
    required: true
  docker-target-base-path:
    description: 'Path between registry and image name (pre-resolved by workflow)'
    required: true
  docker-image-name:
    description: 'Image name (from version generator docker-image-name)'
    required: true
  docker-tag:
    description: 'Tag for target image (from version generator docker-tag)'
    required: true
  version:
    description: 'Version number (from version generator, passed as build arg)'
    required: true
  project-name:
    description: 'Project name (from version generator, passed as build arg)'
    required: true
  is-release:
    description: 'Whether this is a release build (from version generator)'
    required: true

outputs:
  docker-target-image-full-uri:
    description: 'Full target image reference'
    value: ${{ steps.build.outputs.DOCKER_TARGET_IMAGE_FULL_URI }}
  docker-target-registry:
    description: 'Target registry (pass-through for downstream)'
    value: ${{ inputs.docker-target-registry }}
  docker-target-base-path:
    description: 'Target base path (pass-through for downstream)'
    value: ${{ inputs.docker-target-base-path }}

runs:
  using: 'composite'
  steps:
    - name: Build image
      id: build
      shell: bash
      env:
        LOG_ERROR_PREFIX: '::error::'
        LOG_WARNING_PREFIX: '::warning::'
        DOCKER_TARGET_REGISTRY: ${{ inputs.docker-target-registry }}
        DOCKER_TARGET_BASE_PATH: ${{ inputs.docker-target-base-path }}
        DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
        VERSION: ${{ inputs.version }}
        PROJECT_NAME: ${{ inputs.project-name }}
        IS_RELEASE: ${{ inputs.is-release }}
        DOCKERFILE_SUB_PATH: ${{ inputs.dockerfile-sub-path }}
        DOCKERFILE_SUBSTITUTION_FILES: ${{ inputs.dockerfile-substitution-files }}
        OUTPUT_SUB_PATH: ${{ inputs.output-sub-path }}
        DOCKERFILE_SQUASH: ${{ inputs.dockerfile-squash }}
        DOCKERFILE_SQUASH_ALLOW_UNAVAILABLE: ${{ inputs.dockerfile-squash-allow-unavailable }}
        BUILD_MODE: build_server
        DOCKERFILE_NO_CACHE: ${{ inputs.dockerfile-no-cache }}
        TOKEN_DELIMITER_STYLE: ${{ inputs.token-delimiter-style }}
        TOKEN_NAME_STYLE: ${{ inputs.token-name-style }}
        TOKEN_NAME_VALIDATION: ${{ inputs.token-name-validation }}
        CONFIG_SUB_PATH: ${{ inputs.config-sub-path }}
        ALLOW_BUILTIN_TOKEN_OVERRIDE: ${{ inputs.allow-builtin-token-override }}
        CONFIG_VALUE_TRAILING_NEWLINE: ${{ inputs.config-value-trailing-newline }}
      run: "${{ github.action_path }}/../../scripts/main/docker-build-dockerfile"
