# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: 'Docker Build Dockerfile'
description: 'Builds a Docker image from a Dockerfile (build only, use docker-push to push)'
author: 'kube-kaptain'

inputs:
  target-registry:
    description: 'Target container registry'
    required: false
    default: 'ghcr.io'
  target-base-path:
    description: 'Path between registry and image name (leave empty for GHCR auto-detect)'
    required: false
    default: ''
  target-image-name:
    description: 'Target image name (from version generator docker-image-name)'
    required: true
  docker-tag:
    description: 'Tag for target image (from version generator docker-tag)'
    required: true
  version:
    description: 'Version number (from version generator, passed as build arg)'
    required: true
  project-name:
    description: 'Project name (from version generator, passed as build arg)'
    required: true
  dockerfile-sub-path:
    description: 'Directory containing Dockerfile, relative (also used as build context)'
    required: false
    default: 'src/docker'
  squash:
    description: 'Enable --squash (requires experimental mode)'
    required: false
    default: 'true'
  no-cache:
    description: 'Disable layer caching for reproducible builds (default: true)'
    required: false
    default: 'true'
  confirm-image-doesnt-exist:
    description: 'Fail if target image already exists in registry'
    required: false
    default: 'true'

outputs:
  target-image-full-uri:
    description: 'Full target image reference (for passing to docker-push)'
    value: ${{ steps.build.outputs.TARGET_IMAGE_FULL_URI }}
  target-registry:
    description: 'Resolved target registry (for passing to manifest-package)'
    value: ${{ steps.resolve.outputs.target-registry }}
  target-base-path:
    description: 'Computed target base path (for passing to manifest-package)'
    value: ${{ steps.resolve.outputs.target-base-path }}

runs:
  using: 'composite'
  steps:
    - name: Resolve target registry and base path
      id: resolve
      uses: ./.github/buildon-github-actions/src/actions/resolve-target-registry-and-base-path
      with:
        target-registry: ${{ inputs.target-registry }}
        target-base-path: ${{ inputs.target-base-path }}

    - name: Build image
      id: build
      shell: bash
      env:
        LOG_ERROR_PREFIX: '::error::'
        TARGET_REGISTRY: ${{ steps.resolve.outputs.target-registry }}
        TARGET_BASE_PATH: ${{ steps.resolve.outputs.target-base-path }}
        TARGET_IMAGE_NAME: ${{ inputs.target-image-name }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
        VERSION: ${{ inputs.version }}
        PROJECT_NAME: ${{ inputs.project-name }}
        DOCKERFILE_SUB_PATH: ${{ inputs.dockerfile-sub-path }}
        SQUASH: ${{ inputs.squash }}
        NO_CACHE: ${{ inputs.no-cache }}
        CONFIRM_IMAGE_DOESNT_EXIST: ${{ inputs.confirm-image-doesnt-exist }}
      run: "${{ github.action_path }}/../../scripts/main/docker-build-dockerfile"
