# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: Docker Registry Logins
description: Authenticate to container registries (GHCR by default, configure others as needed)

inputs:
  secret-method:
    description: 'Secret retrieval method (github, env)'
    required: false
    default: 'github'
  config:
    description: 'YAML config for registry logins (registry URL as key)'
    required: false
    default: ''
  secrets-json:
    description: 'JSON object containing secret values keyed by secret name'
    required: false
    default: '{}'
  docker-target-registry:
    description: 'Target registry to validate is configured (optional, but recommended for push workflows)'
    required: false
    default: ''
  # Container runtime
  image-build-command:
    description: 'Container runtime command (podman or docker)'
    required: true

runs:
  using: composite
  steps:
    - name: Build config with GHCR default
      id: config
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        GH_ACTOR: ${{ github.actor }}
      run: |
        USER_CONFIG='${{ inputs.config }}'

        # GHCR default config block with token and actor injected
        GHCR_DEFAULT="ghcr.io:
          type: github-token
          token: $GH_TOKEN
          actor: $GH_ACTOR"

        # Check if user provided config and if it includes ghcr.io
        if [[ -z "$USER_CONFIG" ]]; then
          # No user config - use GHCR default only
          FINAL_CONFIG="$GHCR_DEFAULT"
        elif echo "$USER_CONFIG" | yq -e 'has("ghcr.io")' > /dev/null 2>&1; then
          # User config includes ghcr.io - use as-is
          FINAL_CONFIG="$USER_CONFIG"
        else
          # User config without ghcr.io - prepend GHCR default
          FINAL_CONFIG="$GHCR_DEFAULT
        $USER_CONFIG"
        fi

        # Validate docker-target-registry is configured (if provided)
        TARGET_REGISTRY='${{ inputs.docker-target-registry }}'
        if [[ -n "$TARGET_REGISTRY" ]]; then
          if ! echo "$FINAL_CONFIG" | yq -e "has(\"$TARGET_REGISTRY\")" > /dev/null 2>&1; then
            echo "::error::Target registry '$TARGET_REGISTRY' is not configured in docker-registry-logins."
            echo "::error::Add '$TARGET_REGISTRY' to your docker-registry-logins config."
            exit 1
          fi
        fi

        # Export for next step
        {
          echo 'FINAL_CONFIG<<EOF'
          echo "$FINAL_CONFIG"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"

    - name: Run docker-registry-logins
      shell: bash
      run: ${{ github.action_path }}/../../scripts/main/docker-registry-logins
      env:
        SECRET_METHOD: ${{ inputs.secret-method }}
        CONFIG: ${{ steps.config.outputs.FINAL_CONFIG }}
        SECRETS_JSON: ${{ inputs.secrets-json }}
        LOG_ERROR_PREFIX: '::error::'
        LOG_ERROR_SUFFIX: ''
        LOG_GROUP_START: '::group::'
        IMAGE_BUILD_COMMAND: ${{ inputs.image-build-command }}
        LOG_GROUP_END: ''
