# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Change Source Note Write'
description: 'Writes merge candidate metadata as a git note for release tracking'

inputs:
  # Change source note
  change-source-note-enabled:
    description: 'Write a git note with merge candidate metadata for release tracking'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Write change source note
      id: write
      shell: bash
      env:
        BUILD_PLATFORM: github-actions
        BUILD_PLATFORM_LOG_PROVIDER: github-actions
        CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}
        MERGE_CANDIDATE_CREATOR: ${{ github.event.pull_request.user.login }}
      run: "${{ github.action_path }}/../../scripts/main/change-source-note-write"
