# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.

name: Custom Registry Logins

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@1.1.8
    permissions:
      contents: write
      packages: write
      checks: write
    secrets:
      docker-registry-logins-secrets: |
        DOCKERHUB_USER=${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}
        HARBOR_USER=${{ secrets.HARBOR_USER }}
        HARBOR_PASS=${{ secrets.HARBOR_PASS }}
