# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.
#
# Basic Quality and Versioning
#
# Standard build setup:
# - PRs: Enforce quality standards (branch names, commit messages, rebase)
# - Push to main: Generate and push version tag
#
# Copy this to .github/workflows/build.yaml in your repo.

name: Basic Quality Checks And Tag 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/basic-quality-and-versioning.yaml@1.0.2
    permissions:
      contents: write
