# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.
#
# Basic Quality and Versioning
#
# Standard build setup:
# - PRs: Enforce quality standards (branch names, commit messages, rebase)
# - Push to main: Generate and push version tag
#
# Copy this to .github/workflows/build.yaml in your repo.

name: Basic Quality Checks And Tag 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/basic-quality-and-versioning.yaml@1.0.40
    permissions:
      contents: write
      checks: write

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ All Available Options                                                     │
# │ Uncomment and add to the job above as needed                              │
# └───────────────────────────────────────────────────────────────────────────┘

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Branch Configuration                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       release-branch: 'master'  # Default is main, use whatever you want
#       additional-release-branches: 'main-1.x,main-2.x'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Quality Checks                                                          │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       qc-block-slash-containing-branches: true           # Default is false
#       qc-block-double-hyphen-containing-branches: false  # Default is true
#       qc-require-conventional-branches: true             # Default is false
#       qc-require-conventional-commits: true              # Default is false
#       qc-block-conventional-commits: true                # Default is false

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Configuration                                                   │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       tag-version-max-parts: 2  # Default is 3, but any positive integer 1 or higher is valid

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Calculation Strategy                                            │
# └─────────────────────────────────────────────────────────────────────────┘
# Default: git-auto-closest-highest (finds closest tag, increments it)
# Alternative: file-pattern-match (extracts version from a file)
#
#     with:
#       tag-version-calculation-strategy: 'file-pattern-match'
#       tag-version-pattern-type: 'dockerfile-env-kubectl'  # default
#       dockerfile-sub-path: 'src/docker'  # where to find Dockerfile

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Test Injection                                                          │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       hook-pre-tagging-tests-script-sub-path: 'bin/run-tests.bash'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Token Substitution                                                      │
# └─────────────────────────────────────────────────────────────────────────┘
# Tokens like ${Version} are replaced in release files during processing.
# Add custom tokens by creating files in src/config/ (e.g., src/config/MyToken)
#
#     with:
#       token-delimiter-style: 'mustache'  # Default is 'shell' (${Token})
#       token-name-style: 'UPPER_SNAKE'       # Default is 'PascalCase'
#       token-name-validation: 'ALL'          # Default is 'MATCH' (must match style)
#       config-sub-path: 'config'             # Default is 'src/config'
#       allow-builtin-token-override: true    # Default is false
#       config-value-trailing-newline: 'preserve-all'  # Default is 'strip-for-single-line'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ GitHub Release                                                          │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       github-release-enabled: true                           # Default is true
#       github-release-substituted-files: 'dist/output.txt'    # Tokens replaced
#       github-release-verbatim-files: 'CHANGELOG.md'          # Copied as-is
#       github-release-notes: 'Custom release notes'           # Leave empty for auto
#       github-release-add-version-to-filenames: false         # Default is true

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Output Configuration                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       output-sub-path: 'build'  # Default is 'target'
