# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.
#
# Docker Build Retag - Base Path
#
# Many registries use base paths in addition to the normal image name for projects or teams.
# Use target-base-path to add a prefix between the registry and image name.
#
# Result: <registry>/<base-path>/<docker-image-name>:<tag>
#
# Copy this to .github/workflows/build.yaml in your repo.

name: Docker Build Retag

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  retag:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-retag.yaml@1.0.11
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      source-registry: docker.io
      source-image-name: library/redis
      source-tag: '7.4'
      target-base-path: my-team/vendored # This is what you set how you need it

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ All Available Options                                                     │
# │ Uncomment and add to the job above as needed                              │
# └───────────────────────────────────────────────────────────────────────────┘

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Source Image (REQUIRED)                                                 │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       source-registry: docker.io
#       source-image-name: library/alpine
#       source-tag: '3.21'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Target Registry                                                         │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       target-registry: 'myregistry.example.com'  # ecr, gcr, harbor, nexus
#       target-base-path: 'my-org/base-images'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Branch Configuration                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       default-branch: 'master'  # Default is main, use whatever you want
#       additional-release-branches: 'main-1.x,main-2.x'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Quality Checks                                                          │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       block-slashes: true                  # Default is false
#       block-double-hyphens: false          # Default is true
#       require-conventional-branches: true  # Default is false
#       require-conventional-commits: true   # Default is false
#       block-conventional-commits: true     # Default is false

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Configuration                                                   │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       max-version-parts: 2  # Default is 3, but any positive integer 1 or higher is valid

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Registry Credentials                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
# See docker-registry-logins-*.yaml examples for authentication options
