# SPDX-License-Identifier: CC0-1.0
#
# Docker Registry Logins - Explicit JSON secrets
#
# Alternative approach: construct the JSON object yourself and pass it as
# docker-registry-logins-secrets. More verbose than declaring secret names,
# but works without secrets: inherit and shows exactly what gets passed.

name: Build with Registry Logins (Explicit)
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@1.0.64
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      docker-registry-logins: |
        # Docker Hub - private base images
        docker.io:
          type: username-password
          username-secret: DOCKERHUB_USERNAME
          password-secret: DOCKERHUB_PASSWORD

        # AWS ECR - shared libraries
        111111111111.dkr.ecr.us-east-1.amazonaws.com:
          type: aws-ecr
          access-key-id-secret: ECR_ACCESS_KEY_ID
          secret-access-key-secret: ECR_SECRET_ACCESS_KEY
          region: us-east-1
    secrets:
      docker-registry-logins-secrets: |
        {
          "DOCKERHUB_USERNAME": "${{ secrets.DOCKERHUB_USERNAME }}",
          "DOCKERHUB_PASSWORD": "${{ secrets.DOCKERHUB_PASSWORD }}",
          "ECR_ACCESS_KEY_ID": "${{ secrets.ECR_ACCESS_KEY_ID }}",
          "ECR_SECRET_ACCESS_KEY": "${{ secrets.ECR_SECRET_ACCESS_KEY }}"
        }

# Required secrets in repository settings:
#   DOCKERHUB_USERNAME
#   DOCKERHUB_PASSWORD
#   ECR_ACCESS_KEY_ID
#   ECR_SECRET_ACCESS_KEY

# GHCR uses GITHUB_TOKEN automatically (ghcr.io not in config)
