# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.
#
# Docker Build Retag - Base Path
#
# Many registries use base paths in addition to the normal image name for projects or teams.
# Use target-base-path to add a prefix between the registry and image name.
#
# Result: <registry>/<base-path>/<docker-image-name>:<tag>
#
# Copy this to .github/workflows/build.yaml in your repo.

name: Docker Build Retag

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  retag:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-retag.yaml@1.0.39
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      docker-source-registry: docker.io
      docker-source-base-path: library
      docker-source-image-name: redis
      docker-source-tag: '7.4'
      docker-target-base-path: my-team/vendored  # This is what you set how you need it

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ All Available Options                                                     │
# │ Uncomment and add to the job above as needed                              │
# └───────────────────────────────────────────────────────────────────────────┘

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Source Image (REQUIRED)                                                 │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       docker-source-registry: docker.io
#       docker-source-base-path: library      # Optional, if upstream uses a base path
#       docker-source-image-name: alpine
#       docker-source-tag: '3.21'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Target Registry                                                         │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       docker-target-registry: 'myregistry.example.com'  # ecr, gcr, harbor, nexus
#       docker-target-base-path: 'my-org/base-images'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Branch Configuration                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       release-branch: 'master'  # Default is main, use whatever you want
#       additional-release-branches: 'main-1.x,main-2.x'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Quality Checks                                                          │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       block-slash-containing-branches: true           # Default is false
#       block-double-hyphen-containing-branches: false  # Default is true
#       require-conventional-branches: true             # Default is false
#       require-conventional-commits: true              # Default is false
#       block-conventional-commits: true                # Default is false

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Configuration                                                   │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       max-version-parts: 2  # Default is 3, but any positive integer 1 or higher is valid

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Calculation Strategy                                            │
# └─────────────────────────────────────────────────────────────────────────┘
# Default: git-auto-closest-highest (finds closest tag, increments it)
# Alternative: file-pattern-match (extracts version from a file)
#
# For retag workflows, use retag-workflow-source-tag to derive version from
# the source-tag input in this build.yaml file:
#     with:
#       tag-version-calculation-strategy: 'file-pattern-match'
#       tag-version-pattern-type: 'retag-workflow-source-tag'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Test Injection                                                          │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       pre-tagging-tests-script-sub-path: 'bin/run-tests.bash'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Token Substitution                                                      │
# └─────────────────────────────────────────────────────────────────────────┘
# Tokens like ${Version} are replaced in release files during processing.
# Add custom tokens by creating files in src/config/ (e.g., src/config/MyToken)
#
#     with:
#       substitution-token-style: 'mustache'  # Default is 'shell' (${Token})
#       token-name-style: 'UPPER_SNAKE'       # Default is 'PascalCase'
#       token-name-validation: 'ALL'          # Default is 'MATCH' (must match style)
#       config-sub-path: 'config'             # Default is 'src/config'
#       allow-builtin-token-override: true    # Default is false
#       config-value-trailing-newline: 'preserve-all'  # Default is 'strip-for-single-line'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ GitHub Release                                                          │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       github-release-enabled: true                           # Default is true
#       github-release-substituted-files: 'dist/output.txt'    # Tokens replaced
#       github-release-verbatim-files: 'CHANGELOG.md'          # Copied as-is
#       github-release-notes: 'Custom release notes'           # Leave empty for auto
#       github-release-add-version-to-filenames: false         # Default is true

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Output Configuration                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       output-sub-path: 'build'  # Default is 'target'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Registry Credentials                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
# See docker-registry-logins-*.yaml examples for authentication options
