# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.
#
# GitHub Release Options
#
# All workflows that include versions-and-naming create GitHub releases by default.
# This example shows how to disable releases or customize the release notes.
#
# Release notes automatically include relevant URIs:
# - Docker workflows: Docker image URI
# - Kubernetes app workflows: Docker image + manifests image URIs

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ Disable GitHub Release                                                    │
# └───────────────────────────────────────────────────────────────────────────┘
# Set github-release-enabled to false to skip creating a release.
# Useful for intermediate builds or when you manage releases separately.

name: Build Without Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@1.0.71
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      github-release-enabled: false

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ Custom Release Notes                                                      │
# └───────────────────────────────────────────────────────────────────────────┘
# Fully override the default release notes with custom content.
# Default notes follow the format:
#   "Automatic {type} release for version {version} of {project} by Kaptain build script."
#   followed by relevant URIs (Docker Image, Manifests Image, etc.)
#
# Option 1: Inline string (short notes)
#   with:
#     github-release-notes: |
#       ## What's New
#       - Feature X
#       - Bug fix Y
#
#       ## Breaking Changes
#       - Changed Z
#
# Option 2: Notes from a file (longer or generated notes)
#   with:
#     github-release-notes-file: 'RELEASE_NOTES.md'  # Relative to output-sub-path
#
# These two options are mutually exclusive - set one or the other, not both.
# If neither is set, GitHub auto-generates notes from commit history.

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ Additional Release Files                                                  │
# └───────────────────────────────────────────────────────────────────────────┘
# Attach extra files to the release (space-separated). Two options:
# - github-release-substituted-files: Token substitution + version suffix
# - github-release-verbatim-files: Copied as-is with version suffix only
#
# Both lists get version suffix (e.g., file.yaml -> file-1.2.3.yaml).
# Use github-release-add-version-to-filenames: false to disable the suffix.
#
# Kubernetes app workflows automatically include the manifests zip.
#
#   with:
#     github-release-substituted-files: 'template.yaml'  # Tokens replaced
#     github-release-verbatim-files: 'CHANGELOG.md LICENSE'  # Copied as-is

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ Combined Example                                                          │
# └───────────────────────────────────────────────────────────────────────────┘
#
# jobs:
#   build:
#     uses: kube-kaptain/buildon-github-actions/.github/workflows/kubernetes-app-docker-dockerfile.yaml@1.0.71
#     permissions:
#       contents: write
#       packages: write
#       checks: write
#     with:
#       github-release-notes-file: 'RELEASE_NOTES.md'
#       github-release-substituted-files: 'docs/MIGRATION.md'
