# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.
#
# Optional Test Script Injection
#
# Shows how to add custom test scripts to workflows that support them.
#
# Available inputs to configure test hooks and workflow support guidance:
# - pre-tagging-tests-script-sub-path:  Runs before version tagging in almost all workflows
# - post-docker-tests-script-sub-path:  Runs after docker build in any workflow that includes a docker build (not retag)
# - post-package-tests-script-sub-path: Runs after manifest packaging has occurred
#
# Scripts must be:
# - Located under .github/ (the input is a sub-path from there)
# - Executable (chmod +x)
#
# Available variables depends on which workflow - please check the docs/ folder for the workflow you're using
#
# Copy this to .github/workflows/build.yaml in your repo.

name: Build with Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/kubernetes-app-docker-dockerfile.yaml@1.0.11
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      manifests-repo-provider-type: docker
      pre-tagging-tests-script-sub-path: bin/run-tests.bash
      post-docker-tests-script-sub-path: bin/test-container.bash
      post-package-tests-script-sub-path: bin/test-manifests.bash

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ All Available Options                                                     │
# │ Uncomment and add to the job above as needed                              │
# └───────────────────────────────────────────────────────────────────────────┘

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Dockerfile Configuration                                                │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       dockerfile-sub-path: 'docker'  # 'build', '.'
#       squash: false  # true
#       no-cache: false  # true

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Target Registry                                                         │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       docker-target-registry: 'myregistry.example.com'  # ecr, gcr, harbor, nexus
#       docker-target-base-path: 'my-team/images'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Branch Configuration                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       default-branch: 'master'  # Default is main, use whatever you want
#       additional-release-branches: 'main-1.x,main-2.x'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Quality Checks                                                          │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       block-slash-containing-branches: true           # Default is false
#       block-double-hyphen-containing-branches: false  # Default is true
#       require-conventional-branches: true             # Default is false
#       require-conventional-commits: true              # Default is false
#       block-conventional-commits: true                # Default is false

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Configuration                                                   │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       max-version-parts: 2  # Default is 3, but any positive integer 1 or higher is valid

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Calculation Strategy                                            │
# └─────────────────────────────────────────────────────────────────────────┘
# Default: git-auto-closest-highest (finds closest tag, increments it)
# Alternative: file-pattern-match (extracts version from a file)
#
#     with:
#       tag-version-calculation-strategy: 'file-pattern-match'
#       tag-version-pattern-type: 'dockerfile-env-kubectl'  # default
#       # dockerfile-sub-path is shared with docker build config above

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Test Injection                                                          │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       pre-tagging-tests-script-sub-path: 'bin/run-tests.bash'
#       post-docker-tests-script-sub-path: 'bin/test-container.bash'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Registry Credentials                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
# See docker-registry-logins-*.yaml examples for authentication options
