# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.
#
# Versions and Naming Only
#
# Automatic version tagging without PR quality checks.
# Use this when you have your own quality checks or don't need them.
#
# Copy this to .github/workflows/build.yaml in your repo.

name: Version Tag

on:
  push:
    branches: [main]

jobs:
  version:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/versions-and-naming.yaml@1.0.11
    permissions:
      contents: write
      checks: write

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ All Available Options                                                     │
# │ Uncomment and add to the job above as needed                              │
# └───────────────────────────────────────────────────────────────────────────┘

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Branch Configuration                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       release-branch: 'master'  # Default is main, use whatever you want
#       additional-release-branches: 'main-1.x,main-2.x'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Configuration                                                   │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       max-version-parts: 2  # Default is 3, but any positive integer 1 or higher is valid

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Calculation Strategy                                            │
# └─────────────────────────────────────────────────────────────────────────┘
# Default: git-auto-closest-highest (finds closest tag, increments it)
# Alternative: file-pattern-match (extracts version from a file)
#
#     with:
#       tag-version-calculation-strategy: 'file-pattern-match'
#       tag-version-pattern-type: 'dockerfile-env-kubectl'  # default
#       dockerfile-sub-path: 'src/docker'  # where to find Dockerfile
#
# Pattern types with defaults:
#   dockerfile-env-kubectl: src/docker/Dockerfile, ENV KUBECTL_VERSION=x.y.z
#   retag-workflow-source-tag: .github/workflows/build.yaml, docker-source-tag: x.y.z
#   custom: requires all inputs below
#
# Custom pattern example:
#     with:
#       tag-version-calculation-strategy: 'file-pattern-match'
#       tag-version-pattern-type: 'custom'
#       tag-version-source-sub-path: 'src/config'
#       tag-version-source-file-name: 'version.txt'
#       tag-version-source-custom-pattern: '^VERSION=([0-9]+\.[0-9]+\.[0-9]+)$'
