# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.
#
# Versions and Naming Only
#
# Automatic version tagging without PR quality checks.
# Use this when you have your own quality checks or don't need them.
#
# Copy this to .github/workflows/build.yaml in your repo.

name: Version Tag

on:
  push:
    branches: [main]

jobs:
  version:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/versions-and-naming.yaml@1.0.11
    permissions:
      contents: write
      checks: write

# ┌───────────────────────────────────────────────────────────────────────────┐
# │ All Available Options                                                     │
# │ Uncomment and add to the job above as needed                              │
# └───────────────────────────────────────────────────────────────────────────┘

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Branch Configuration                                                    │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       default-branch: 'master'  # Default is main, use whatever you want
#       additional-release-branches: 'main-1.x,main-2.x'

# ┌─────────────────────────────────────────────────────────────────────────┐
# │ Version Configuration                                                   │
# └─────────────────────────────────────────────────────────────────────────┘
#     with:
#       max-version-parts: 2  # Default is 3, but any positive integer 1 or higher is valid
