# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.

name: Multi-Registry Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@1.1.19
    permissions:
      contents: write
      packages: write
      checks: write
    secrets:
      docker-registry-logins-secrets: |
        ECR_USER_EAST=${{ secrets.ECR_USER_EAST }}
        ECR_TOKEN_EAST=${{ secrets.ECR_TOKEN_EAST }}
