# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Resolve Target Registry and Base Path'
description: 'Resolves target registry (defaults to ghcr.io) and computes base path (auto-detects org for GHCR)'

inputs:
  # Docker registry logins
  docker-registry-logins:
    description: 'YAML config for Docker registry logins (registry URL as key)'
    required: false
    default: ''
  # Docker target config
  docker-target-registry:
    description: 'Target container registry domain (defaults to ghcr.io on gh actions)'
    required: false
    default: ''
  docker-target-base-path:
    description: 'Path between registry and image name (defaults to lower cased org name on gh actions)'
    required: false
    default: ''
  # Docker push targets
  docker-push-targets:
    description: 'JSON array of additional push targets [{registry, base-path?}]'
    required: false
    default: ''

outputs:
  docker-target-registry:
    description: 'Resolved target registry'
    value: ${{ steps.resolve.outputs.docker-target-registry }}
  docker-target-base-path:
    description: 'Computed target base path'
    value: ${{ steps.resolve.outputs.docker-target-base-path }}

runs:
  using: 'composite'
  steps:
    - name: Resolve target registry and base path
      id: resolve
      shell: bash
      run: |
        # Use provided registry or default to ghcr.io
        if [[ -n "${{ inputs.docker-target-registry }}" ]]; then
          RESOLVED_REGISTRY="${{ inputs.docker-target-registry }}"
        else
          RESOLVED_REGISTRY="ghcr.io"
        fi
        echo "docker-target-registry=$RESOLVED_REGISTRY" >> "$GITHUB_OUTPUT"

        # Auto-set base path for GHCR if not explicitly provided
        # Note: GHCR requires lowercase paths, so we lowercase the org name
        if [[ "$RESOLVED_REGISTRY" == "ghcr.io" && -z "${{ inputs.docker-target-base-path }}" ]]; then
          OWNER="${{ github.repository_owner }}"
          echo "docker-target-base-path=${OWNER,,}" >> "$GITHUB_OUTPUT"
        else
          echo "docker-target-base-path=${{ inputs.docker-target-base-path }}" >> "$GITHUB_OUTPUT"
        fi
