# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.

# This is a minimum example with no overrides, extend as needed
apiVersion: kaptain.org/1.22
kind: kubernetes-app-manifests-only
