# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Kubernetes Manifests Package'
description: 'Packages Kubernetes manifests into a zip with variable substitution'

inputs:
  # Action-specific inputs
  project-name:
    description: 'Project name for output naming'
    required: true
  version:
    description: 'Version for output naming'
    required: true

  # Build output
  output-sub-path:
    description: 'Build output directory (relative)'
    required: false
    default: 'target'
  # Token substitution
  token-delimiter-style:
    description: 'Token delimiter syntax for variables (shell, mustache, helm, erb, github-actions, blade, stringtemplate, ognl, t4, swift)'
    required: false
    default: 'shell'
  token-name-style:
    description: 'Case style for token names (UPPER_SNAKE, lower_snake, lower-kebab, UPPER-KEBAB, camelCase, PascalCase, lower.dot, UPPER.DOT)'
    required: false
    default: 'PascalCase'
  token-name-validation:
    description: 'How to validate user token names (MATCH = must match token-name-style, ALL = accept any valid name)'
    required: false
    default: 'MATCH'
  allow-builtin-token-override:
    description: 'Allow user tokens to override built-in tokens (for template/reusable projects)'
    required: false
    default: 'false'
  config-sub-path:
    description: 'Directory containing user-defined token files (relative)'
    required: false
    default: 'src/config'
  config-value-trailing-newline:
    description: 'How to handle trailing newlines in config values (strip-for-single-line, preserve-all, always-strip-one-newline)'
    required: false
    default: 'strip-for-single-line'

outputs:
  manifests-zip-sub-path:
    description: 'Directory containing the zip file (relative)'
    value: ${{ steps.package.outputs.MANIFESTS_ZIP_SUB_PATH }}
  manifests-zip-file-name:
    description: 'Filename of the zip'
    value: ${{ steps.package.outputs.MANIFESTS_ZIP_FILE_NAME }}

runs:
  using: 'composite'
  steps:
    - name: Package manifests
      id: package
      shell: bash
      env:
        LOG_ERROR_PREFIX: '::error::'
        PROJECT_NAME: ${{ inputs.project-name }}
        VERSION: ${{ inputs.version }}
        OUTPUT_SUB_PATH: ${{ inputs.output-sub-path }}
        TOKEN_DELIMITER_STYLE: ${{ inputs.token-delimiter-style }}
        CONFIG_VALUE_TRAILING_NEWLINE: ${{ inputs.config-value-trailing-newline }}
      run: "${{ github.action_path }}/../../scripts/main/kubernetes-manifests-package"
