# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: 'Docker Build Retag'
description: 'Pulls and retags Docker images (no push)'
author: 'kube-kaptain'

inputs:
  source-registry:
    description: 'Upstream registry (e.g., docker.io)'
    required: true
  source-image-name:
    description: 'Upstream image name (e.g., library/nginx)'
    required: true
  source-tag:
    description: 'Upstream image tag (e.g., 1.25)'
    required: true
  target-registry:
    description: 'Target container registry'
    required: false
    default: 'ghcr.io'
  target-base-path:
    description: 'Path between registry and image name (leave empty for GHCR auto-detect)'
    required: false
    default: ''
  target-image-name:
    description: 'Target image name (from version generator docker-image-name)'
    required: true
  docker-tag:
    description: 'Tag for target image (from version generator docker-tag)'
    required: true

outputs:
  source-image-full-uri:
    description: 'Full source image reference'
    value: ${{ steps.retag.outputs.SOURCE_IMAGE_FULL_URI }}
  target-image-full-uri:
    description: 'Full target image reference'
    value: ${{ steps.retag.outputs.TARGET_IMAGE_FULL_URI }}
  target-registry:
    description: 'Resolved target registry (for passing to manifest-package)'
    value: ${{ steps.resolve.outputs.target-registry }}
  target-base-path:
    description: 'Computed target base path (for passing to manifest-package)'
    value: ${{ steps.resolve.outputs.target-base-path }}

runs:
  using: 'composite'
  steps:
    - name: Resolve target registry and base path
      id: resolve
      uses: ./.github/buildon-github-actions/src/actions/resolve-target-registry-and-base-path
      with:
        target-registry: ${{ inputs.target-registry }}
        target-base-path: ${{ inputs.target-base-path }}

    - name: Pull and retag
      id: retag
      shell: bash
      env:
        LOG_ERROR_PREFIX: '::error::'
        SOURCE_REGISTRY: ${{ inputs.source-registry }}
        SOURCE_IMAGE_NAME: ${{ inputs.source-image-name }}
        SOURCE_TAG: ${{ inputs.source-tag }}
        TARGET_REGISTRY: ${{ steps.resolve.outputs.target-registry }}
        TARGET_BASE_PATH: ${{ steps.resolve.outputs.target-base-path }}
        TARGET_IMAGE_NAME: ${{ inputs.target-image-name }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
      run: "${{ github.action_path }}/../../scripts/main/docker-build-retag"
