# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Docker Build Retag'
description: 'Pulls and retags Docker images (no push)'

inputs:
  # Docker push image list file path
  docker-push-image-list-file:
    description: 'Path to file listing image URIs for docker-push-all (set by docker-registry-logins)'
    required: true
  # Docker source image configuration
  docker-source-registry:
    description: 'Upstream registry (e.g., docker.io)'
    required: true
  docker-source-namespace:
    description: 'Path segment between registry and image name (e.g., library)'
    required: false
    default: ''
  docker-source-image-name:
    description: 'Upstream image name (e.g., nginx)'
    required: true
  docker-source-tag:
    description: 'Upstream image tag (e.g., 1.25)'
    required: true

  # Target image configuration (action-specific, pre-resolved by workflow)
  docker-target-registry:
    description: 'Target container registry (pre-resolved by workflow)'
    required: true
  docker-target-namespace:
    description: 'Namespace between registry and image name (pre-resolved by workflow)'
    required: true
  docker-image-name:
    description: 'Image name (from version generator docker-image-name)'
    required: true
  docker-tag:
    description: 'Tag for target image (from version generator docker-tag)'
    required: true
  # Container runtime
  image-build-command:
    description: 'Container runtime command (podman or docker)'
    required: true
  # Target platform for docker/podman operations
  docker-platform:
    description: 'Target platform (linux/amd64, linux/arm64, or both comma-separated)'
    required: false
    default: 'linux/amd64'

outputs:
  docker-source-image-full-uri:
    description: 'Full source image reference'
    value: ${{ steps.retag.outputs.DOCKER_SOURCE_IMAGE_FULL_URI }}
  docker-target-image-full-uri:
    description: 'Full target image reference'
    value: ${{ steps.retag.outputs.DOCKER_TARGET_IMAGE_FULL_URI }}
  docker-target-registry:
    description: 'Target registry (pass-through for downstream)'
    value: ${{ inputs.docker-target-registry }}
  docker-target-namespace:
    description: 'Target namespace (pass-through for downstream)'
    value: ${{ inputs.docker-target-namespace }}

runs:
  using: 'composite'
  steps:
    - name: Pull and retag
      id: retag
      shell: bash
      env:
        BUILD_PLATFORM: github-actions
        BUILD_PLATFORM_LOG_PROVIDER: github-actions
        DOCKER_PUSH_IMAGE_LIST_FILE: ${{ inputs.docker-push-image-list-file }}
        DOCKER_SOURCE_REGISTRY: ${{ inputs.docker-source-registry }}
        DOCKER_SOURCE_NAMESPACE: ${{ inputs.docker-source-namespace }}
        DOCKER_SOURCE_IMAGE_NAME: ${{ inputs.docker-source-image-name }}
        DOCKER_SOURCE_TAG: ${{ inputs.docker-source-tag }}
        DOCKER_TARGET_REGISTRY: ${{ inputs.docker-target-registry }}
        DOCKER_TARGET_NAMESPACE: ${{ inputs.docker-target-namespace }}
        DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
        DOCKER_TAG: ${{ inputs.docker-tag }}
        IMAGE_BUILD_COMMAND: ${{ inputs.image-build-command }}
        DOCKER_PLATFORM: ${{ inputs.docker-platform }}
      run: "${{ github.action_path }}/../../scripts/main/docker-build-retag"
