# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: 'Versions & Naming'
description: 'Generates version numbers, tags, and naming for releases'

inputs:
  # Release branches
  release-branch:
    description: 'The release branch name'
    required: false
    default: 'main'
  additional-release-branches:
    description: 'Comma-separated list of additional release branches'
    required: false
    default: ''
  # Tag version calculation
  tag-version-max-parts:
    description: 'Maximum allowed version parts (fail if exceeded)'
    required: false
    default: '3'
  tag-version-calculation-strategy:
    description: 'Strategy for calculating version (git-auto-closest-highest, file-pattern-match, compound-file-pattern-match)'
    required: false
    default: 'git-auto-closest-highest'
  tag-version-pattern-type:
    description: 'Pattern type for file-pattern-match strategy (dockerfile-env-kubectl, retag-workflow-source-tag, custom)'
    required: false
    default: 'dockerfile-env-kubectl'
  tag-version-prefix-parts:
    description: 'Number of parts from source version to use as prefix (default 2, output = prefix + 1 parts)'
    required: false
    default: ''
  tag-version-source-sub-path:
    description: 'Override path to source directory (takes precedence over dockerfile-sub-path)'
    required: false
    default: ''
  tag-version-source-file-name:
    description: 'Override source file name (defaults based on pattern type)'
    required: false
    default: ''
  tag-version-source-custom-pattern:
    description: 'Regex with capture group for version extraction (required for custom pattern type)'
    required: false
    default: ''
  # Compound file-pattern-match source TWO inputs
  tag-version-source-two-sub-path:
    description: 'Path to source TWO directory (defaults to source ONE path)'
    required: false
    default: ''
  tag-version-source-two-file-name:
    description: 'Source TWO file name (defaults to source ONE file name)'
    required: false
    default: ''
  tag-version-source-two-pattern:
    description: 'Regex with capture group for source TWO (required if same file as source ONE)'
    required: false
    default: ''
  tag-version-source-two-prefix-parts:
    description: 'Number of parts from source TWO version to use in prefix (default 2)'
    required: false
    default: ''

  # Docker dockerfile path (for pattern matching)
  dockerfile-sub-path:
    description: 'Directory containing Dockerfile, relative to repo root.'
    required: false
    default: ''

outputs:
  version:
    description: 'The generated version (e.g., 1.2.3)'
    value: ${{ steps.generate.outputs.VERSION }}
  version-major:
    description: 'Major version number'
    value: ${{ steps.generate.outputs.VERSION_MAJOR }}
  version-minor:
    description: 'Minor version number'
    value: ${{ steps.generate.outputs.VERSION_MINOR }}
  version-patch:
    description: 'Patch version number'
    value: ${{ steps.generate.outputs.VERSION_PATCH }}
  version-2-part:
    description: 'Version padded/truncated to 2 parts (e.g., 1.2)'
    value: ${{ steps.generate.outputs.VERSION_2_PART }}
  version-3-part:
    description: 'Version padded/truncated to 3 parts (e.g., 1.2.3)'
    value: ${{ steps.generate.outputs.VERSION_3_PART }}
  version-4-part:
    description: 'Version padded/truncated to 4 parts (e.g., 1.2.3.0)'
    value: ${{ steps.generate.outputs.VERSION_4_PART }}
  docker-tag:
    description: 'Tag for Docker images (version or version-PRERELEASE)'
    value: ${{ steps.generate.outputs.DOCKER_TAG }}
  docker-image-name:
    description: 'Docker image name (prefix/project-name)'
    value: ${{ steps.generate.outputs.DOCKER_IMAGE_NAME }}
  git-tag:
    description: 'Tag for git (same as docker-tag)'
    value: ${{ steps.generate.outputs.GIT_TAG }}
  is-release:
    description: 'Whether this is a release build (true/false)'
    value: ${{ steps.generate.outputs.IS_RELEASE }}
  project-name:
    description: 'The repository/project name'
    value: ${{ steps.generate.outputs.PROJECT_NAME }}

runs:
  using: 'composite'
  steps:
    - name: Generate release tag
      id: generate
      shell: bash
      env:
        LOG_ERROR_PREFIX: '::error::'
        LOG_WARNING_PREFIX: '::warning::'
        BUILD_MODE: build_server
        REPOSITORY_NAME: ${{ github.event.repository.name }}
        CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}
        RELEASE_BRANCH: ${{ inputs.release-branch }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        ADDITIONAL_RELEASE_BRANCHES: ${{ inputs.additional-release-branches }}
        TAG_VERSION_MAX_PARTS: ${{ inputs.tag-version-max-parts }}
        TAG_VERSION_CALCULATION_STRATEGY: ${{ inputs.tag-version-calculation-strategy }}
        TAG_VERSION_PATTERN_TYPE: ${{ inputs.tag-version-pattern-type }}
        TAG_VERSION_PREFIX_PARTS: ${{ inputs.tag-version-prefix-parts }}
        DOCKERFILE_SUB_PATH: ${{ inputs.dockerfile-sub-path }}
        TAG_VERSION_SOURCE_SUB_PATH: ${{ inputs.tag-version-source-sub-path }}
        TAG_VERSION_SOURCE_FILE_NAME: ${{ inputs.tag-version-source-file-name }}
        TAG_VERSION_SOURCE_CUSTOM_PATTERN: ${{ inputs.tag-version-source-custom-pattern }}
        TAG_VERSION_SOURCE_TWO_SUB_PATH: ${{ inputs.tag-version-source-two-sub-path }}
        TAG_VERSION_SOURCE_TWO_FILE_NAME: ${{ inputs.tag-version-source-two-file-name }}
        TAG_VERSION_SOURCE_TWO_PATTERN: ${{ inputs.tag-version-source-two-pattern }}
        TAG_VERSION_SOURCE_TWO_PREFIX_PARTS: ${{ inputs.tag-version-source-two-prefix-parts }}
      run: "${{ github.action_path }}/../../scripts/main/versions-and-naming"
