# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: Basic Quality Checks
on:
  workflow_call:
    inputs:
      default-branch:
        description: 'The default/release branch name'
        required: false
        type: string
        default: 'main'
      additional-release-branches:
        description: 'Comma-separated list of additional release branches'
        required: false
        type: string
        default: ''
      block-slashes:
        description: 'DEPRECATED: Use block-slash-containing-branches instead'
        required: false
        type: boolean
        default: false
      block-slash-containing-branches:
        description: 'Block branch names containing slashes'
        required: false
        type: boolean
        default: false
      block-double-hyphen-containing-branches:
        description: 'Block branch names containing double hyphens (typo detection)'
        required: false
        type: boolean
        default: true
      require-conventional-branches:
        description: 'Require branch names start with feature/, fix/, etc.'
        required: false
        type: boolean
        default: false
      require-conventional-commits:
        description: 'Require commits use conventional commit format (feat:, fix:, etc.)'
        required: false
        type: boolean
        default: false
      block-conventional-commits:
        description: 'Block commits that use conventional commit format'
        required: false
        type: boolean
        default: false
jobs:
  basic-quality-checks:
    name: Basic Quality Checks
    runs-on: ubuntu-24.04
    steps:
      # INJECT: parse-workflow-ref-and-checkout
      # INJECT: basic-quality-checks
