# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: Basic Quality Checks
kaptain-order: 10
kaptain-description: Enforces basic quality - blocks bad branch names, bad commit messages, and bad branch structure
on:
  workflow_call:
    inputs:
      # INJECT-INPUT: release-branches

      # INJECT-INPUT: basic-quality-checks

      # INJECT-INPUT: hooks-pre-build
      # INJECT-INPUT: hooks-post-build

jobs:
  basic-quality-checks:
    name: Basic Quality Checks
    runs-on: ubuntu-24.04
    steps:
      # INJECT: parse-workflow-ref-and-checkout

      # === Validate Tooling ===
      # INJECT: github-check-start(name="Validate Tooling", id="check-validate-tooling")
      # INJECT: validate-tooling
      # INJECT: github-check-end(name="Validate Tooling", id="check-validate-tooling")

      # === Pre-Build ===
      # INJECT: github-check-start(name="Pre-Build", id="check-pre-build", if="inputs.hook-pre-build-script-sub-path != ''")
      # INJECT: hook-pre-build
      # INJECT: github-check-end(name="Pre-Build", id="check-pre-build", if="inputs.hook-pre-build-script-sub-path != ''")

      # === Basic Quality Checks ===
      # INJECT: github-check-start(name="Basic Quality Checks", id="check-basic-quality", if="github.event_name == 'pull_request'")
      # INJECT: basic-quality-checks
      # INJECT: github-check-end(name="Basic Quality Checks", id="check-basic-quality", if="github.event_name == 'pull_request'")

      # === Post-Build ===
      # INJECT: github-check-start(name="Post-Build", id="check-post-build", if="inputs.hook-post-build-script-sub-path != ''")
      # INJECT: hook-post-build
      # INJECT: github-check-end(name="Post-Build", id="check-post-build", if="inputs.hook-post-build-script-sub-path != ''")
