# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: Basic Quality Checks
kaptain-order: 10
kaptain-description: Enforces basic quality - blocks bad branch names, bad commit messages, and bad branch structure
on:
  workflow_call:
    inputs:
      # Quality check options
      release-branch:
        description: 'The release branch name'
        required: false
        type: string
        default: 'main'
      additional-release-branches:
        description: 'Comma-separated list of additional release branches'
        required: false
        type: string
        default: ''
      block-slashes:
        description: 'DEPRECATED: Use block-slash-containing-branches instead'
        required: false
        type: boolean
        default: false
      qc-block-slash-containing-branches:
        description: 'Block branch names containing slashes'
        required: false
        type: boolean
        default: false
      qc-block-double-hyphen-containing-branches:
        description: 'Block branch names containing double hyphens (typo detection)'
        required: false
        type: boolean
        default: true
      qc-require-conventional-branches:
        description: 'Require branch names start with feature/, fix/, etc.'
        required: false
        type: boolean
        default: false
      qc-require-conventional-commits:
        description: 'Require commits use conventional commit format (feat:, fix:, etc.)'
        required: false
        type: boolean
        default: false
      qc-block-conventional-commits:
        description: 'Block commits that use conventional commit format'
        required: false
        type: boolean
        default: false

jobs:
  basic-quality-checks:
    name: Basic Quality Checks
    runs-on: ubuntu-24.04
    steps:
      # INJECT: parse-workflow-ref-and-checkout
      # INJECT: basic-quality-checks
