# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: Basic Quality Checks
on:
  workflow_call:
    inputs:
      default-branch:
        description: 'The default/release branch name'
        required: false
        type: string
        default: 'main'
      additional-release-branches:
        description: 'Comma-separated list of additional release branches'
        required: false
        type: string
        default: ''
      block-slashes:
        description: 'Block branch names containing slashes'
        required: false
        type: boolean
        default: false
      block-double-hyphens:
        description: 'Block branch names containing double hyphens (typo detection)'
        required: false
        type: boolean
        default: true
      require-conventional-branches:
        description: 'Require branch names start with feature/, fix/, etc.'
        required: false
        type: boolean
        default: false
      require-conventional-commits:
        description: 'Require commits use conventional commit format (feat:, fix:, etc.)'
        required: false
        type: boolean
        default: false
      block-conventional-commits:
        description: 'Block commits that use conventional commit format'
        required: false
        type: boolean
        default: false
jobs:
  basic-quality-checks:
    name: Basic Quality Checks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      # INJECT: parse-workflow-ref
      - name: Basic quality checks
        uses: ./.github/buildon-github-actions/src/actions/basic-quality-checks
        with:
          default-branch: ${{ inputs.default-branch }}
          additional-release-branches: ${{ inputs.additional-release-branches }}
          block-slashes: ${{ inputs.block-slashes }}
          block-double-hyphens: ${{ inputs.block-double-hyphens }}
          require-conventional-branches: ${{ inputs.require-conventional-branches }}
          require-conventional-commits: ${{ inputs.require-conventional-commits }}
          block-conventional-commits: ${{ inputs.block-conventional-commits }}
