# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: Basic Quality and Versioning
on:
  workflow_call:
    inputs:
      default-branch:
        description: 'The default/release branch name'
        required: false
        type: string
        default: 'main'
      additional-release-branches:
        description: 'Comma-separated list of additional release branches'
        required: false
        type: string
        default: ''
      block-slashes:
        description: 'Block branch names containing slashes'
        required: false
        type: boolean
        default: false
      block-double-hyphens:
        description: 'Block branch names containing double hyphens (typo detection)'
        required: false
        type: boolean
        default: true
      require-conventional-branches:
        description: 'Require branch names start with feature/, fix/, etc.'
        required: false
        type: boolean
        default: false
      require-conventional-commits:
        description: 'Require commits use conventional commit format (feat:, fix:, etc.)'
        required: false
        type: boolean
        default: false
      block-conventional-commits:
        description: 'Block commits that use conventional commit format'
        required: false
        type: boolean
        default: false
      max-version-parts:
        description: 'Maximum allowed version parts (fail if exceeded)'
        required: false
        type: number
        default: 3
      pre-tagging-tests-script-sub-path:
        description: 'Path to pre-tagging test script relative to .github/ (e.g., bin/pre-tagging.bash)'
        required: false
        type: string
        default: ''
    outputs:
      version:
        description: 'The generated version'
        value: ${{ jobs.versions-and-naming.outputs.version }}
      version-major:
        description: 'Major version number'
        value: ${{ jobs.versions-and-naming.outputs.version-major }}
      version-minor:
        description: 'Minor version number'
        value: ${{ jobs.versions-and-naming.outputs.version-minor }}
      version-patch:
        description: 'Patch version number'
        value: ${{ jobs.versions-and-naming.outputs.version-patch }}
      version-2-part:
        description: 'Version padded/truncated to 2 parts'
        value: ${{ jobs.versions-and-naming.outputs.version-2-part }}
      version-3-part:
        description: 'Version padded/truncated to 3 parts'
        value: ${{ jobs.versions-and-naming.outputs.version-3-part }}
      version-4-part:
        description: 'Version padded/truncated to 4 parts'
        value: ${{ jobs.versions-and-naming.outputs.version-4-part }}
      docker-tag:
        description: 'Tag for Docker images'
        value: ${{ jobs.versions-and-naming.outputs.docker-tag }}
      docker-image-name:
        description: 'Docker image name (prefix/project-name)'
        value: ${{ jobs.versions-and-naming.outputs.docker-image-name }}
      is-release:
        description: 'Whether this is a release build'
        value: ${{ jobs.versions-and-naming.outputs.is-release }}
      project-name:
        description: 'The repository/project name'
        value: ${{ jobs.versions-and-naming.outputs.project-name }}
jobs:
  basic-quality-checks:
    name: Basic Quality Checks
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      # INJECT: parse-workflow-ref-and-checkout
      # INJECT: basic-quality-checks
  pre-tagging-tests:
    name: Pre-tagging Tests
    needs: basic-quality-checks
    if: always() && inputs.pre-tagging-tests-script-sub-path != '' && (needs.basic-quality-checks.result == 'success' || needs.basic-quality-checks.result == 'skipped')
    runs-on: ubuntu-24.04
    steps:
      # INJECT: parse-workflow-ref-and-checkout
      - name: Run pre-tagging tests
        uses: ./.github/buildon-github-actions/src/actions/run-test-script
        with:
          script-sub-path: ${{ inputs.pre-tagging-tests-script-sub-path }}
  versions-and-naming:
    name: Versions & Naming
    needs: pre-tagging-tests
    if: always() && (needs.pre-tagging-tests.result == 'success' || needs.pre-tagging-tests.result == 'skipped')
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      version: ${{ steps.versions.outputs.version }}
      version-major: ${{ steps.versions.outputs.version-major }}
      version-minor: ${{ steps.versions.outputs.version-minor }}
      version-patch: ${{ steps.versions.outputs.version-patch }}
      version-2-part: ${{ steps.versions.outputs.version-2-part }}
      version-3-part: ${{ steps.versions.outputs.version-3-part }}
      version-4-part: ${{ steps.versions.outputs.version-4-part }}
      docker-tag: ${{ steps.versions.outputs.docker-tag }}
      docker-image-name: ${{ steps.versions.outputs.docker-image-name }}
      is-release: ${{ steps.versions.outputs.is-release }}
      project-name: ${{ steps.versions.outputs.project-name }}
    steps:
      # INJECT: parse-workflow-ref-and-checkout
      # INJECT: versions-and-naming
