# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: Basic Quality Checks
kaptain-order: 10
kaptain-description: Enforces basic quality - blocks bad branch names, bad commit messages, and bad branch structure
on:
  workflow_call:
    inputs:
      # INJECT-INPUT: release-branches

      # INJECT-INPUT: basic-quality-checks

jobs:
  basic-quality-checks:
    name: Basic Quality Checks
    runs-on: ubuntu-24.04
    steps:
      # INJECT: parse-workflow-ref-and-checkout

      # === Validate Tooling ===
      # INJECT: github-check-start(name="Validate Tooling", id="check-validate-tooling")
      # INJECT: validate-tooling
      # INJECT: github-check-end(name="Validate Tooling", id="check-validate-tooling")

      # INJECT: basic-quality-checks
