# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: Kubernetes App - Docker Retag
on:
  workflow_call:
    inputs:
      # Source image configuration
      source-registry:
        description: 'Upstream registry (e.g., docker.io)'
        required: true
        type: string
      source-image-name:
        description: 'Upstream image name (e.g., library/nginx)'
        required: true
        type: string
      source-tag:
        description: 'Upstream image tag (e.g., 1.25)'
        required: true
        type: string
      # Manifest configuration
      manifests-sub-path:
        description: 'Directory containing Kubernetes manifests (relative)'
        required: false
        type: string
        default: 'src/kubernetes'
      substitution-token-style:
        description: 'Token delimiter syntax for variables (shell, mustache, helm, erb, github-actions, blade, stringtemplate, ognl, t4, swift)'
        required: false
        type: string
        default: 'shell'
      token-name-style:
        description: 'Case style for token names in manifests (UPPER_SNAKE, lower_snake, kebab-case, camelCase, PascalCase, lower.dot, UPPER.DOT)'
        required: false
        type: string
        default: 'PascalCase'
      token-name-validation:
        description: 'How to validate user token names (MATCH = must match token-name-style, ALL = accept any valid name)'
        required: false
        type: string
        default: 'MATCH'
      allow-builtin-token-override:
        description: 'Allow user tokens to override built-in tokens (for template/reusable projects)'
        required: false
        type: boolean
        default: false
      config-sub-path:
        description: 'Directory containing user-defined token files (relative)'
        required: false
        type: string
        default: 'src/config'
      output-sub-path:
        description: 'Build output directory (relative)'
        required: false
        type: string
        default: 'target'
      config-value-trailing-newline:
        description: 'How to handle trailing newlines in config values (strip-for-single-line, preserve-all, always-strip-one-newline)'
        required: false
        type: string
        default: 'strip-for-single-line'
      # Repo provider configuration (required - no default)
      manifests-repo-provider-type:
        description: 'Repo provider type for manifest storage (docker, github-release). Required - consumer must choose.'
        required: true
        type: string
      # Target configuration
      target-registry:
        description: 'Target container registry'
        required: false
        type: string
        default: 'ghcr.io'
      target-base-path:
        description: 'Path between registry and image name (auto-set for GHCR)'
        required: false
        type: string
        default: ''
      # Version generator inputs (pass-through)
      default-branch:
        description: 'The default/release branch name'
        required: false
        type: string
        default: 'main'
      additional-release-branches:
        description: 'Comma-separated list of additional release branches'
        required: false
        type: string
        default: ''
      max-version-parts:
        description: 'Maximum allowed version parts (fail if exceeded)'
        required: false
        type: number
        default: 3
      # Quality check inputs
      block-slashes:
        description: 'Block branch names containing slashes'
        required: false
        type: boolean
        default: false
      block-double-hyphens:
        description: 'Block branch names containing double hyphens (typo detection)'
        required: false
        type: boolean
        default: true
      require-conventional-branches:
        description: 'Require branch names start with feature/, fix/, etc.'
        required: false
        type: boolean
        default: false
      require-conventional-commits:
        description: 'Require commits use conventional commit format (feat:, fix:, etc.)'
        required: false
        type: boolean
        default: false
      block-conventional-commits:
        description: 'Block commits that use conventional commit format'
        required: false
        type: boolean
        default: false
      # Test injection points
      pre-tagging-tests-script-sub-path:
        description: 'Path to pre-tagging test script relative to .github/ (e.g., bin/pre-tagging.bash)'
        required: false
        type: string
        default: ''
      post-package-tests-script-sub-path:
        description: 'Path to post-package test script relative to .github/ (e.g., bin/post-package.bash)'
        required: false
        type: string
        default: ''
      docker-registry-logins:
        description: 'YAML config for Docker registry logins (registry URL as key)'
        required: false
        type: string
        default: ''
    secrets:
      docker-registry-logins-secrets:
        description: 'JSON object of secrets for docker-registry-logins (e.g., {"DOCKER_USER": "x", "DOCKER_PASS": "y"})'
        required: false
    outputs:
      # Version outputs
      version:
        description: 'The generated version'
        value: ${{ jobs.build.outputs.version }}
      version-major:
        description: 'Major version number'
        value: ${{ jobs.build.outputs.version-major }}
      version-minor:
        description: 'Minor version number'
        value: ${{ jobs.build.outputs.version-minor }}
      version-patch:
        description: 'Patch version number'
        value: ${{ jobs.build.outputs.version-patch }}
      version-2-part:
        description: 'Version padded/truncated to 2 parts'
        value: ${{ jobs.build.outputs.version-2-part }}
      version-3-part:
        description: 'Version padded/truncated to 3 parts'
        value: ${{ jobs.build.outputs.version-3-part }}
      version-4-part:
        description: 'Version padded/truncated to 4 parts'
        value: ${{ jobs.build.outputs.version-4-part }}
      docker-tag:
        description: 'Tag for Docker images'
        value: ${{ jobs.build.outputs.docker-tag }}
      docker-image-name:
        description: 'Docker image name'
        value: ${{ jobs.build.outputs.docker-image-name }}
      project-name:
        description: 'The repository/project name'
        value: ${{ jobs.build.outputs.project-name }}
      is-release:
        description: 'Whether this is a release build'
        value: ${{ jobs.build.outputs.is-release }}
      # Docker retag outputs
      source-image-full-uri:
        description: 'Full source image reference'
        value: ${{ jobs.build.outputs.source-image-full-uri }}
      target-image-full-uri:
        description: 'Full target image reference (action output name)'
        value: ${{ jobs.build.outputs.target-image-full-uri }}
      docker-image-full-uri:
        description: 'Full docker image reference (alias for target-image-full-uri)'
        value: ${{ jobs.build.outputs.target-image-full-uri }}
      docker-image-pushed:
        description: 'Whether docker image was pushed'
        value: ${{ jobs.build.outputs.docker-image-pushed }}
      # Manifest package outputs
      manifests-zip-sub-path:
        description: 'Directory containing manifests zip file (relative)'
        value: ${{ jobs.build.outputs.manifests-zip-sub-path }}
      manifests-zip-file-name:
        description: 'Name of manifests zip file'
        value: ${{ jobs.build.outputs.manifests-zip-file-name }}
      # Manifest repo provider publish outputs
      manifests-uri:
        description: 'Reference to published manifests (format depends on repo provider)'
        value: ${{ jobs.build.outputs.manifests-uri }}
      manifests-published:
        description: 'Whether manifests were published'
        value: ${{ jobs.build.outputs.manifests-published }}
jobs:
  basic-quality-checks:
    name: Basic Quality Checks
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      # INJECT: parse-workflow-ref-and-checkout
      # INJECT: basic-quality-checks
  build:
    name: Build & Publish
    needs: basic-quality-checks
    if: always() && (needs.basic-quality-checks.result == 'success' || needs.basic-quality-checks.result == 'skipped')
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      checks: write
    outputs:
      version: ${{ steps.versions.outputs.version }}
      version-major: ${{ steps.versions.outputs.version-major }}
      version-minor: ${{ steps.versions.outputs.version-minor }}
      version-patch: ${{ steps.versions.outputs.version-patch }}
      version-2-part: ${{ steps.versions.outputs.version-2-part }}
      version-3-part: ${{ steps.versions.outputs.version-3-part }}
      version-4-part: ${{ steps.versions.outputs.version-4-part }}
      docker-tag: ${{ steps.versions.outputs.docker-tag }}
      docker-image-name: ${{ steps.versions.outputs.docker-image-name }}
      project-name: ${{ steps.versions.outputs.project-name }}
      is-release: ${{ steps.versions.outputs.is-release }}
      source-image-full-uri: ${{ steps.docker-build.outputs.source-image-full-uri }}
      target-image-full-uri: ${{ steps.docker-build.outputs.target-image-full-uri }}
      docker-image-pushed: ${{ steps.docker-push.outputs.image-pushed }}
      manifests-zip-sub-path: ${{ steps.manifest-package.outputs.manifests-zip-sub-path }}
      manifests-zip-file-name: ${{ steps.manifest-package.outputs.manifests-zip-file-name }}
      manifests-uri: ${{ steps.manifest-repo-provider-publish.outputs.manifests-uri }}
      manifests-published: ${{ steps.manifest-repo-provider-publish.outputs.manifests-published }}
    steps:
      # INJECT: parse-workflow-ref-and-checkout

      # === Docker Registry Logins ===
      # INJECT: docker-registry-logins

      # === Pre-tagging Tests ===
      # INJECT: github-check-start(name="Pre-tagging Tests", id="check-pre-tagging", if="inputs.pre-tagging-tests-script-sub-path != ''")
      # INJECT: pre-tagging-tests
      # INJECT: github-check-end(name="Pre-tagging Tests", id="check-pre-tagging", if="inputs.pre-tagging-tests-script-sub-path != ''")

      # === Versions & Naming ===
      # INJECT: github-check-start(name="Versions & Naming", id="check-versions")
      # INJECT: versions-and-naming
      # INJECT: github-check-end(name="Versions & Naming", id="check-versions")

      # === Docker Retag ===
      # INJECT: github-check-start(name="Docker Retag", id="check-docker-retag")
      # INJECT: docker-build-retag
      # INJECT: github-check-end(name="Docker Retag", id="check-docker-retag")

      # === Manifest Package ===
      # INJECT: github-check-start(name="Package Manifests", id="check-manifest-package")
      # INJECT: manifest-package
      # INJECT: github-check-end(name="Package Manifests", id="check-manifest-package")

      # === Manifest Repo Provider Package ===
      # INJECT: github-check-start(name="Package Manifests for Repo Provider", id="check-manifest-repo-provider-package")
      # INJECT: manifest-repo-provider-package
      # INJECT: github-check-end(name="Package Manifests for Repo Provider", id="check-manifest-repo-provider-package")

      # === Post-package Tests ===
      # INJECT: github-check-start(name="Post-package Tests", id="check-post-package", if="inputs.post-package-tests-script-sub-path != ''")
      # INJECT: post-package-tests
      # INJECT: github-check-end(name="Post-package Tests", id="check-post-package", if="inputs.post-package-tests-script-sub-path != ''")

      # === Docker Push ===
      # INJECT: github-check-start(name="Docker Push", id="check-docker-push", if="steps.versions.outputs.is-release == 'true'")
      # INJECT: docker-push
      # INJECT: github-check-end(name="Docker Push", id="check-docker-push", if="steps.versions.outputs.is-release == 'true'")

      # === Manifest Repo Provider Publish ===
      # INJECT: github-check-start(name="Publish Manifests via Repo Provider", id="check-manifest-repo-provider-publish", if="steps.versions.outputs.is-release == 'true'")
      # INJECT: manifest-repo-provider-publish
      # INJECT: github-check-end(name="Publish Manifests via Repo Provider", id="check-manifest-repo-provider-publish", if="steps.versions.outputs.is-release == 'true'")
