# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: Kubernetes App - Docker Retag
on:
  workflow_call:
    inputs:
      # Source image configuration
      source-registry:
        description: 'Upstream registry (e.g., docker.io)'
        required: true
        type: string
      source-image-name:
        description: 'Upstream image name (e.g., library/nginx)'
        required: true
        type: string
      source-tag:
        description: 'Upstream image tag (e.g., 1.25)'
        required: true
        type: string
      # Manifest configuration
      manifests-path:
        description: 'Directory containing Kubernetes manifests'
        required: false
        type: string
        default: 'src/kubernetes'
      substitution-token-style:
        description: 'Token delimiter syntax for variables (shell)'
        required: false
        type: string
        default: 'shell'
      substitution-output-style:
        description: 'Case style for variable names in manifests (UPPER_SNAKE, lower_snake, kebab-case, camelCase, PascalCase)'
        required: false
        type: string
        default: 'UPPER_SNAKE'
      # Repo provider configuration (required - no default)
      manifest-repo-provider-type:
        description: 'Repo provider type for manifest storage (docker, github-release). Required - consumer must choose.'
        required: true
        type: string
      # Target configuration
      target-registry:
        description: 'Target container registry'
        required: false
        type: string
        default: 'ghcr.io'
      target-base-path:
        description: 'Path between registry and image name (auto-set for GHCR)'
        required: false
        type: string
        default: ''
      confirm-image-doesnt-exist:
        description: 'Fail if target image already exists in registry'
        required: false
        type: boolean
        default: true
      # Version generator inputs (pass-through)
      default-branch:
        description: 'The default/release branch name'
        required: false
        type: string
        default: 'main'
      additional-release-branches:
        description: 'Comma-separated list of additional release branches'
        required: false
        type: string
        default: ''
      max-version-parts:
        description: 'Maximum allowed version parts (fail if exceeded)'
        required: false
        type: number
        default: 3
      # Quality check inputs
      block-slashes:
        description: 'Block branch names containing slashes'
        required: false
        type: boolean
        default: false
      block-double-hyphens:
        description: 'Block branch names containing double hyphens (typo detection)'
        required: false
        type: boolean
        default: true
      require-conventional-branches:
        description: 'Require branch names start with feature/, fix/, etc.'
        required: false
        type: boolean
        default: false
      require-conventional-commits:
        description: 'Require commits use conventional commit format (feat:, fix:, etc.)'
        required: false
        type: boolean
        default: false
      block-conventional-commits:
        description: 'Block commits that use conventional commit format'
        required: false
        type: boolean
        default: false
      # Test injection points
      pre-tagging-tests-script-sub-path:
        description: 'Path to pre-tagging test script relative to .github/ (e.g., bin/pre-tagging.bash)'
        required: false
        type: string
        default: ''
      post-package-tests-script-sub-path:
        description: 'Path to post-package test script relative to .github/ (e.g., bin/post-package.bash)'
        required: false
        type: string
        default: ''
      docker-registry-logins:
        description: 'YAML config for Docker registry logins (registry URL as key)'
        required: false
        type: string
        default: ''
    secrets:
      docker-registry-logins-secrets:
        description: 'JSON object of secrets for docker-registry-logins (e.g., {"DOCKER_USER": "x", "DOCKER_PASS": "y"})'
        required: false
    outputs:
      # Version outputs
      version:
        description: 'The generated version'
        value: ${{ jobs.build.outputs.version }}
      version-major:
        description: 'Major version number'
        value: ${{ jobs.build.outputs.version-major }}
      version-minor:
        description: 'Minor version number'
        value: ${{ jobs.build.outputs.version-minor }}
      version-patch:
        description: 'Patch version number'
        value: ${{ jobs.build.outputs.version-patch }}
      version-2-part:
        description: 'Version padded/truncated to 2 parts'
        value: ${{ jobs.build.outputs.version-2-part }}
      version-3-part:
        description: 'Version padded/truncated to 3 parts'
        value: ${{ jobs.build.outputs.version-3-part }}
      version-4-part:
        description: 'Version padded/truncated to 4 parts'
        value: ${{ jobs.build.outputs.version-4-part }}
      docker-tag:
        description: 'Tag for Docker images'
        value: ${{ jobs.build.outputs.docker-tag }}
      docker-image-name:
        description: 'Docker image name'
        value: ${{ jobs.build.outputs.docker-image-name }}
      project-name:
        description: 'The repository/project name'
        value: ${{ jobs.build.outputs.project-name }}
      is-release:
        description: 'Whether this is a release build'
        value: ${{ jobs.build.outputs.is-release }}
      # Docker retag outputs
      source-image-full-uri:
        description: 'Full source image reference'
        value: ${{ jobs.build.outputs.source-image-full-uri }}
      target-image-full-uri:
        description: 'Full target image reference (action output name)'
        value: ${{ jobs.build.outputs.target-image-full-uri }}
      docker-image-full-uri:
        description: 'Full docker image reference (alias for target-image-full-uri)'
        value: ${{ jobs.build.outputs.target-image-full-uri }}
      docker-image-pushed:
        description: 'Whether docker image was pushed'
        value: ${{ jobs.build.outputs.docker-image-pushed }}
      # Manifest package outputs
      manifest-zip-path:
        description: 'Path to manifest zip file'
        value: ${{ jobs.build.outputs.manifest-zip-path }}
      manifest-zip-name:
        description: 'Name of manifest zip file'
        value: ${{ jobs.build.outputs.manifest-zip-name }}
      # Manifest publish outputs
      manifest-uri:
        description: 'Reference to published manifests (format depends on repo provider)'
        value: ${{ jobs.build.outputs.manifest-uri }}
      manifest-published:
        description: 'Whether manifests were published'
        value: ${{ jobs.build.outputs.manifest-published }}
jobs:
  basic-quality-checks:
    name: Basic Quality Checks
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.pull_request.head.sha }}
      # INJECT: parse-workflow-ref
      - name: Start check - Quality
        id: check-quality
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: start
          check-name: 'Quality Checks'
      - name: Basic quality checks
        id: quality
        uses: ./.github/buildon-github-actions/src/actions/basic-quality-checks
        with:
          default-branch: ${{ inputs.default-branch }}
          additional-release-branches: ${{ inputs.additional-release-branches }}
          block-slashes: ${{ inputs.block-slashes }}
          block-double-hyphens: ${{ inputs.block-double-hyphens }}
          require-conventional-branches: ${{ inputs.require-conventional-branches }}
          require-conventional-commits: ${{ inputs.require-conventional-commits }}
          block-conventional-commits: ${{ inputs.block-conventional-commits }}
      - name: Pass check - Quality
        if: success()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: pass
          check-run-id: ${{ steps.check-quality.outputs.check-run-id }}
      - name: Fail check - Quality
        if: failure()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: fail
          check-run-id: ${{ steps.check-quality.outputs.check-run-id }}
  build:
    name: Build & Publish
    needs: basic-quality-checks
    if: always() && (needs.basic-quality-checks.result == 'success' || needs.basic-quality-checks.result == 'skipped')
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      checks: write
    outputs:
      version: ${{ steps.versions.outputs.version }}
      version-major: ${{ steps.versions.outputs.version-major }}
      version-minor: ${{ steps.versions.outputs.version-minor }}
      version-patch: ${{ steps.versions.outputs.version-patch }}
      version-2-part: ${{ steps.versions.outputs.version-2-part }}
      version-3-part: ${{ steps.versions.outputs.version-3-part }}
      version-4-part: ${{ steps.versions.outputs.version-4-part }}
      docker-tag: ${{ steps.versions.outputs.docker-tag }}
      docker-image-name: ${{ steps.versions.outputs.docker-image-name }}
      project-name: ${{ steps.versions.outputs.project-name }}
      is-release: ${{ steps.versions.outputs.is-release }}
      source-image-full-uri: ${{ steps.docker-retag.outputs.source-image-full-uri }}
      target-image-full-uri: ${{ steps.docker-retag.outputs.target-image-full-uri }}
      docker-image-pushed: ${{ steps.docker-retag.outputs.image-pushed }}
      manifest-zip-path: ${{ steps.manifest-package.outputs.manifest-zip-path }}
      manifest-zip-name: ${{ steps.manifest-package.outputs.manifest-zip-name }}
      manifest-uri: ${{ steps.manifest-publish.outputs.manifest-uri }}
      manifest-published: ${{ steps.manifest-publish.outputs.manifest-published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # INJECT: parse-workflow-ref

      # === Docker Registry Logins ===
      - name: Docker registry logins
        uses: ./.github/buildon-github-actions/src/actions/docker-registry-logins
        with:
          config: ${{ inputs.docker-registry-logins }}
          secrets-json: ${{ secrets.docker-registry-logins-secrets || toJSON(secrets) }}
          target-registry: ${{ inputs.target-registry }}

      # === Pre-tagging Tests ===
      - name: Start check - Pre-tagging Tests
        if: inputs.pre-tagging-tests-script-sub-path != ''
        id: check-pre-tagging
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: start
          check-name: 'Pre-tagging Tests'
      - name: Run pre-tagging tests
        if: inputs.pre-tagging-tests-script-sub-path != ''
        id: pre-tagging-tests
        uses: ./.github/buildon-github-actions/src/actions/run-test-script
        with:
          script-sub-path: ${{ inputs.pre-tagging-tests-script-sub-path }}
      - name: Pass check - Pre-tagging Tests
        if: inputs.pre-tagging-tests-script-sub-path != '' && success()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: pass
          check-run-id: ${{ steps.check-pre-tagging.outputs.check-run-id }}
      - name: Fail check - Pre-tagging Tests
        if: inputs.pre-tagging-tests-script-sub-path != '' && failure()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: fail
          check-run-id: ${{ steps.check-pre-tagging.outputs.check-run-id }}

      # === Versions & Naming ===
      - name: Start check - Versions
        id: check-versions
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: start
          check-name: 'Versions & Naming'
      - name: Generate versions and naming
        id: versions
        uses: ./.github/buildon-github-actions/src/actions/versions-and-naming
        with:
          default-branch: ${{ inputs.default-branch }}
          additional-release-branches: ${{ inputs.additional-release-branches }}
          max-version-parts: ${{ inputs.max-version-parts }}
      - name: Pass check - Versions
        if: success()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: pass
          check-run-id: ${{ steps.check-versions.outputs.check-run-id }}
      - name: Fail check - Versions
        if: failure()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: fail
          check-run-id: ${{ steps.check-versions.outputs.check-run-id }}

      # === Docker Retag ===
      - name: Start check - Docker Retag
        id: check-docker-retag
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: start
          check-name: 'Docker Retag'
      - name: Retag and push
        id: docker-retag
        uses: ./.github/buildon-github-actions/src/actions/docker-build-retag
        with:
          source-registry: ${{ inputs.source-registry }}
          source-image-name: ${{ inputs.source-image-name }}
          source-tag: ${{ inputs.source-tag }}
          target-registry: ${{ inputs.target-registry }}
          target-base-path: ${{ inputs.target-base-path }}
          target-image-name: ${{ steps.versions.outputs.docker-image-name }}
          docker-tag: ${{ steps.versions.outputs.docker-tag }}
          is-release: ${{ steps.versions.outputs.is-release }}
          confirm-image-doesnt-exist: ${{ inputs.confirm-image-doesnt-exist }}
      - name: Pass check - Docker Retag
        if: success()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: pass
          check-run-id: ${{ steps.check-docker-retag.outputs.check-run-id }}
      - name: Fail check - Docker Retag
        if: failure()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: fail
          check-run-id: ${{ steps.check-docker-retag.outputs.check-run-id }}

      # === Manifest Package ===
      - name: Start check - Package Manifests
        id: check-manifest-package
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: start
          check-name: 'Package Manifests'
      - name: Package manifests
        id: manifest-package
        uses: ./.github/buildon-github-actions/src/actions/kubernetes-manifest-package
        with:
          manifests-path: ${{ inputs.manifests-path }}
          project-name: ${{ steps.versions.outputs.project-name }}
          version: ${{ steps.versions.outputs.version }}
          docker-tag: ${{ steps.versions.outputs.docker-tag }}
          docker-image-name: ${{ steps.versions.outputs.docker-image-name }}
          substitution-token-style: ${{ inputs.substitution-token-style }}
          substitution-output-style: ${{ inputs.substitution-output-style }}
      - name: Pass check - Package Manifests
        if: success()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: pass
          check-run-id: ${{ steps.check-manifest-package.outputs.check-run-id }}
      - name: Fail check - Package Manifests
        if: failure()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: fail
          check-run-id: ${{ steps.check-manifest-package.outputs.check-run-id }}

      # === Post-package Tests ===
      - name: Start check - Post-package Tests
        if: inputs.post-package-tests-script-sub-path != ''
        id: check-post-package
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: start
          check-name: 'Post-package Tests'
      - name: Run post-package tests
        if: inputs.post-package-tests-script-sub-path != ''
        id: post-package-tests
        uses: ./.github/buildon-github-actions/src/actions/run-test-script
        with:
          script-sub-path: ${{ inputs.post-package-tests-script-sub-path }}
          version: ${{ steps.versions.outputs.version }}
          docker-tag: ${{ steps.versions.outputs.docker-tag }}
          docker-image-name: ${{ steps.versions.outputs.docker-image-name }}
          project-name: ${{ steps.versions.outputs.project-name }}
          is-release: ${{ steps.versions.outputs.is-release }}
      - name: Pass check - Post-package Tests
        if: inputs.post-package-tests-script-sub-path != '' && success()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: pass
          check-run-id: ${{ steps.check-post-package.outputs.check-run-id }}
      - name: Fail check - Post-package Tests
        if: inputs.post-package-tests-script-sub-path != '' && failure()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: fail
          check-run-id: ${{ steps.check-post-package.outputs.check-run-id }}

      # === Manifest Publish ===
      - name: Start check - Publish Manifests
        id: check-manifest-publish
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: start
          check-name: 'Publish Manifests'
      - name: Docker registry logins (for manifest publish)
        if: inputs.manifest-repo-provider-type == 'docker'
        uses: ./.github/buildon-github-actions/src/actions/docker-registry-logins
        with:
          config: ${{ inputs.docker-registry-logins }}
          secrets-json: ${{ secrets.docker-registry-logins-secrets || toJSON(secrets) }}
          target-registry: ${{ inputs.target-registry }}
      - name: Publish manifests
        id: manifest-publish
        uses: ./.github/buildon-github-actions/src/actions/kubernetes-manifest-publish
        with:
          manifest-repo-provider-type: ${{ inputs.manifest-repo-provider-type }}
          manifest-zip-path: ${{ steps.manifest-package.outputs.manifest-zip-path }}
          manifest-zip-name: ${{ steps.manifest-package.outputs.manifest-zip-name }}
          target-registry: ${{ inputs.target-registry }}
          target-base-path: ${{ inputs.target-base-path }}
          target-image-name: ${{ steps.versions.outputs.docker-image-name }}
          docker-tag: ${{ steps.versions.outputs.docker-tag }}-manifests
          confirm-image-doesnt-exist: ${{ inputs.confirm-image-doesnt-exist }}
          version: ${{ steps.versions.outputs.version }}
          is-release: ${{ steps.versions.outputs.is-release }}
      - name: Pass check - Publish Manifests
        if: success()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: pass
          check-run-id: ${{ steps.check-manifest-publish.outputs.check-run-id }}
      - name: Fail check - Publish Manifests
        if: failure()
        uses: ./.github/buildon-github-actions/src/actions/github-check-run
        with:
          action: fail
          check-run-id: ${{ steps.check-manifest-publish.outputs.check-run-id }}
