# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: Versions & Naming
on:
  workflow_call:
    inputs:
      default-branch:
        description: 'The default/release branch name'
        required: false
        type: string
        default: 'main'
      additional-release-branches:
        description: 'Comma-separated list of additional release branches'
        required: false
        type: string
        default: ''
      max-version-parts:
        description: 'Maximum allowed version parts (fail if exceeded)'
        required: false
        type: number
        default: 3
      pre-tagging-tests-script-sub-path:
        description: 'Path to pre-tagging test script relative to .github/ (e.g., bin/pre-tagging.bash)'
        required: false
        type: string
        default: ''
    outputs:
      version:
        description: 'The generated version'
        value: ${{ jobs.versions-and-naming.outputs.version }}
      version-major:
        description: 'Major version number'
        value: ${{ jobs.versions-and-naming.outputs.version-major }}
      version-minor:
        description: 'Minor version number'
        value: ${{ jobs.versions-and-naming.outputs.version-minor }}
      version-patch:
        description: 'Patch version number'
        value: ${{ jobs.versions-and-naming.outputs.version-patch }}
      version-2-part:
        description: 'Version padded/truncated to 2 parts'
        value: ${{ jobs.versions-and-naming.outputs.version-2-part }}
      version-3-part:
        description: 'Version padded/truncated to 3 parts'
        value: ${{ jobs.versions-and-naming.outputs.version-3-part }}
      version-4-part:
        description: 'Version padded/truncated to 4 parts'
        value: ${{ jobs.versions-and-naming.outputs.version-4-part }}
      docker-tag:
        description: 'Tag for Docker images'
        value: ${{ jobs.versions-and-naming.outputs.docker-tag }}
      docker-image-name:
        description: 'Docker image name (prefix/project-name)'
        value: ${{ jobs.versions-and-naming.outputs.docker-image-name }}
      is-release:
        description: 'Whether this is a release build'
        value: ${{ jobs.versions-and-naming.outputs.is-release }}
      project-name:
        description: 'The repository/project name'
        value: ${{ jobs.versions-and-naming.outputs.project-name }}
jobs:
  versions-and-naming:
    name: Versions & Naming
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      version: ${{ steps.versions.outputs.version }}
      version-major: ${{ steps.versions.outputs.version-major }}
      version-minor: ${{ steps.versions.outputs.version-minor }}
      version-patch: ${{ steps.versions.outputs.version-patch }}
      version-2-part: ${{ steps.versions.outputs.version-2-part }}
      version-3-part: ${{ steps.versions.outputs.version-3-part }}
      version-4-part: ${{ steps.versions.outputs.version-4-part }}
      docker-tag: ${{ steps.versions.outputs.docker-tag }}
      docker-image-name: ${{ steps.versions.outputs.docker-image-name }}
      is-release: ${{ steps.versions.outputs.is-release }}
      project-name: ${{ steps.versions.outputs.project-name }}
    steps:
      # INJECT: parse-workflow-ref-and-checkout
      - name: Run pre-tagging tests
        if: inputs.pre-tagging-tests-script-sub-path != ''
        id: pre-tagging-tests
        uses: ./.github/buildon-github-actions/src/actions/run-test-script
        with:
          script-sub-path: ${{ inputs.pre-tagging-tests-script-sub-path }}
      # INJECT: versions-and-naming
