# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

name: Versions & Naming
kaptain-order: 20
kaptain-description: Calculates and sets all critical artifact naming and version/tag information, and performs a GitHub release
on:
  workflow_call:
    inputs:
      # INJECT-INPUT: output-sub-path

      # INJECT-INPUT: token-substitution

      # INJECT-INPUT: release-branches
      # INJECT-INPUT: tag-version

      # INJECT-INPUT: hooks-pre-tagging

      # INJECT-INPUT: github-release
    outputs:
      version:
        description: 'The generated version'
        value: ${{ jobs.versions-and-naming.outputs.version }}
      version-major:
        description: 'Major version number'
        value: ${{ jobs.versions-and-naming.outputs.version-major }}
      version-minor:
        description: 'Minor version number'
        value: ${{ jobs.versions-and-naming.outputs.version-minor }}
      version-patch:
        description: 'Patch version number'
        value: ${{ jobs.versions-and-naming.outputs.version-patch }}
      version-2-part:
        description: 'Version padded/truncated to 2 parts'
        value: ${{ jobs.versions-and-naming.outputs.version-2-part }}
      version-3-part:
        description: 'Version padded/truncated to 3 parts'
        value: ${{ jobs.versions-and-naming.outputs.version-3-part }}
      version-4-part:
        description: 'Version padded/truncated to 4 parts'
        value: ${{ jobs.versions-and-naming.outputs.version-4-part }}
      docker-tag:
        description: 'Tag for Docker images'
        value: ${{ jobs.versions-and-naming.outputs.docker-tag }}
      docker-image-name:
        description: 'Docker image name (prefix/project-name)'
        value: ${{ jobs.versions-and-naming.outputs.docker-image-name }}
      git-tag:
        description: 'Tag for git'
        value: ${{ jobs.versions-and-naming.outputs.git-tag }}
      is-release:
        description: 'Whether this is a release build'
        value: ${{ jobs.versions-and-naming.outputs.is-release }}
      project-name:
        description: 'The repository/project name'
        value: ${{ jobs.versions-and-naming.outputs.project-name }}
jobs:
  versions-and-naming:
    name: Versions & Naming
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      version: ${{ steps.versions.outputs.version }}
      version-major: ${{ steps.versions.outputs.version-major }}
      version-minor: ${{ steps.versions.outputs.version-minor }}
      version-patch: ${{ steps.versions.outputs.version-patch }}
      version-2-part: ${{ steps.versions.outputs.version-2-part }}
      version-3-part: ${{ steps.versions.outputs.version-3-part }}
      version-4-part: ${{ steps.versions.outputs.version-4-part }}
      docker-tag: ${{ steps.versions.outputs.docker-tag }}
      docker-image-name: ${{ steps.versions.outputs.docker-image-name }}
      git-tag: ${{ steps.versions.outputs.git-tag }}
      is-release: ${{ steps.versions.outputs.is-release }}
      project-name: ${{ steps.versions.outputs.project-name }}
    steps:
      # INJECT: parse-workflow-ref-and-checkout

      # === Resolve Registry ===
      # INJECT: resolve-registry-and-namespace

      # === Docker Registry Logins ===
      # INJECT: github-check-start(name="Docker Registry Logins", id="check-docker-registry-logins")
      # INJECT: docker-registry-logins
      # INJECT: github-check-end(name="Docker Registry Logins", id="check-docker-registry-logins")

      # === Pre-tagging Tests ===
      # INJECT: github-check-start(name="Pre-tagging Tests", id="check-pre-tagging", if="inputs.hook-pre-tagging-tests-script-sub-path != ''")
      # INJECT: hook-pre-tagging-tests
      # INJECT: github-check-end(name="Pre-tagging Tests", id="check-pre-tagging", if="inputs.hook-pre-tagging-tests-script-sub-path != ''")

      # === Versions & Naming ===
      # INJECT: github-check-start(name="Versions & Naming", id="check-versions")
      # INJECT: versions-and-naming
      # INJECT: github-check-end(name="Versions & Naming", id="check-versions")

      # === GitHub Release Prepare ===
      # INJECT: github-check-start(name="GitHub Release Prepare", id="check-github-release-prepare", if="inputs.github-release-enabled == true")
      # INJECT: github-release-prepare-no-files
      # INJECT: github-check-end(name="GitHub Release Prepare", id="check-github-release-prepare", if="inputs.github-release-enabled == true")

      # === Git Tag Push ===
      # INJECT: github-check-start(name="Git Tag Push", id="check-git-push-tag", if="steps.versions.outputs.is-release == 'true'")
      # INJECT: git-push-tag
      # INJECT: github-check-end(name="Git Tag Push", id="check-git-push-tag", if="steps.versions.outputs.is-release == 'true'")

      # === GitHub Release ===
      # INJECT: github-check-start(name="GitHub Release", id="check-github-release", if="inputs.github-release-enabled == true && steps.versions.outputs.is-release == 'true'")
      # INJECT: github-release-no-files
      # INJECT: github-check-end(name="GitHub Release", id="check-github-release", if="inputs.github-release-enabled == true && steps.versions.outputs.is-release == 'true'")
