#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# validate-layer-payload.bash - Validate a KaptainPM layer's layer-payload
# declarations against a filesystem root that represents the image contents.
#
# The same validation runs at build time (filesystem root = substituted docker
# context directory) and at consumption time (filesystem root = directory the
# layer image was extracted into). In both cases, paths declared in the
# manifest's layer-payload entries must correspond to real files under the
# given filesystem root.
#
# Currently enforces:
#   - every layer-payload entry has a non-empty source
#   - every source exists as a regular file in the context listing of
#     <fs-root> (generated by walking <fs-root> and expressing each file as
#     the image-absolute path it would occupy inside the layer image)
#   - every layer-payload entry has a non-empty destination
#   - destinations are relative (no leading '/')
#   - destinations contain no '..' path component (leading './' is allowed)
#   - destinations are globally unique across all layer-payload entries
#     (sources may repeat; destinations may not)
#
# Requires: yq, find, grep, sed, sort, and a log/log_error pair already
# sourced by the caller.

# Validate the layer-payload declarations in a KaptainPM manifest against a
# filesystem root.
#
# The caller provides the work_dir — typically a sub-path under kaptainpm or
# OUTPUT_SUB_PATH so the files land alongside the rest of the related output.
# The work dir is wiped and recreated on every call, then populated with
# layer-file-manifest.txt (sorted list of image-absolute paths that exist
# under fs_root) and seen-destinations.txt (destinations consumed as the
# loop progresses). Both files are left in place after return so they can
# be inspected for debugging. If calling more than once, use a unique dir
# for each run so all remain in place post run.
#
# Usage: validate_layer_payload <yaml-manifest-file> <fs-root-dir> <work-dir>
#
# Returns:
#   0 on success
#   non-zero if any entry fails validation (caller decides how to react)
validate_layer_payload() {
  local yaml_file="${1}"
  local fs_root="${2}"
  local work_dir="${3}"

  local payload_count
  payload_count=$(yq eval '.["layer-payload"] // [] | length' "${yaml_file}")
  if [[ "${payload_count}" -eq 0 ]]; then
    return 0
  fi

  log "Validating ${payload_count} layer-payload entry/entries..."

  rm -rf "${work_dir}"
  mkdir -p "${work_dir}"
  local manifest_file="${work_dir}/layer-file-manifest.txt"
  local seen_dests_file="${work_dir}/seen-destinations.txt"

  # Build an in-image path listing of every regular file under fs_root. Each
  # line is an image-absolute path (as the file would appear inside the
  # layer image). Example: a file at ${fs_root}/somedir/file.ext is listed
  # as /somedir/file.ext. The listing is sorted for determinism and re-used
  # for every source lookup below.
  (
    cd "${fs_root}" || exit 1
    find . -type f
  ) 2>/dev/null | sed 's|^\.||' | sort > "${manifest_file}"

  : > "${seen_dests_file}"

  local i source_path dest_path
  for ((i = 0; i < payload_count; i++)); do
    source_path=$(yq eval ".[\"layer-payload\"][${i}].source" "${yaml_file}")
    if [[ -z "${source_path}" || "${source_path}" == "null" ]]; then
      log_error "layer-payload[${i}] has no source path"
      return 1
    fi
    # Source must be a real file in the image context listing. Exact
    # whole-line match via grep -Fxq.
    if ! grep -Fxq "${source_path}" "${manifest_file}"; then
      log_error "layer-payload[${i}] source not found in context listing of ${fs_root}: ${source_path}"
      return 1
    fi

    # Destination path must be relative to consumer's repo root and contain
    # no parent-traversal, so a layer cannot write outside the repo at
    # install time.
    dest_path=$(yq eval ".[\"layer-payload\"][${i}].destination" "${yaml_file}")
    if [[ -z "${dest_path}" || "${dest_path}" == "null" ]]; then
      log_error "layer-payload[${i}] has no destination path"
      return 1
    fi
    # Reject absolute paths.
    if [[ "${dest_path}" == '/'* ]]; then
      log_error "layer-payload[${i}] destination must be relative (no leading '/'): ${dest_path}"
      return 1
    fi
    # Reject any '..' component. Matches bare '..', leading '../x', middle
    # 'x/../y', and trailing 'x/..'. Leading './' is allowed and untouched.
    if [[ "${dest_path}" =~ (^|/)'..'($|/) ]]; then
      log_error "layer-payload[${i}] destination contains parent-traversal '..': ${dest_path}"
      return 1
    fi
    # Destinations must be globally unique across the whole layer-payload.
    # Sources may repeat (same file copied to multiple places); destinations
    # may not (two entries writing to the same place is always a bug).
    if grep -Fxq "${dest_path}" "${seen_dests_file}"; then
      log_error "layer-payload[${i}] destination already used by an earlier entry: ${dest_path}"
      return 1
    fi
    echo "${dest_path}" >> "${seen_dests_file}"

    log "  payload ok: ${source_path} -> ${dest_path}"
  done
}
