name: Dog Food & All Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/basic-quality-and-versioning.yaml
    permissions:
      contents: write
      packages: write
      checks: write
