# SPDX-License-Identifier: CC0-1.0
# This example is released to the public domain. Use freely without attribution.

name: Kubernetes Generators

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/kubernetes-app-docker-dockerfile.yaml@1.1.2
    permissions:
      contents: write
      packages: write
      checks: write
